// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/yourorg/shoppilot/internal/models"
	"github.com/yourorg/shoppilot/internal/services"
)

type FakeSupplierService struct {
	CreateSupplierStub        func(context.Context, uuid.UUID, *services.CreateSupplierRequest) (*models.Supplier, error)
	createSupplierMutex       sync.RWMutex
	createSupplierArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 *services.CreateSupplierRequest
	}
	createSupplierReturns struct {
		result1 *models.Supplier
		result2 error
	}
	createSupplierReturnsOnCall map[int]struct {
		result1 *models.Supplier
		result2 error
	}
	DeleteSupplierStub        func(context.Context, uuid.UUID, uuid.UUID) error
	deleteSupplierMutex       sync.RWMutex
	deleteSupplierArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	deleteSupplierReturns struct {
		result1 error
	}
	deleteSupplierReturnsOnCall map[int]struct {
		result1 error
	}
	GetSupplierStub        func(context.Context, uuid.UUID, uuid.UUID) (*models.Supplier, error)
	getSupplierMutex       sync.RWMutex
	getSupplierArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	getSupplierReturns struct {
		result1 *models.Supplier
		result2 error
	}
	getSupplierReturnsOnCall map[int]struct {
		result1 *models.Supplier
		result2 error
	}
	ListActiveSuppliersStub        func(context.Context, uuid.UUID, int, int) ([]*models.Supplier, int, error)
	listActiveSuppliersMutex       sync.RWMutex
	listActiveSuppliersArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}
	listActiveSuppliersReturns struct {
		result1 []*models.Supplier
		result2 int
		result3 error
	}
	listActiveSuppliersReturnsOnCall map[int]struct {
		result1 []*models.Supplier
		result2 int
		result3 error
	}
	ListSuppliersStub        func(context.Context, uuid.UUID, int, int) ([]*models.Supplier, int, error)
	listSuppliersMutex       sync.RWMutex
	listSuppliersArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}
	listSuppliersReturns struct {
		result1 []*models.Supplier
		result2 int
		result3 error
	}
	listSuppliersReturnsOnCall map[int]struct {
		result1 []*models.Supplier
		result2 int
		result3 error
	}
	UpdateSupplierStub        func(context.Context, uuid.UUID, uuid.UUID, *services.UpdateSupplierRequest) error
	updateSupplierMutex       sync.RWMutex
	updateSupplierArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 *services.UpdateSupplierRequest
	}
	updateSupplierReturns struct {
		result1 error
	}
	updateSupplierReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSupplierService) CreateSupplier(arg1 context.Context, arg2 uuid.UUID, arg3 *services.CreateSupplierRequest) (*models.Supplier, error) {
	fake.createSupplierMutex.Lock()
	ret, specificReturn := fake.createSupplierReturnsOnCall[len(fake.createSupplierArgsForCall)]
	fake.createSupplierArgsForCall = append(fake.createSupplierArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 *services.CreateSupplierRequest
	}{arg1, arg2, arg3})
	stub := fake.CreateSupplierStub
	fakeReturns := fake.createSupplierReturns
	fake.recordInvocation("CreateSupplier", []interface{}{arg1, arg2, arg3})
	fake.createSupplierMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSupplierService) CreateSupplierCallCount() int {
	fake.createSupplierMutex.RLock()
	defer fake.createSupplierMutex.RUnlock()
	return len(fake.createSupplierArgsForCall)
}

func (fake *FakeSupplierService) CreateSupplierCalls(stub func(context.Context, uuid.UUID, *services.CreateSupplierRequest) (*models.Supplier, error)) {
	fake.createSupplierMutex.Lock()
	defer fake.createSupplierMutex.Unlock()
	fake.CreateSupplierStub = stub
}

func (fake *FakeSupplierService) CreateSupplierArgsForCall(i int) (context.Context, uuid.UUID, *services.CreateSupplierRequest) {
	fake.createSupplierMutex.RLock()
	defer fake.createSupplierMutex.RUnlock()
	argsForCall := fake.createSupplierArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSupplierService) CreateSupplierReturns(result1 *models.Supplier, result2 error) {
	fake.createSupplierMutex.Lock()
	defer fake.createSupplierMutex.Unlock()
	fake.CreateSupplierStub = nil
	fake.createSupplierReturns = struct {
		result1 *models.Supplier
		result2 error
	}{result1, result2}
}

func (fake *FakeSupplierService) CreateSupplierReturnsOnCall(i int, result1 *models.Supplier, result2 error) {
	fake.createSupplierMutex.Lock()
	defer fake.createSupplierMutex.Unlock()
	fake.CreateSupplierStub = nil
	if fake.createSupplierReturnsOnCall == nil {
		fake.createSupplierReturnsOnCall = make(map[int]struct {
			result1 *models.Supplier
			result2 error
		})
	}
	fake.createSupplierReturnsOnCall[i] = struct {
		result1 *models.Supplier
		result2 error
	}{result1, result2}
}

func (fake *FakeSupplierService) DeleteSupplier(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.deleteSupplierMutex.Lock()
	ret, specificReturn := fake.deleteSupplierReturnsOnCall[len(fake.deleteSupplierArgsForCall)]
	fake.deleteSupplierArgsForCall = append(fake.deleteSupplierArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.DeleteSupplierStub
	fakeReturns := fake.deleteSupplierReturns
	fake.recordInvocation("DeleteSupplier", []interface{}{arg1, arg2, arg3})
	fake.deleteSupplierMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSupplierService) DeleteSupplierCallCount() int {
	fake.deleteSupplierMutex.RLock()
	defer fake.deleteSupplierMutex.RUnlock()
	return len(fake.deleteSupplierArgsForCall)
}

func (fake *FakeSupplierService) DeleteSupplierCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.deleteSupplierMutex.Lock()
	defer fake.deleteSupplierMutex.Unlock()
	fake.DeleteSupplierStub = stub
}

func (fake *FakeSupplierService) DeleteSupplierArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.deleteSupplierMutex.RLock()
	defer fake.deleteSupplierMutex.RUnlock()
	argsForCall := fake.deleteSupplierArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSupplierService) DeleteSupplierReturns(result1 error) {
	fake.deleteSupplierMutex.Lock()
	defer fake.deleteSupplierMutex.Unlock()
	fake.DeleteSupplierStub = nil
	fake.deleteSupplierReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSupplierService) DeleteSupplierReturnsOnCall(i int, result1 error) {
	fake.deleteSupplierMutex.Lock()
	defer fake.deleteSupplierMutex.Unlock()
	fake.DeleteSupplierStub = nil
	if fake.deleteSupplierReturnsOnCall == nil {
		fake.deleteSupplierReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteSupplierReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSupplierService) GetSupplier(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (*models.Supplier, error) {
	fake.getSupplierMutex.Lock()
	ret, specificReturn := fake.getSupplierReturnsOnCall[len(fake.getSupplierArgsForCall)]
	fake.getSupplierArgsForCall = append(fake.getSupplierArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.GetSupplierStub
	fakeReturns := fake.getSupplierReturns
	fake.recordInvocation("GetSupplier", []interface{}{arg1, arg2, arg3})
	fake.getSupplierMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSupplierService) GetSupplierCallCount() int {
	fake.getSupplierMutex.RLock()
	defer fake.getSupplierMutex.RUnlock()
	return len(fake.getSupplierArgsForCall)
}

func (fake *FakeSupplierService) GetSupplierCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (*models.Supplier, error)) {
	fake.getSupplierMutex.Lock()
	defer fake.getSupplierMutex.Unlock()
	fake.GetSupplierStub = stub
}

func (fake *FakeSupplierService) GetSupplierArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.getSupplierMutex.RLock()
	defer fake.getSupplierMutex.RUnlock()
	argsForCall := fake.getSupplierArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSupplierService) GetSupplierReturns(result1 *models.Supplier, result2 error) {
	fake.getSupplierMutex.Lock()
	defer fake.getSupplierMutex.Unlock()
	fake.GetSupplierStub = nil
	fake.getSupplierReturns = struct {
		result1 *models.Supplier
		result2 error
	}{result1, result2}
}

func (fake *FakeSupplierService) GetSupplierReturnsOnCall(i int, result1 *models.Supplier, result2 error) {
	fake.getSupplierMutex.Lock()
	defer fake.getSupplierMutex.Unlock()
	fake.GetSupplierStub = nil
	if fake.getSupplierReturnsOnCall == nil {
		fake.getSupplierReturnsOnCall = make(map[int]struct {
			result1 *models.Supplier
			result2 error
		})
	}
	fake.getSupplierReturnsOnCall[i] = struct {
		result1 *models.Supplier
		result2 error
	}{result1, result2}
}

func (fake *FakeSupplierService) ListActiveSuppliers(arg1 context.Context, arg2 uuid.UUID, arg3 int, arg4 int) ([]*models.Supplier, int, error) {
	fake.listActiveSuppliersMutex.Lock()
	ret, specificReturn := fake.listActiveSuppliersReturnsOnCall[len(fake.listActiveSuppliersArgsForCall)]
	fake.listActiveSuppliersArgsForCall = append(fake.listActiveSuppliersArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListActiveSuppliersStub
	fakeReturns := fake.listActiveSuppliersReturns
	fake.recordInvocation("ListActiveSuppliers", []interface{}{arg1, arg2, arg3, arg4})
	fake.listActiveSuppliersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeSupplierService) ListActiveSuppliersCallCount() int {
	fake.listActiveSuppliersMutex.RLock()
	defer fake.listActiveSuppliersMutex.RUnlock()
	return len(fake.listActiveSuppliersArgsForCall)
}

func (fake *FakeSupplierService) ListActiveSuppliersCalls(stub func(context.Context, uuid.UUID, int, int) ([]*models.Supplier, int, error)) {
	fake.listActiveSuppliersMutex.Lock()
	defer fake.listActiveSuppliersMutex.Unlock()
	fake.ListActiveSuppliersStub = stub
}

func (fake *FakeSupplierService) ListActiveSuppliersArgsForCall(i int) (context.Context, uuid.UUID, int, int) {
	fake.listActiveSuppliersMutex.RLock()
	defer fake.listActiveSuppliersMutex.RUnlock()
	argsForCall := fake.listActiveSuppliersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeSupplierService) ListActiveSuppliersReturns(result1 []*models.Supplier, result2 int, result3 error) {
	fake.listActiveSuppliersMutex.Lock()
	defer fake.listActiveSuppliersMutex.Unlock()
	fake.ListActiveSuppliersStub = nil
	fake.listActiveSuppliersReturns = struct {
		result1 []*models.Supplier
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeSupplierService) ListActiveSuppliersReturnsOnCall(i int, result1 []*models.Supplier, result2 int, result3 error) {
	fake.listActiveSuppliersMutex.Lock()
	defer fake.listActiveSuppliersMutex.Unlock()
	fake.ListActiveSuppliersStub = nil
	if fake.listActiveSuppliersReturnsOnCall == nil {
		fake.listActiveSuppliersReturnsOnCall = make(map[int]struct {
			result1 []*models.Supplier
			result2 int
			result3 error
		})
	}
	fake.listActiveSuppliersReturnsOnCall[i] = struct {
		result1 []*models.Supplier
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeSupplierService) ListSuppliers(arg1 context.Context, arg2 uuid.UUID, arg3 int, arg4 int) ([]*models.Supplier, int, error) {
	fake.listSuppliersMutex.Lock()
	ret, specificReturn := fake.listSuppliersReturnsOnCall[len(fake.listSuppliersArgsForCall)]
	fake.listSuppliersArgsForCall = append(fake.listSuppliersArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListSuppliersStub
	fakeReturns := fake.listSuppliersReturns
	fake.recordInvocation("ListSuppliers", []interface{}{arg1, arg2, arg3, arg4})
	fake.listSuppliersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeSupplierService) ListSuppliersCallCount() int {
	fake.listSuppliersMutex.RLock()
	defer fake.listSuppliersMutex.RUnlock()
	return len(fake.listSuppliersArgsForCall)
}

func (fake *FakeSupplierService) ListSuppliersCalls(stub func(context.Context, uuid.UUID, int, int) ([]*models.Supplier, int, error)) {
	fake.listSuppliersMutex.Lock()
	defer fake.listSuppliersMutex.Unlock()
	fake.ListSuppliersStub = stub
}

func (fake *FakeSupplierService) ListSuppliersArgsForCall(i int) (context.Context, uuid.UUID, int, int) {
	fake.listSuppliersMutex.RLock()
	defer fake.listSuppliersMutex.RUnlock()
	argsForCall := fake.listSuppliersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeSupplierService) ListSuppliersReturns(result1 []*models.Supplier, result2 int, result3 error) {
	fake.listSuppliersMutex.Lock()
	defer fake.listSuppliersMutex.Unlock()
	fake.ListSuppliersStub = nil
	fake.listSuppliersReturns = struct {
		result1 []*models.Supplier
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeSupplierService) ListSuppliersReturnsOnCall(i int, result1 []*models.Supplier, result2 int, result3 error) {
	fake.listSuppliersMutex.Lock()
	defer fake.listSuppliersMutex.Unlock()
	fake.ListSuppliersStub = nil
	if fake.listSuppliersReturnsOnCall == nil {
		fake.listSuppliersReturnsOnCall = make(map[int]struct {
			result1 []*models.Supplier
			result2 int
			result3 error
		})
	}
	fake.listSuppliersReturnsOnCall[i] = struct {
		result1 []*models.Supplier
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeSupplierService) UpdateSupplier(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 *services.UpdateSupplierRequest) error {
	fake.updateSupplierMutex.Lock()
	ret, specificReturn := fake.updateSupplierReturnsOnCall[len(fake.updateSupplierArgsForCall)]
	fake.updateSupplierArgsForCall = append(fake.updateSupplierArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 *services.UpdateSupplierRequest
	}{arg1, arg2, arg3, arg4})
	stub := fake.UpdateSupplierStub
	fakeReturns := fake.updateSupplierReturns
	fake.recordInvocation("UpdateSupplier", []interface{}{arg1, arg2, arg3, arg4})
	fake.updateSupplierMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSupplierService) UpdateSupplierCallCount() int {
	fake.updateSupplierMutex.RLock()
	defer fake.updateSupplierMutex.RUnlock()
	return len(fake.updateSupplierArgsForCall)
}

func (fake *FakeSupplierService) UpdateSupplierCalls(stub func(context.Context, uuid.UUID, uuid.UUID, *services.UpdateSupplierRequest) error) {
	fake.updateSupplierMutex.Lock()
	defer fake.updateSupplierMutex.Unlock()
	fake.UpdateSupplierStub = stub
}

func (fake *FakeSupplierService) UpdateSupplierArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, *services.UpdateSupplierRequest) {
	fake.updateSupplierMutex.RLock()
	defer fake.updateSupplierMutex.RUnlock()
	argsForCall := fake.updateSupplierArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeSupplierService) UpdateSupplierReturns(result1 error) {
	fake.updateSupplierMutex.Lock()
	defer fake.updateSupplierMutex.Unlock()
	fake.UpdateSupplierStub = nil
	fake.updateSupplierReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSupplierService) UpdateSupplierReturnsOnCall(i int, result1 error) {
	fake.updateSupplierMutex.Lock()
	defer fake.updateSupplierMutex.Unlock()
	fake.UpdateSupplierStub = nil
	if fake.updateSupplierReturnsOnCall == nil {
		fake.updateSupplierReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateSupplierReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSupplierService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSupplierService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ services.SupplierService = new(FakeSupplierService)
