// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/yourorg/shoppilot/internal/models"
	"github.com/yourorg/shoppilot/internal/services"
)

type FakeCustomerService struct {
	CreateCustomerStub        func(context.Context, uuid.UUID, *services.CreateCustomerRequest) (*models.Customer, error)
	createCustomerMutex       sync.RWMutex
	createCustomerArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 *services.CreateCustomerRequest
	}
	createCustomerReturns struct {
		result1 *models.Customer
		result2 error
	}
	createCustomerReturnsOnCall map[int]struct {
		result1 *models.Customer
		result2 error
	}
	DeleteCustomerStub        func(context.Context, uuid.UUID, uuid.UUID) error
	deleteCustomerMutex       sync.RWMutex
	deleteCustomerArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	deleteCustomerReturns struct {
		result1 error
	}
	deleteCustomerReturnsOnCall map[int]struct {
		result1 error
	}
	GetCustomerStub        func(context.Context, uuid.UUID, uuid.UUID) (*models.Customer, error)
	getCustomerMutex       sync.RWMutex
	getCustomerArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	getCustomerReturns struct {
		result1 *models.Customer
		result2 error
	}
	getCustomerReturnsOnCall map[int]struct {
		result1 *models.Customer
		result2 error
	}
	ListCustomersStub        func(context.Context, uuid.UUID, int, int) ([]*models.Customer, int, error)
	listCustomersMutex       sync.RWMutex
	listCustomersArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}
	listCustomersReturns struct {
		result1 []*models.Customer
		result2 int
		result3 error
	}
	listCustomersReturnsOnCall map[int]struct {
		result1 []*models.Customer
		result2 int
		result3 error
	}
	SearchCustomersStub        func(context.Context, uuid.UUID, string, int, int) ([]*models.Customer, int, error)
	searchCustomersMutex       sync.RWMutex
	searchCustomersArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
		arg4 int
		arg5 int
	}
	searchCustomersReturns struct {
		result1 []*models.Customer
		result2 int
		result3 error
	}
	searchCustomersReturnsOnCall map[int]struct {
		result1 []*models.Customer
		result2 int
		result3 error
	}
	UpdateCustomerStub        func(context.Context, uuid.UUID, uuid.UUID, *services.UpdateCustomerRequest) error
	updateCustomerMutex       sync.RWMutex
	updateCustomerArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 *services.UpdateCustomerRequest
	}
	updateCustomerReturns struct {
		result1 error
	}
	updateCustomerReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCustomerService) CreateCustomer(arg1 context.Context, arg2 uuid.UUID, arg3 *services.CreateCustomerRequest) (*models.Customer, error) {
	fake.createCustomerMutex.Lock()
	ret, specificReturn := fake.createCustomerReturnsOnCall[len(fake.createCustomerArgsForCall)]
	fake.createCustomerArgsForCall = append(fake.createCustomerArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 *services.CreateCustomerRequest
	}{arg1, arg2, arg3})
	stub := fake.CreateCustomerStub
	fakeReturns := fake.createCustomerReturns
	fake.recordInvocation("CreateCustomer", []interface{}{arg1, arg2, arg3})
	fake.createCustomerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCustomerService) CreateCustomerCallCount() int {
	fake.createCustomerMutex.RLock()
	defer fake.createCustomerMutex.RUnlock()
	return len(fake.createCustomerArgsForCall)
}

func (fake *FakeCustomerService) CreateCustomerCalls(stub func(context.Context, uuid.UUID, *services.CreateCustomerRequest) (*models.Customer, error)) {
	fake.createCustomerMutex.Lock()
	defer fake.createCustomerMutex.Unlock()
	fake.CreateCustomerStub = stub
}

func (fake *FakeCustomerService) CreateCustomerArgsForCall(i int) (context.Context, uuid.UUID, *services.CreateCustomerRequest) {
	fake.createCustomerMutex.RLock()
	defer fake.createCustomerMutex.RUnlock()
	argsForCall := fake.createCustomerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeCustomerService) CreateCustomerReturns(result1 *models.Customer, result2 error) {
	fake.createCustomerMutex.Lock()
	defer fake.createCustomerMutex.Unlock()
	fake.CreateCustomerStub = nil
	fake.createCustomerReturns = struct {
		result1 *models.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerService) CreateCustomerReturnsOnCall(i int, result1 *models.Customer, result2 error) {
	fake.createCustomerMutex.Lock()
	defer fake.createCustomerMutex.Unlock()
	fake.CreateCustomerStub = nil
	if fake.createCustomerReturnsOnCall == nil {
		fake.createCustomerReturnsOnCall = make(map[int]struct {
			result1 *models.Customer
			result2 error
		})
	}
	fake.createCustomerReturnsOnCall[i] = struct {
		result1 *models.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerService) DeleteCustomer(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.deleteCustomerMutex.Lock()
	ret, specificReturn := fake.deleteCustomerReturnsOnCall[len(fake.deleteCustomerArgsForCall)]
	fake.deleteCustomerArgsForCall = append(fake.deleteCustomerArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.DeleteCustomerStub
	fakeReturns := fake.deleteCustomerReturns
	fake.recordInvocation("DeleteCustomer", []interface{}{arg1, arg2, arg3})
	fake.deleteCustomerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCustomerService) DeleteCustomerCallCount() int {
	fake.deleteCustomerMutex.RLock()
	defer fake.deleteCustomerMutex.RUnlock()
	return len(fake.deleteCustomerArgsForCall)
}

func (fake *FakeCustomerService) DeleteCustomerCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.deleteCustomerMutex.Lock()
	defer fake.deleteCustomerMutex.Unlock()
	fake.DeleteCustomerStub = stub
}

func (fake *FakeCustomerService) DeleteCustomerArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.deleteCustomerMutex.RLock()
	defer fake.deleteCustomerMutex.RUnlock()
	argsForCall := fake.deleteCustomerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeCustomerService) DeleteCustomerReturns(result1 error) {
	fake.deleteCustomerMutex.Lock()
	defer fake.deleteCustomerMutex.Unlock()
	fake.DeleteCustomerStub = nil
	fake.deleteCustomerReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCustomerService) DeleteCustomerReturnsOnCall(i int, result1 error) {
	fake.deleteCustomerMutex.Lock()
	defer fake.deleteCustomerMutex.Unlock()
	fake.DeleteCustomerStub = nil
	if fake.deleteCustomerReturnsOnCall == nil {
		fake.deleteCustomerReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteCustomerReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCustomerService) GetCustomer(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (*models.Customer, error) {
	fake.getCustomerMutex.Lock()
	ret, specificReturn := fake.getCustomerReturnsOnCall[len(fake.getCustomerArgsForCall)]
	fake.getCustomerArgsForCall = append(fake.getCustomerArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.GetCustomerStub
	fakeReturns := fake.getCustomerReturns
	fake.recordInvocation("GetCustomer", []interface{}{arg1, arg2, arg3})
	fake.getCustomerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCustomerService) GetCustomerCallCount() int {
	fake.getCustomerMutex.RLock()
	defer fake.getCustomerMutex.RUnlock()
	return len(fake.getCustomerArgsForCall)
}

func (fake *FakeCustomerService) GetCustomerCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (*models.Customer, error)) {
	fake.getCustomerMutex.Lock()
	defer fake.getCustomerMutex.Unlock()
	fake.GetCustomerStub = stub
}

func (fake *FakeCustomerService) GetCustomerArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.getCustomerMutex.RLock()
	defer fake.getCustomerMutex.RUnlock()
	argsForCall := fake.getCustomerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeCustomerService) GetCustomerReturns(result1 *models.Customer, result2 error) {
	fake.getCustomerMutex.Lock()
	defer fake.getCustomerMutex.Unlock()
	fake.GetCustomerStub = nil
	fake.getCustomerReturns = struct {
		result1 *models.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerService) GetCustomerReturnsOnCall(i int, result1 *models.Customer, result2 error) {
	fake.getCustomerMutex.Lock()
	defer fake.getCustomerMutex.Unlock()
	fake.GetCustomerStub = nil
	if fake.getCustomerReturnsOnCall == nil {
		fake.getCustomerReturnsOnCall = make(map[int]struct {
			result1 *models.Customer
			result2 error
		})
	}
	fake.getCustomerReturnsOnCall[i] = struct {
		result1 *models.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerService) ListCustomers(arg1 context.Context, arg2 uuid.UUID, arg3 int, arg4 int) ([]*models.Customer, int, error) {
	fake.listCustomersMutex.Lock()
	ret, specificReturn := fake.listCustomersReturnsOnCall[len(fake.listCustomersArgsForCall)]
	fake.listCustomersArgsForCall = append(fake.listCustomersArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListCustomersStub
	fakeReturns := fake.listCustomersReturns
	fake.recordInvocation("ListCustomers", []interface{}{arg1, arg2, arg3, arg4})
	fake.listCustomersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeCustomerService) ListCustomersCallCount() int {
	fake.listCustomersMutex.RLock()
	defer fake.listCustomersMutex.RUnlock()
	return len(fake.listCustomersArgsForCall)
}

func (fake *FakeCustomerService) ListCustomersCalls(stub func(context.Context, uuid.UUID, int, int) ([]*models.Customer, int, error)) {
	fake.listCustomersMutex.Lock()
	defer fake.listCustomersMutex.Unlock()
	fake.ListCustomersStub = stub
}

func (fake *FakeCustomerService) ListCustomersArgsForCall(i int) (context.Context, uuid.UUID, int, int) {
	fake.listCustomersMutex.RLock()
	defer fake.listCustomersMutex.RUnlock()
	argsForCall := fake.listCustomersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeCustomerService) ListCustomersReturns(result1 []*models.Customer, result2 int, result3 error) {
	fake.listCustomersMutex.Lock()
	defer fake.listCustomersMutex.Unlock()
	fake.ListCustomersStub = nil
	fake.listCustomersReturns = struct {
		result1 []*models.Customer
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCustomerService) ListCustomersReturnsOnCall(i int, result1 []*models.Customer, result2 int, result3 error) {
	fake.listCustomersMutex.Lock()
	defer fake.listCustomersMutex.Unlock()
	fake.ListCustomersStub = nil
	if fake.listCustomersReturnsOnCall == nil {
		fake.listCustomersReturnsOnCall = make(map[int]struct {
			result1 []*models.Customer
			result2 int
			result3 error
		})
	}
	fake.listCustomersReturnsOnCall[i] = struct {
		result1 []*models.Customer
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCustomerService) SearchCustomers(arg1 context.Context, arg2 uuid.UUID, arg3 string, arg4 int, arg5 int) ([]*models.Customer, int, error) {
	fake.searchCustomersMutex.Lock()
	ret, specificReturn := fake.searchCustomersReturnsOnCall[len(fake.searchCustomersArgsForCall)]
	fake.searchCustomersArgsForCall = append(fake.searchCustomersArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
		arg4 int
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.SearchCustomersStub
	fakeReturns := fake.searchCustomersReturns
	fake.recordInvocation("SearchCustomers", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.searchCustomersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeCustomerService) SearchCustomersCallCount() int {
	fake.searchCustomersMutex.RLock()
	defer fake.searchCustomersMutex.RUnlock()
	return len(fake.searchCustomersArgsForCall)
}

func (fake *FakeCustomerService) SearchCustomersCalls(stub func(context.Context, uuid.UUID, string, int, int) ([]*models.Customer, int, error)) {
	fake.searchCustomersMutex.Lock()
	defer fake.searchCustomersMutex.Unlock()
	fake.SearchCustomersStub = stub
}

func (fake *FakeCustomerService) SearchCustomersArgsForCall(i int) (context.Context, uuid.UUID, string, int, int) {
	fake.searchCustomersMutex.RLock()
	defer fake.searchCustomersMutex.RUnlock()
	argsForCall := fake.searchCustomersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeCustomerService) SearchCustomersReturns(result1 []*models.Customer, result2 int, result3 error) {
	fake.searchCustomersMutex.Lock()
	defer fake.searchCustomersMutex.Unlock()
	fake.SearchCustomersStub = nil
	fake.searchCustomersReturns = struct {
		result1 []*models.Customer
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCustomerService) SearchCustomersReturnsOnCall(i int, result1 []*models.Customer, result2 int, result3 error) {
	fake.searchCustomersMutex.Lock()
	defer fake.searchCustomersMutex.Unlock()
	fake.SearchCustomersStub = nil
	if fake.searchCustomersReturnsOnCall == nil {
		fake.searchCustomersReturnsOnCall = make(map[int]struct {
			result1 []*models.Customer
			result2 int
			result3 error
		})
	}
	fake.searchCustomersReturnsOnCall[i] = struct {
		result1 []*models.Customer
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeCustomerService) UpdateCustomer(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 *services.UpdateCustomerRequest) error {
	fake.updateCustomerMutex.Lock()
	ret, specificReturn := fake.updateCustomerReturnsOnCall[len(fake.updateCustomerArgsForCall)]
	fake.updateCustomerArgsForCall = append(fake.updateCustomerArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 *services.UpdateCustomerRequest
	}{arg1, arg2, arg3, arg4})
	stub := fake.UpdateCustomerStub
	fakeReturns := fake.updateCustomerReturns
	fake.recordInvocation("UpdateCustomer", []interface{}{arg1, arg2, arg3, arg4})
	fake.updateCustomerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCustomerService) UpdateCustomerCallCount() int {
	fake.updateCustomerMutex.RLock()
	defer fake.updateCustomerMutex.RUnlock()
	return len(fake.updateCustomerArgsForCall)
}

func (fake *FakeCustomerService) UpdateCustomerCalls(stub func(context.Context, uuid.UUID, uuid.UUID, *services.UpdateCustomerRequest) error) {
	fake.updateCustomerMutex.Lock()
	defer fake.updateCustomerMutex.Unlock()
	fake.UpdateCustomerStub = stub
}

func (fake *FakeCustomerService) UpdateCustomerArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, *services.UpdateCustomerRequest) {
	fake.updateCustomerMutex.RLock()
	defer fake.updateCustomerMutex.RUnlock()
	argsForCall := fake.updateCustomerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeCustomerService) UpdateCustomerReturns(result1 error) {
	fake.updateCustomerMutex.Lock()
	defer fake.updateCustomerMutex.Unlock()
	fake.UpdateCustomerStub = nil
	fake.updateCustomerReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCustomerService) UpdateCustomerReturnsOnCall(i int, result1 error) {
	fake.updateCustomerMutex.Lock()
	defer fake.updateCustomerMutex.Unlock()
	fake.UpdateCustomerStub = nil
	if fake.updateCustomerReturnsOnCall == nil {
		fake.updateCustomerReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateCustomerReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCustomerService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCustomerService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ services.CustomerService = new(FakeCustomerService)
