// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/yourorg/shoppilot/internal/models"
	"github.com/yourorg/shoppilot/internal/services"
)

type FakeProductService struct {
	AdjustInventoryStub        func(context.Context, uuid.UUID, uuid.UUID, int) error
	adjustInventoryMutex       sync.RWMutex
	adjustInventoryArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
	}
	adjustInventoryReturns struct {
		result1 error
	}
	adjustInventoryReturnsOnCall map[int]struct {
		result1 error
	}
	CheckLowStockAlertsStub        func(context.Context, uuid.UUID, uuid.UUID) ([]*models.InventoryAlert, error)
	checkLowStockAlertsMutex       sync.RWMutex
	checkLowStockAlertsArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	checkLowStockAlertsReturns struct {
		result1 []*models.InventoryAlert
		result2 error
	}
	checkLowStockAlertsReturnsOnCall map[int]struct {
		result1 []*models.InventoryAlert
		result2 error
	}
	CheckStockStub        func(context.Context, uuid.UUID, uuid.UUID) (int, error)
	checkStockMutex       sync.RWMutex
	checkStockArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	checkStockReturns struct {
		result1 int
		result2 error
	}
	checkStockReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	CreateProductStub        func(context.Context, *services.CreateProductRequest) (*models.Product, error)
	createProductMutex       sync.RWMutex
	createProductArgsForCall []struct {
		arg1 context.Context
		arg2 *services.CreateProductRequest
	}
	createProductReturns struct {
		result1 *models.Product
		result2 error
	}
	createProductReturnsOnCall map[int]struct {
		result1 *models.Product
		result2 error
	}
	CreateVariantStub        func(context.Context, uuid.UUID, uuid.UUID, *services.CreateVariantRequest) (*models.ProductVariant, error)
	createVariantMutex       sync.RWMutex
	createVariantArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 *services.CreateVariantRequest
	}
	createVariantReturns struct {
		result1 *models.ProductVariant
		result2 error
	}
	createVariantReturnsOnCall map[int]struct {
		result1 *models.ProductVariant
		result2 error
	}
	DeleteProductStub        func(context.Context, uuid.UUID, uuid.UUID) error
	deleteProductMutex       sync.RWMutex
	deleteProductArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	deleteProductReturns struct {
		result1 error
	}
	deleteProductReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteVariantStub        func(context.Context, uuid.UUID, uuid.UUID) error
	deleteVariantMutex       sync.RWMutex
	deleteVariantArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	deleteVariantReturns struct {
		result1 error
	}
	deleteVariantReturnsOnCall map[int]struct {
		result1 error
	}
	GetInventoryAlertStub        func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (*models.InventoryAlert, error)
	getInventoryAlertMutex       sync.RWMutex
	getInventoryAlertArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 uuid.UUID
	}
	getInventoryAlertReturns struct {
		result1 *models.InventoryAlert
		result2 error
	}
	getInventoryAlertReturnsOnCall map[int]struct {
		result1 *models.InventoryAlert
		result2 error
	}
	GetMovementHistoryStub        func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]*models.InventoryMovement, int, error)
	getMovementHistoryMutex       sync.RWMutex
	getMovementHistoryArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
		arg5 int
	}
	getMovementHistoryReturns struct {
		result1 []*models.InventoryMovement
		result2 int
		result3 error
	}
	getMovementHistoryReturnsOnCall map[int]struct {
		result1 []*models.InventoryMovement
		result2 int
		result3 error
	}
	GetProductStub        func(context.Context, uuid.UUID, uuid.UUID) (*models.Product, error)
	getProductMutex       sync.RWMutex
	getProductArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	getProductReturns struct {
		result1 *models.Product
		result2 error
	}
	getProductReturnsOnCall map[int]struct {
		result1 *models.Product
		result2 error
	}
	GetVariantStub        func(context.Context, uuid.UUID, uuid.UUID) (*models.ProductVariant, error)
	getVariantMutex       sync.RWMutex
	getVariantArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	getVariantReturns struct {
		result1 *models.ProductVariant
		result2 error
	}
	getVariantReturnsOnCall map[int]struct {
		result1 *models.ProductVariant
		result2 error
	}
	ListProductsStub        func(context.Context, uuid.UUID, *uuid.UUID, int, int) ([]*models.Product, int, error)
	listProductsMutex       sync.RWMutex
	listProductsArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 *uuid.UUID
		arg4 int
		arg5 int
	}
	listProductsReturns struct {
		result1 []*models.Product
		result2 int
		result3 error
	}
	listProductsReturnsOnCall map[int]struct {
		result1 []*models.Product
		result2 int
		result3 error
	}
	ListVariantsStub        func(context.Context, uuid.UUID, uuid.UUID) ([]*models.ProductVariant, error)
	listVariantsMutex       sync.RWMutex
	listVariantsArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	listVariantsReturns struct {
		result1 []*models.ProductVariant
		result2 error
	}
	listVariantsReturnsOnCall map[int]struct {
		result1 []*models.ProductVariant
		result2 error
	}
	RecordMovementStub        func(context.Context, *services.RecordMovementRequest) (*models.InventoryMovement, error)
	recordMovementMutex       sync.RWMutex
	recordMovementArgsForCall []struct {
		arg1 context.Context
		arg2 *services.RecordMovementRequest
	}
	recordMovementReturns struct {
		result1 *models.InventoryMovement
		result2 error
	}
	recordMovementReturnsOnCall map[int]struct {
		result1 *models.InventoryMovement
		result2 error
	}
	SearchProductsStub        func(context.Context, uuid.UUID, string, int, int) ([]*models.Product, int, error)
	searchProductsMutex       sync.RWMutex
	searchProductsArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
		arg4 int
		arg5 int
	}
	searchProductsReturns struct {
		result1 []*models.Product
		result2 int
		result3 error
	}
	searchProductsReturnsOnCall map[int]struct {
		result1 []*models.Product
		result2 int
		result3 error
	}
	SetInventoryStub        func(context.Context, uuid.UUID, uuid.UUID, int) error
	setInventoryMutex       sync.RWMutex
	setInventoryArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
	}
	setInventoryReturns struct {
		result1 error
	}
	setInventoryReturnsOnCall map[int]struct {
		result1 error
	}
	SetInventoryAlertStub        func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, *services.SetInventoryAlertRequest) (*models.InventoryAlert, error)
	setInventoryAlertMutex       sync.RWMutex
	setInventoryAlertArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 uuid.UUID
		arg5 *services.SetInventoryAlertRequest
	}
	setInventoryAlertReturns struct {
		result1 *models.InventoryAlert
		result2 error
	}
	setInventoryAlertReturnsOnCall map[int]struct {
		result1 *models.InventoryAlert
		result2 error
	}
	UpdateProductStub        func(context.Context, uuid.UUID, uuid.UUID, *services.UpdateProductRequest) error
	updateProductMutex       sync.RWMutex
	updateProductArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 *services.UpdateProductRequest
	}
	updateProductReturns struct {
		result1 error
	}
	updateProductReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateVariantStub        func(context.Context, uuid.UUID, uuid.UUID, *services.UpdateVariantRequest) error
	updateVariantMutex       sync.RWMutex
	updateVariantArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 *services.UpdateVariantRequest
	}
	updateVariantReturns struct {
		result1 error
	}
	updateVariantReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProductService) AdjustInventory(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 int) error {
	fake.adjustInventoryMutex.Lock()
	ret, specificReturn := fake.adjustInventoryReturnsOnCall[len(fake.adjustInventoryArgsForCall)]
	fake.adjustInventoryArgsForCall = append(fake.adjustInventoryArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.AdjustInventoryStub
	fakeReturns := fake.adjustInventoryReturns
	fake.recordInvocation("AdjustInventory", []interface{}{arg1, arg2, arg3, arg4})
	fake.adjustInventoryMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProductService) AdjustInventoryCallCount() int {
	fake.adjustInventoryMutex.RLock()
	defer fake.adjustInventoryMutex.RUnlock()
	return len(fake.adjustInventoryArgsForCall)
}

func (fake *FakeProductService) AdjustInventoryCalls(stub func(context.Context, uuid.UUID, uuid.UUID, int) error) {
	fake.adjustInventoryMutex.Lock()
	defer fake.adjustInventoryMutex.Unlock()
	fake.AdjustInventoryStub = stub
}

func (fake *FakeProductService) AdjustInventoryArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, int) {
	fake.adjustInventoryMutex.RLock()
	defer fake.adjustInventoryMutex.RUnlock()
	argsForCall := fake.adjustInventoryArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeProductService) AdjustInventoryReturns(result1 error) {
	fake.adjustInventoryMutex.Lock()
	defer fake.adjustInventoryMutex.Unlock()
	fake.AdjustInventoryStub = nil
	fake.adjustInventoryReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductService) AdjustInventoryReturnsOnCall(i int, result1 error) {
	fake.adjustInventoryMutex.Lock()
	defer fake.adjustInventoryMutex.Unlock()
	fake.AdjustInventoryStub = nil
	if fake.adjustInventoryReturnsOnCall == nil {
		fake.adjustInventoryReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.adjustInventoryReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductService) CheckLowStockAlerts(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) ([]*models.InventoryAlert, error) {
	fake.checkLowStockAlertsMutex.Lock()
	ret, specificReturn := fake.checkLowStockAlertsReturnsOnCall[len(fake.checkLowStockAlertsArgsForCall)]
	fake.checkLowStockAlertsArgsForCall = append(fake.checkLowStockAlertsArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.CheckLowStockAlertsStub
	fakeReturns := fake.checkLowStockAlertsReturns
	fake.recordInvocation("CheckLowStockAlerts", []interface{}{arg1, arg2, arg3})
	fake.checkLowStockAlertsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProductService) CheckLowStockAlertsCallCount() int {
	fake.checkLowStockAlertsMutex.RLock()
	defer fake.checkLowStockAlertsMutex.RUnlock()
	return len(fake.checkLowStockAlertsArgsForCall)
}

func (fake *FakeProductService) CheckLowStockAlertsCalls(stub func(context.Context, uuid.UUID, uuid.UUID) ([]*models.InventoryAlert, error)) {
	fake.checkLowStockAlertsMutex.Lock()
	defer fake.checkLowStockAlertsMutex.Unlock()
	fake.CheckLowStockAlertsStub = stub
}

func (fake *FakeProductService) CheckLowStockAlertsArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.checkLowStockAlertsMutex.RLock()
	defer fake.checkLowStockAlertsMutex.RUnlock()
	argsForCall := fake.checkLowStockAlertsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProductService) CheckLowStockAlertsReturns(result1 []*models.InventoryAlert, result2 error) {
	fake.checkLowStockAlertsMutex.Lock()
	defer fake.checkLowStockAlertsMutex.Unlock()
	fake.CheckLowStockAlertsStub = nil
	fake.checkLowStockAlertsReturns = struct {
		result1 []*models.InventoryAlert
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) CheckLowStockAlertsReturnsOnCall(i int, result1 []*models.InventoryAlert, result2 error) {
	fake.checkLowStockAlertsMutex.Lock()
	defer fake.checkLowStockAlertsMutex.Unlock()
	fake.CheckLowStockAlertsStub = nil
	if fake.checkLowStockAlertsReturnsOnCall == nil {
		fake.checkLowStockAlertsReturnsOnCall = make(map[int]struct {
			result1 []*models.InventoryAlert
			result2 error
		})
	}
	fake.checkLowStockAlertsReturnsOnCall[i] = struct {
		result1 []*models.InventoryAlert
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) CheckStock(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (int, error) {
	fake.checkStockMutex.Lock()
	ret, specificReturn := fake.checkStockReturnsOnCall[len(fake.checkStockArgsForCall)]
	fake.checkStockArgsForCall = append(fake.checkStockArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.CheckStockStub
	fakeReturns := fake.checkStockReturns
	fake.recordInvocation("CheckStock", []interface{}{arg1, arg2, arg3})
	fake.checkStockMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProductService) CheckStockCallCount() int {
	fake.checkStockMutex.RLock()
	defer fake.checkStockMutex.RUnlock()
	return len(fake.checkStockArgsForCall)
}

func (fake *FakeProductService) CheckStockCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (int, error)) {
	fake.checkStockMutex.Lock()
	defer fake.checkStockMutex.Unlock()
	fake.CheckStockStub = stub
}

func (fake *FakeProductService) CheckStockArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.checkStockMutex.RLock()
	defer fake.checkStockMutex.RUnlock()
	argsForCall := fake.checkStockArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProductService) CheckStockReturns(result1 int, result2 error) {
	fake.checkStockMutex.Lock()
	defer fake.checkStockMutex.Unlock()
	fake.CheckStockStub = nil
	fake.checkStockReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) CheckStockReturnsOnCall(i int, result1 int, result2 error) {
	fake.checkStockMutex.Lock()
	defer fake.checkStockMutex.Unlock()
	fake.CheckStockStub = nil
	if fake.checkStockReturnsOnCall == nil {
		fake.checkStockReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.checkStockReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) CreateProduct(arg1 context.Context, arg2 *services.CreateProductRequest) (*models.Product, error) {
	fake.createProductMutex.Lock()
	ret, specificReturn := fake.createProductReturnsOnCall[len(fake.createProductArgsForCall)]
	fake.createProductArgsForCall = append(fake.createProductArgsForCall, struct {
		arg1 context.Context
		arg2 *services.CreateProductRequest
	}{arg1, arg2})
	stub := fake.CreateProductStub
	fakeReturns := fake.createProductReturns
	fake.recordInvocation("CreateProduct", []interface{}{arg1, arg2})
	fake.createProductMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProductService) CreateProductCallCount() int {
	fake.createProductMutex.RLock()
	defer fake.createProductMutex.RUnlock()
	return len(fake.createProductArgsForCall)
}

func (fake *FakeProductService) CreateProductCalls(stub func(context.Context, *services.CreateProductRequest) (*models.Product, error)) {
	fake.createProductMutex.Lock()
	defer fake.createProductMutex.Unlock()
	fake.CreateProductStub = stub
}

func (fake *FakeProductService) CreateProductArgsForCall(i int) (context.Context, *services.CreateProductRequest) {
	fake.createProductMutex.RLock()
	defer fake.createProductMutex.RUnlock()
	argsForCall := fake.createProductArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeProductService) CreateProductReturns(result1 *models.Product, result2 error) {
	fake.createProductMutex.Lock()
	defer fake.createProductMutex.Unlock()
	fake.CreateProductStub = nil
	fake.createProductReturns = struct {
		result1 *models.Product
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) CreateProductReturnsOnCall(i int, result1 *models.Product, result2 error) {
	fake.createProductMutex.Lock()
	defer fake.createProductMutex.Unlock()
	fake.CreateProductStub = nil
	if fake.createProductReturnsOnCall == nil {
		fake.createProductReturnsOnCall = make(map[int]struct {
			result1 *models.Product
			result2 error
		})
	}
	fake.createProductReturnsOnCall[i] = struct {
		result1 *models.Product
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) CreateVariant(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 *services.CreateVariantRequest) (*models.ProductVariant, error) {
	fake.createVariantMutex.Lock()
	ret, specificReturn := fake.createVariantReturnsOnCall[len(fake.createVariantArgsForCall)]
	fake.createVariantArgsForCall = append(fake.createVariantArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 *services.CreateVariantRequest
	}{arg1, arg2, arg3, arg4})
	stub := fake.CreateVariantStub
	fakeReturns := fake.createVariantReturns
	fake.recordInvocation("CreateVariant", []interface{}{arg1, arg2, arg3, arg4})
	fake.createVariantMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProductService) CreateVariantCallCount() int {
	fake.createVariantMutex.RLock()
	defer fake.createVariantMutex.RUnlock()
	return len(fake.createVariantArgsForCall)
}

func (fake *FakeProductService) CreateVariantCalls(stub func(context.Context, uuid.UUID, uuid.UUID, *services.CreateVariantRequest) (*models.ProductVariant, error)) {
	fake.createVariantMutex.Lock()
	defer fake.createVariantMutex.Unlock()
	fake.CreateVariantStub = stub
}

func (fake *FakeProductService) CreateVariantArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, *services.CreateVariantRequest) {
	fake.createVariantMutex.RLock()
	defer fake.createVariantMutex.RUnlock()
	argsForCall := fake.createVariantArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeProductService) CreateVariantReturns(result1 *models.ProductVariant, result2 error) {
	fake.createVariantMutex.Lock()
	defer fake.createVariantMutex.Unlock()
	fake.CreateVariantStub = nil
	fake.createVariantReturns = struct {
		result1 *models.ProductVariant
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) CreateVariantReturnsOnCall(i int, result1 *models.ProductVariant, result2 error) {
	fake.createVariantMutex.Lock()
	defer fake.createVariantMutex.Unlock()
	fake.CreateVariantStub = nil
	if fake.createVariantReturnsOnCall == nil {
		fake.createVariantReturnsOnCall = make(map[int]struct {
			result1 *models.ProductVariant
			result2 error
		})
	}
	fake.createVariantReturnsOnCall[i] = struct {
		result1 *models.ProductVariant
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) DeleteProduct(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.deleteProductMutex.Lock()
	ret, specificReturn := fake.deleteProductReturnsOnCall[len(fake.deleteProductArgsForCall)]
	fake.deleteProductArgsForCall = append(fake.deleteProductArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.DeleteProductStub
	fakeReturns := fake.deleteProductReturns
	fake.recordInvocation("DeleteProduct", []interface{}{arg1, arg2, arg3})
	fake.deleteProductMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProductService) DeleteProductCallCount() int {
	fake.deleteProductMutex.RLock()
	defer fake.deleteProductMutex.RUnlock()
	return len(fake.deleteProductArgsForCall)
}

func (fake *FakeProductService) DeleteProductCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.deleteProductMutex.Lock()
	defer fake.deleteProductMutex.Unlock()
	fake.DeleteProductStub = stub
}

func (fake *FakeProductService) DeleteProductArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.deleteProductMutex.RLock()
	defer fake.deleteProductMutex.RUnlock()
	argsForCall := fake.deleteProductArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProductService) DeleteProductReturns(result1 error) {
	fake.deleteProductMutex.Lock()
	defer fake.deleteProductMutex.Unlock()
	fake.DeleteProductStub = nil
	fake.deleteProductReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductService) DeleteProductReturnsOnCall(i int, result1 error) {
	fake.deleteProductMutex.Lock()
	defer fake.deleteProductMutex.Unlock()
	fake.DeleteProductStub = nil
	if fake.deleteProductReturnsOnCall == nil {
		fake.deleteProductReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteProductReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductService) DeleteVariant(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.deleteVariantMutex.Lock()
	ret, specificReturn := fake.deleteVariantReturnsOnCall[len(fake.deleteVariantArgsForCall)]
	fake.deleteVariantArgsForCall = append(fake.deleteVariantArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.DeleteVariantStub
	fakeReturns := fake.deleteVariantReturns
	fake.recordInvocation("DeleteVariant", []interface{}{arg1, arg2, arg3})
	fake.deleteVariantMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProductService) DeleteVariantCallCount() int {
	fake.deleteVariantMutex.RLock()
	defer fake.deleteVariantMutex.RUnlock()
	return len(fake.deleteVariantArgsForCall)
}

func (fake *FakeProductService) DeleteVariantCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.deleteVariantMutex.Lock()
	defer fake.deleteVariantMutex.Unlock()
	fake.DeleteVariantStub = stub
}

func (fake *FakeProductService) DeleteVariantArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.deleteVariantMutex.RLock()
	defer fake.deleteVariantMutex.RUnlock()
	argsForCall := fake.deleteVariantArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProductService) DeleteVariantReturns(result1 error) {
	fake.deleteVariantMutex.Lock()
	defer fake.deleteVariantMutex.Unlock()
	fake.DeleteVariantStub = nil
	fake.deleteVariantReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductService) DeleteVariantReturnsOnCall(i int, result1 error) {
	fake.deleteVariantMutex.Lock()
	defer fake.deleteVariantMutex.Unlock()
	fake.DeleteVariantStub = nil
	if fake.deleteVariantReturnsOnCall == nil {
		fake.deleteVariantReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteVariantReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductService) GetInventoryAlert(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 uuid.UUID) (*models.InventoryAlert, error) {
	fake.getInventoryAlertMutex.Lock()
	ret, specificReturn := fake.getInventoryAlertReturnsOnCall[len(fake.getInventoryAlertArgsForCall)]
	fake.getInventoryAlertArgsForCall = append(fake.getInventoryAlertArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 uuid.UUID
	}{arg1, arg2, arg3, arg4})
	stub := fake.GetInventoryAlertStub
	fakeReturns := fake.getInventoryAlertReturns
	fake.recordInvocation("GetInventoryAlert", []interface{}{arg1, arg2, arg3, arg4})
	fake.getInventoryAlertMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProductService) GetInventoryAlertCallCount() int {
	fake.getInventoryAlertMutex.RLock()
	defer fake.getInventoryAlertMutex.RUnlock()
	return len(fake.getInventoryAlertArgsForCall)
}

func (fake *FakeProductService) GetInventoryAlertCalls(stub func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (*models.InventoryAlert, error)) {
	fake.getInventoryAlertMutex.Lock()
	defer fake.getInventoryAlertMutex.Unlock()
	fake.GetInventoryAlertStub = stub
}

func (fake *FakeProductService) GetInventoryAlertArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, uuid.UUID) {
	fake.getInventoryAlertMutex.RLock()
	defer fake.getInventoryAlertMutex.RUnlock()
	argsForCall := fake.getInventoryAlertArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeProductService) GetInventoryAlertReturns(result1 *models.InventoryAlert, result2 error) {
	fake.getInventoryAlertMutex.Lock()
	defer fake.getInventoryAlertMutex.Unlock()
	fake.GetInventoryAlertStub = nil
	fake.getInventoryAlertReturns = struct {
		result1 *models.InventoryAlert
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) GetInventoryAlertReturnsOnCall(i int, result1 *models.InventoryAlert, result2 error) {
	fake.getInventoryAlertMutex.Lock()
	defer fake.getInventoryAlertMutex.Unlock()
	fake.GetInventoryAlertStub = nil
	if fake.getInventoryAlertReturnsOnCall == nil {
		fake.getInventoryAlertReturnsOnCall = make(map[int]struct {
			result1 *models.InventoryAlert
			result2 error
		})
	}
	fake.getInventoryAlertReturnsOnCall[i] = struct {
		result1 *models.InventoryAlert
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) GetMovementHistory(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 int, arg5 int) ([]*models.InventoryMovement, int, error) {
	fake.getMovementHistoryMutex.Lock()
	ret, specificReturn := fake.getMovementHistoryReturnsOnCall[len(fake.getMovementHistoryArgsForCall)]
	fake.getMovementHistoryArgsForCall = append(fake.getMovementHistoryArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.GetMovementHistoryStub
	fakeReturns := fake.getMovementHistoryReturns
	fake.recordInvocation("GetMovementHistory", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.getMovementHistoryMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeProductService) GetMovementHistoryCallCount() int {
	fake.getMovementHistoryMutex.RLock()
	defer fake.getMovementHistoryMutex.RUnlock()
	return len(fake.getMovementHistoryArgsForCall)
}

func (fake *FakeProductService) GetMovementHistoryCalls(stub func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]*models.InventoryMovement, int, error)) {
	fake.getMovementHistoryMutex.Lock()
	defer fake.getMovementHistoryMutex.Unlock()
	fake.GetMovementHistoryStub = stub
}

func (fake *FakeProductService) GetMovementHistoryArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, int, int) {
	fake.getMovementHistoryMutex.RLock()
	defer fake.getMovementHistoryMutex.RUnlock()
	argsForCall := fake.getMovementHistoryArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeProductService) GetMovementHistoryReturns(result1 []*models.InventoryMovement, result2 int, result3 error) {
	fake.getMovementHistoryMutex.Lock()
	defer fake.getMovementHistoryMutex.Unlock()
	fake.GetMovementHistoryStub = nil
	fake.getMovementHistoryReturns = struct {
		result1 []*models.InventoryMovement
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeProductService) GetMovementHistoryReturnsOnCall(i int, result1 []*models.InventoryMovement, result2 int, result3 error) {
	fake.getMovementHistoryMutex.Lock()
	defer fake.getMovementHistoryMutex.Unlock()
	fake.GetMovementHistoryStub = nil
	if fake.getMovementHistoryReturnsOnCall == nil {
		fake.getMovementHistoryReturnsOnCall = make(map[int]struct {
			result1 []*models.InventoryMovement
			result2 int
			result3 error
		})
	}
	fake.getMovementHistoryReturnsOnCall[i] = struct {
		result1 []*models.InventoryMovement
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeProductService) GetProduct(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (*models.Product, error) {
	fake.getProductMutex.Lock()
	ret, specificReturn := fake.getProductReturnsOnCall[len(fake.getProductArgsForCall)]
	fake.getProductArgsForCall = append(fake.getProductArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.GetProductStub
	fakeReturns := fake.getProductReturns
	fake.recordInvocation("GetProduct", []interface{}{arg1, arg2, arg3})
	fake.getProductMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProductService) GetProductCallCount() int {
	fake.getProductMutex.RLock()
	defer fake.getProductMutex.RUnlock()
	return len(fake.getProductArgsForCall)
}

func (fake *FakeProductService) GetProductCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (*models.Product, error)) {
	fake.getProductMutex.Lock()
	defer fake.getProductMutex.Unlock()
	fake.GetProductStub = stub
}

func (fake *FakeProductService) GetProductArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.getProductMutex.RLock()
	defer fake.getProductMutex.RUnlock()
	argsForCall := fake.getProductArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProductService) GetProductReturns(result1 *models.Product, result2 error) {
	fake.getProductMutex.Lock()
	defer fake.getProductMutex.Unlock()
	fake.GetProductStub = nil
	fake.getProductReturns = struct {
		result1 *models.Product
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) GetProductReturnsOnCall(i int, result1 *models.Product, result2 error) {
	fake.getProductMutex.Lock()
	defer fake.getProductMutex.Unlock()
	fake.GetProductStub = nil
	if fake.getProductReturnsOnCall == nil {
		fake.getProductReturnsOnCall = make(map[int]struct {
			result1 *models.Product
			result2 error
		})
	}
	fake.getProductReturnsOnCall[i] = struct {
		result1 *models.Product
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) GetVariant(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (*models.ProductVariant, error) {
	fake.getVariantMutex.Lock()
	ret, specificReturn := fake.getVariantReturnsOnCall[len(fake.getVariantArgsForCall)]
	fake.getVariantArgsForCall = append(fake.getVariantArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.GetVariantStub
	fakeReturns := fake.getVariantReturns
	fake.recordInvocation("GetVariant", []interface{}{arg1, arg2, arg3})
	fake.getVariantMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProductService) GetVariantCallCount() int {
	fake.getVariantMutex.RLock()
	defer fake.getVariantMutex.RUnlock()
	return len(fake.getVariantArgsForCall)
}

func (fake *FakeProductService) GetVariantCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (*models.ProductVariant, error)) {
	fake.getVariantMutex.Lock()
	defer fake.getVariantMutex.Unlock()
	fake.GetVariantStub = stub
}

func (fake *FakeProductService) GetVariantArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.getVariantMutex.RLock()
	defer fake.getVariantMutex.RUnlock()
	argsForCall := fake.getVariantArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProductService) GetVariantReturns(result1 *models.ProductVariant, result2 error) {
	fake.getVariantMutex.Lock()
	defer fake.getVariantMutex.Unlock()
	fake.GetVariantStub = nil
	fake.getVariantReturns = struct {
		result1 *models.ProductVariant
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) GetVariantReturnsOnCall(i int, result1 *models.ProductVariant, result2 error) {
	fake.getVariantMutex.Lock()
	defer fake.getVariantMutex.Unlock()
	fake.GetVariantStub = nil
	if fake.getVariantReturnsOnCall == nil {
		fake.getVariantReturnsOnCall = make(map[int]struct {
			result1 *models.ProductVariant
			result2 error
		})
	}
	fake.getVariantReturnsOnCall[i] = struct {
		result1 *models.ProductVariant
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) ListProducts(arg1 context.Context, arg2 uuid.UUID, arg3 *uuid.UUID, arg4 int, arg5 int) ([]*models.Product, int, error) {
	fake.listProductsMutex.Lock()
	ret, specificReturn := fake.listProductsReturnsOnCall[len(fake.listProductsArgsForCall)]
	fake.listProductsArgsForCall = append(fake.listProductsArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 *uuid.UUID
		arg4 int
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ListProductsStub
	fakeReturns := fake.listProductsReturns
	fake.recordInvocation("ListProducts", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.listProductsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeProductService) ListProductsCallCount() int {
	fake.listProductsMutex.RLock()
	defer fake.listProductsMutex.RUnlock()
	return len(fake.listProductsArgsForCall)
}

func (fake *FakeProductService) ListProductsCalls(stub func(context.Context, uuid.UUID, *uuid.UUID, int, int) ([]*models.Product, int, error)) {
	fake.listProductsMutex.Lock()
	defer fake.listProductsMutex.Unlock()
	fake.ListProductsStub = stub
}

func (fake *FakeProductService) ListProductsArgsForCall(i int) (context.Context, uuid.UUID, *uuid.UUID, int, int) {
	fake.listProductsMutex.RLock()
	defer fake.listProductsMutex.RUnlock()
	argsForCall := fake.listProductsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeProductService) ListProductsReturns(result1 []*models.Product, result2 int, result3 error) {
	fake.listProductsMutex.Lock()
	defer fake.listProductsMutex.Unlock()
	fake.ListProductsStub = nil
	fake.listProductsReturns = struct {
		result1 []*models.Product
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeProductService) ListProductsReturnsOnCall(i int, result1 []*models.Product, result2 int, result3 error) {
	fake.listProductsMutex.Lock()
	defer fake.listProductsMutex.Unlock()
	fake.ListProductsStub = nil
	if fake.listProductsReturnsOnCall == nil {
		fake.listProductsReturnsOnCall = make(map[int]struct {
			result1 []*models.Product
			result2 int
			result3 error
		})
	}
	fake.listProductsReturnsOnCall[i] = struct {
		result1 []*models.Product
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeProductService) ListVariants(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) ([]*models.ProductVariant, error) {
	fake.listVariantsMutex.Lock()
	ret, specificReturn := fake.listVariantsReturnsOnCall[len(fake.listVariantsArgsForCall)]
	fake.listVariantsArgsForCall = append(fake.listVariantsArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.ListVariantsStub
	fakeReturns := fake.listVariantsReturns
	fake.recordInvocation("ListVariants", []interface{}{arg1, arg2, arg3})
	fake.listVariantsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProductService) ListVariantsCallCount() int {
	fake.listVariantsMutex.RLock()
	defer fake.listVariantsMutex.RUnlock()
	return len(fake.listVariantsArgsForCall)
}

func (fake *FakeProductService) ListVariantsCalls(stub func(context.Context, uuid.UUID, uuid.UUID) ([]*models.ProductVariant, error)) {
	fake.listVariantsMutex.Lock()
	defer fake.listVariantsMutex.Unlock()
	fake.ListVariantsStub = stub
}

func (fake *FakeProductService) ListVariantsArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.listVariantsMutex.RLock()
	defer fake.listVariantsMutex.RUnlock()
	argsForCall := fake.listVariantsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProductService) ListVariantsReturns(result1 []*models.ProductVariant, result2 error) {
	fake.listVariantsMutex.Lock()
	defer fake.listVariantsMutex.Unlock()
	fake.ListVariantsStub = nil
	fake.listVariantsReturns = struct {
		result1 []*models.ProductVariant
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) ListVariantsReturnsOnCall(i int, result1 []*models.ProductVariant, result2 error) {
	fake.listVariantsMutex.Lock()
	defer fake.listVariantsMutex.Unlock()
	fake.ListVariantsStub = nil
	if fake.listVariantsReturnsOnCall == nil {
		fake.listVariantsReturnsOnCall = make(map[int]struct {
			result1 []*models.ProductVariant
			result2 error
		})
	}
	fake.listVariantsReturnsOnCall[i] = struct {
		result1 []*models.ProductVariant
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) RecordMovement(arg1 context.Context, arg2 *services.RecordMovementRequest) (*models.InventoryMovement, error) {
	fake.recordMovementMutex.Lock()
	ret, specificReturn := fake.recordMovementReturnsOnCall[len(fake.recordMovementArgsForCall)]
	fake.recordMovementArgsForCall = append(fake.recordMovementArgsForCall, struct {
		arg1 context.Context
		arg2 *services.RecordMovementRequest
	}{arg1, arg2})
	stub := fake.RecordMovementStub
	fakeReturns := fake.recordMovementReturns
	fake.recordInvocation("RecordMovement", []interface{}{arg1, arg2})
	fake.recordMovementMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProductService) RecordMovementCallCount() int {
	fake.recordMovementMutex.RLock()
	defer fake.recordMovementMutex.RUnlock()
	return len(fake.recordMovementArgsForCall)
}

func (fake *FakeProductService) RecordMovementCalls(stub func(context.Context, *services.RecordMovementRequest) (*models.InventoryMovement, error)) {
	fake.recordMovementMutex.Lock()
	defer fake.recordMovementMutex.Unlock()
	fake.RecordMovementStub = stub
}

func (fake *FakeProductService) RecordMovementArgsForCall(i int) (context.Context, *services.RecordMovementRequest) {
	fake.recordMovementMutex.RLock()
	defer fake.recordMovementMutex.RUnlock()
	argsForCall := fake.recordMovementArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeProductService) RecordMovementReturns(result1 *models.InventoryMovement, result2 error) {
	fake.recordMovementMutex.Lock()
	defer fake.recordMovementMutex.Unlock()
	fake.RecordMovementStub = nil
	fake.recordMovementReturns = struct {
		result1 *models.InventoryMovement
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) RecordMovementReturnsOnCall(i int, result1 *models.InventoryMovement, result2 error) {
	fake.recordMovementMutex.Lock()
	defer fake.recordMovementMutex.Unlock()
	fake.RecordMovementStub = nil
	if fake.recordMovementReturnsOnCall == nil {
		fake.recordMovementReturnsOnCall = make(map[int]struct {
			result1 *models.InventoryMovement
			result2 error
		})
	}
	fake.recordMovementReturnsOnCall[i] = struct {
		result1 *models.InventoryMovement
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) SearchProducts(arg1 context.Context, arg2 uuid.UUID, arg3 string, arg4 int, arg5 int) ([]*models.Product, int, error) {
	fake.searchProductsMutex.Lock()
	ret, specificReturn := fake.searchProductsReturnsOnCall[len(fake.searchProductsArgsForCall)]
	fake.searchProductsArgsForCall = append(fake.searchProductsArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
		arg4 int
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.SearchProductsStub
	fakeReturns := fake.searchProductsReturns
	fake.recordInvocation("SearchProducts", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.searchProductsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeProductService) SearchProductsCallCount() int {
	fake.searchProductsMutex.RLock()
	defer fake.searchProductsMutex.RUnlock()
	return len(fake.searchProductsArgsForCall)
}

func (fake *FakeProductService) SearchProductsCalls(stub func(context.Context, uuid.UUID, string, int, int) ([]*models.Product, int, error)) {
	fake.searchProductsMutex.Lock()
	defer fake.searchProductsMutex.Unlock()
	fake.SearchProductsStub = stub
}

func (fake *FakeProductService) SearchProductsArgsForCall(i int) (context.Context, uuid.UUID, string, int, int) {
	fake.searchProductsMutex.RLock()
	defer fake.searchProductsMutex.RUnlock()
	argsForCall := fake.searchProductsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeProductService) SearchProductsReturns(result1 []*models.Product, result2 int, result3 error) {
	fake.searchProductsMutex.Lock()
	defer fake.searchProductsMutex.Unlock()
	fake.SearchProductsStub = nil
	fake.searchProductsReturns = struct {
		result1 []*models.Product
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeProductService) SearchProductsReturnsOnCall(i int, result1 []*models.Product, result2 int, result3 error) {
	fake.searchProductsMutex.Lock()
	defer fake.searchProductsMutex.Unlock()
	fake.SearchProductsStub = nil
	if fake.searchProductsReturnsOnCall == nil {
		fake.searchProductsReturnsOnCall = make(map[int]struct {
			result1 []*models.Product
			result2 int
			result3 error
		})
	}
	fake.searchProductsReturnsOnCall[i] = struct {
		result1 []*models.Product
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeProductService) SetInventory(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 int) error {
	fake.setInventoryMutex.Lock()
	ret, specificReturn := fake.setInventoryReturnsOnCall[len(fake.setInventoryArgsForCall)]
	fake.setInventoryArgsForCall = append(fake.setInventoryArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.SetInventoryStub
	fakeReturns := fake.setInventoryReturns
	fake.recordInvocation("SetInventory", []interface{}{arg1, arg2, arg3, arg4})
	fake.setInventoryMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProductService) SetInventoryCallCount() int {
	fake.setInventoryMutex.RLock()
	defer fake.setInventoryMutex.RUnlock()
	return len(fake.setInventoryArgsForCall)
}

func (fake *FakeProductService) SetInventoryCalls(stub func(context.Context, uuid.UUID, uuid.UUID, int) error) {
	fake.setInventoryMutex.Lock()
	defer fake.setInventoryMutex.Unlock()
	fake.SetInventoryStub = stub
}

func (fake *FakeProductService) SetInventoryArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, int) {
	fake.setInventoryMutex.RLock()
	defer fake.setInventoryMutex.RUnlock()
	argsForCall := fake.setInventoryArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeProductService) SetInventoryReturns(result1 error) {
	fake.setInventoryMutex.Lock()
	defer fake.setInventoryMutex.Unlock()
	fake.SetInventoryStub = nil
	fake.setInventoryReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductService) SetInventoryReturnsOnCall(i int, result1 error) {
	fake.setInventoryMutex.Lock()
	defer fake.setInventoryMutex.Unlock()
	fake.SetInventoryStub = nil
	if fake.setInventoryReturnsOnCall == nil {
		fake.setInventoryReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setInventoryReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductService) SetInventoryAlert(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 uuid.UUID, arg5 *services.SetInventoryAlertRequest) (*models.InventoryAlert, error) {
	fake.setInventoryAlertMutex.Lock()
	ret, specificReturn := fake.setInventoryAlertReturnsOnCall[len(fake.setInventoryAlertArgsForCall)]
	fake.setInventoryAlertArgsForCall = append(fake.setInventoryAlertArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 uuid.UUID
		arg5 *services.SetInventoryAlertRequest
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.SetInventoryAlertStub
	fakeReturns := fake.setInventoryAlertReturns
	fake.recordInvocation("SetInventoryAlert", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.setInventoryAlertMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProductService) SetInventoryAlertCallCount() int {
	fake.setInventoryAlertMutex.RLock()
	defer fake.setInventoryAlertMutex.RUnlock()
	return len(fake.setInventoryAlertArgsForCall)
}

func (fake *FakeProductService) SetInventoryAlertCalls(stub func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, *services.SetInventoryAlertRequest) (*models.InventoryAlert, error)) {
	fake.setInventoryAlertMutex.Lock()
	defer fake.setInventoryAlertMutex.Unlock()
	fake.SetInventoryAlertStub = stub
}

func (fake *FakeProductService) SetInventoryAlertArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, uuid.UUID, *services.SetInventoryAlertRequest) {
	fake.setInventoryAlertMutex.RLock()
	defer fake.setInventoryAlertMutex.RUnlock()
	argsForCall := fake.setInventoryAlertArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeProductService) SetInventoryAlertReturns(result1 *models.InventoryAlert, result2 error) {
	fake.setInventoryAlertMutex.Lock()
	defer fake.setInventoryAlertMutex.Unlock()
	fake.SetInventoryAlertStub = nil
	fake.setInventoryAlertReturns = struct {
		result1 *models.InventoryAlert
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) SetInventoryAlertReturnsOnCall(i int, result1 *models.InventoryAlert, result2 error) {
	fake.setInventoryAlertMutex.Lock()
	defer fake.setInventoryAlertMutex.Unlock()
	fake.SetInventoryAlertStub = nil
	if fake.setInventoryAlertReturnsOnCall == nil {
		fake.setInventoryAlertReturnsOnCall = make(map[int]struct {
			result1 *models.InventoryAlert
			result2 error
		})
	}
	fake.setInventoryAlertReturnsOnCall[i] = struct {
		result1 *models.InventoryAlert
		result2 error
	}{result1, result2}
}

func (fake *FakeProductService) UpdateProduct(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 *services.UpdateProductRequest) error {
	fake.updateProductMutex.Lock()
	ret, specificReturn := fake.updateProductReturnsOnCall[len(fake.updateProductArgsForCall)]
	fake.updateProductArgsForCall = append(fake.updateProductArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 *services.UpdateProductRequest
	}{arg1, arg2, arg3, arg4})
	stub := fake.UpdateProductStub
	fakeReturns := fake.updateProductReturns
	fake.recordInvocation("UpdateProduct", []interface{}{arg1, arg2, arg3, arg4})
	fake.updateProductMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProductService) UpdateProductCallCount() int {
	fake.updateProductMutex.RLock()
	defer fake.updateProductMutex.RUnlock()
	return len(fake.updateProductArgsForCall)
}

func (fake *FakeProductService) UpdateProductCalls(stub func(context.Context, uuid.UUID, uuid.UUID, *services.UpdateProductRequest) error) {
	fake.updateProductMutex.Lock()
	defer fake.updateProductMutex.Unlock()
	fake.UpdateProductStub = stub
}

func (fake *FakeProductService) UpdateProductArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, *services.UpdateProductRequest) {
	fake.updateProductMutex.RLock()
	defer fake.updateProductMutex.RUnlock()
	argsForCall := fake.updateProductArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeProductService) UpdateProductReturns(result1 error) {
	fake.updateProductMutex.Lock()
	defer fake.updateProductMutex.Unlock()
	fake.UpdateProductStub = nil
	fake.updateProductReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductService) UpdateProductReturnsOnCall(i int, result1 error) {
	fake.updateProductMutex.Lock()
	defer fake.updateProductMutex.Unlock()
	fake.UpdateProductStub = nil
	if fake.updateProductReturnsOnCall == nil {
		fake.updateProductReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateProductReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductService) UpdateVariant(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 *services.UpdateVariantRequest) error {
	fake.updateVariantMutex.Lock()
	ret, specificReturn := fake.updateVariantReturnsOnCall[len(fake.updateVariantArgsForCall)]
	fake.updateVariantArgsForCall = append(fake.updateVariantArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 *services.UpdateVariantRequest
	}{arg1, arg2, arg3, arg4})
	stub := fake.UpdateVariantStub
	fakeReturns := fake.updateVariantReturns
	fake.recordInvocation("UpdateVariant", []interface{}{arg1, arg2, arg3, arg4})
	fake.updateVariantMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProductService) UpdateVariantCallCount() int {
	fake.updateVariantMutex.RLock()
	defer fake.updateVariantMutex.RUnlock()
	return len(fake.updateVariantArgsForCall)
}

func (fake *FakeProductService) UpdateVariantCalls(stub func(context.Context, uuid.UUID, uuid.UUID, *services.UpdateVariantRequest) error) {
	fake.updateVariantMutex.Lock()
	defer fake.updateVariantMutex.Unlock()
	fake.UpdateVariantStub = stub
}

func (fake *FakeProductService) UpdateVariantArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, *services.UpdateVariantRequest) {
	fake.updateVariantMutex.RLock()
	defer fake.updateVariantMutex.RUnlock()
	argsForCall := fake.updateVariantArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeProductService) UpdateVariantReturns(result1 error) {
	fake.updateVariantMutex.Lock()
	defer fake.updateVariantMutex.Unlock()
	fake.UpdateVariantStub = nil
	fake.updateVariantReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductService) UpdateVariantReturnsOnCall(i int, result1 error) {
	fake.updateVariantMutex.Lock()
	defer fake.updateVariantMutex.Unlock()
	fake.UpdateVariantStub = nil
	if fake.updateVariantReturnsOnCall == nil {
		fake.updateVariantReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateVariantReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProductService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ services.ProductService = new(FakeProductService)
