// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/yourorg/shoppilot/internal/models"
	"github.com/yourorg/shoppilot/internal/services"
)

type FakePurchaseOrderService struct {
	AddItemStub        func(context.Context, uuid.UUID, uuid.UUID, *services.AddPurchaseOrderItemRequest) (*models.PurchaseOrderItem, error)
	addItemMutex       sync.RWMutex
	addItemArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 *services.AddPurchaseOrderItemRequest
	}
	addItemReturns struct {
		result1 *models.PurchaseOrderItem
		result2 error
	}
	addItemReturnsOnCall map[int]struct {
		result1 *models.PurchaseOrderItem
		result2 error
	}
	CancelPurchaseOrderStub        func(context.Context, uuid.UUID, uuid.UUID) error
	cancelPurchaseOrderMutex       sync.RWMutex
	cancelPurchaseOrderArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	cancelPurchaseOrderReturns struct {
		result1 error
	}
	cancelPurchaseOrderReturnsOnCall map[int]struct {
		result1 error
	}
	CreatePurchaseOrderStub        func(context.Context, uuid.UUID, *services.CreatePurchaseOrderRequest) (*models.PurchaseOrder, error)
	createPurchaseOrderMutex       sync.RWMutex
	createPurchaseOrderArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 *services.CreatePurchaseOrderRequest
	}
	createPurchaseOrderReturns struct {
		result1 *models.PurchaseOrder
		result2 error
	}
	createPurchaseOrderReturnsOnCall map[int]struct {
		result1 *models.PurchaseOrder
		result2 error
	}
	DeletePurchaseOrderStub        func(context.Context, uuid.UUID, uuid.UUID) error
	deletePurchaseOrderMutex       sync.RWMutex
	deletePurchaseOrderArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	deletePurchaseOrderReturns struct {
		result1 error
	}
	deletePurchaseOrderReturnsOnCall map[int]struct {
		result1 error
	}
	GetPurchaseOrderStub        func(context.Context, uuid.UUID, uuid.UUID) (*models.PurchaseOrder, error)
	getPurchaseOrderMutex       sync.RWMutex
	getPurchaseOrderArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	getPurchaseOrderReturns struct {
		result1 *models.PurchaseOrder
		result2 error
	}
	getPurchaseOrderReturnsOnCall map[int]struct {
		result1 *models.PurchaseOrder
		result2 error
	}
	ListItemsStub        func(context.Context, uuid.UUID, uuid.UUID) ([]*models.PurchaseOrderItem, error)
	listItemsMutex       sync.RWMutex
	listItemsArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	listItemsReturns struct {
		result1 []*models.PurchaseOrderItem
		result2 error
	}
	listItemsReturnsOnCall map[int]struct {
		result1 []*models.PurchaseOrderItem
		result2 error
	}
	ListPurchaseOrdersStub        func(context.Context, uuid.UUID, *services.PurchaseOrderFilters, int, int) ([]*models.PurchaseOrder, int, error)
	listPurchaseOrdersMutex       sync.RWMutex
	listPurchaseOrdersArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 *services.PurchaseOrderFilters
		arg4 int
		arg5 int
	}
	listPurchaseOrdersReturns struct {
		result1 []*models.PurchaseOrder
		result2 int
		result3 error
	}
	listPurchaseOrdersReturnsOnCall map[int]struct {
		result1 []*models.PurchaseOrder
		result2 int
		result3 error
	}
	ReceiveItemsStub        func(context.Context, uuid.UUID, uuid.UUID, []services.ReceiveItemRequest) error
	receiveItemsMutex       sync.RWMutex
	receiveItemsArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 []services.ReceiveItemRequest
	}
	receiveItemsReturns struct {
		result1 error
	}
	receiveItemsReturnsOnCall map[int]struct {
		result1 error
	}
	RemoveItemStub        func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error
	removeItemMutex       sync.RWMutex
	removeItemArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 uuid.UUID
	}
	removeItemReturns struct {
		result1 error
	}
	removeItemReturnsOnCall map[int]struct {
		result1 error
	}
	SubmitPurchaseOrderStub        func(context.Context, uuid.UUID, uuid.UUID) error
	submitPurchaseOrderMutex       sync.RWMutex
	submitPurchaseOrderArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	submitPurchaseOrderReturns struct {
		result1 error
	}
	submitPurchaseOrderReturnsOnCall map[int]struct {
		result1 error
	}
	UpdatePurchaseOrderStub        func(context.Context, uuid.UUID, uuid.UUID, *services.UpdatePurchaseOrderRequest) error
	updatePurchaseOrderMutex       sync.RWMutex
	updatePurchaseOrderArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 *services.UpdatePurchaseOrderRequest
	}
	updatePurchaseOrderReturns struct {
		result1 error
	}
	updatePurchaseOrderReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePurchaseOrderService) AddItem(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 *services.AddPurchaseOrderItemRequest) (*models.PurchaseOrderItem, error) {
	fake.addItemMutex.Lock()
	ret, specificReturn := fake.addItemReturnsOnCall[len(fake.addItemArgsForCall)]
	fake.addItemArgsForCall = append(fake.addItemArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 *services.AddPurchaseOrderItemRequest
	}{arg1, arg2, arg3, arg4})
	stub := fake.AddItemStub
	fakeReturns := fake.addItemReturns
	fake.recordInvocation("AddItem", []interface{}{arg1, arg2, arg3, arg4})
	fake.addItemMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePurchaseOrderService) AddItemCallCount() int {
	fake.addItemMutex.RLock()
	defer fake.addItemMutex.RUnlock()
	return len(fake.addItemArgsForCall)
}

func (fake *FakePurchaseOrderService) AddItemCalls(stub func(context.Context, uuid.UUID, uuid.UUID, *services.AddPurchaseOrderItemRequest) (*models.PurchaseOrderItem, error)) {
	fake.addItemMutex.Lock()
	defer fake.addItemMutex.Unlock()
	fake.AddItemStub = stub
}

func (fake *FakePurchaseOrderService) AddItemArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, *services.AddPurchaseOrderItemRequest) {
	fake.addItemMutex.RLock()
	defer fake.addItemMutex.RUnlock()
	argsForCall := fake.addItemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakePurchaseOrderService) AddItemReturns(result1 *models.PurchaseOrderItem, result2 error) {
	fake.addItemMutex.Lock()
	defer fake.addItemMutex.Unlock()
	fake.AddItemStub = nil
	fake.addItemReturns = struct {
		result1 *models.PurchaseOrderItem
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderService) AddItemReturnsOnCall(i int, result1 *models.PurchaseOrderItem, result2 error) {
	fake.addItemMutex.Lock()
	defer fake.addItemMutex.Unlock()
	fake.AddItemStub = nil
	if fake.addItemReturnsOnCall == nil {
		fake.addItemReturnsOnCall = make(map[int]struct {
			result1 *models.PurchaseOrderItem
			result2 error
		})
	}
	fake.addItemReturnsOnCall[i] = struct {
		result1 *models.PurchaseOrderItem
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderService) CancelPurchaseOrder(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.cancelPurchaseOrderMutex.Lock()
	ret, specificReturn := fake.cancelPurchaseOrderReturnsOnCall[len(fake.cancelPurchaseOrderArgsForCall)]
	fake.cancelPurchaseOrderArgsForCall = append(fake.cancelPurchaseOrderArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.CancelPurchaseOrderStub
	fakeReturns := fake.cancelPurchaseOrderReturns
	fake.recordInvocation("CancelPurchaseOrder", []interface{}{arg1, arg2, arg3})
	fake.cancelPurchaseOrderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePurchaseOrderService) CancelPurchaseOrderCallCount() int {
	fake.cancelPurchaseOrderMutex.RLock()
	defer fake.cancelPurchaseOrderMutex.RUnlock()
	return len(fake.cancelPurchaseOrderArgsForCall)
}

func (fake *FakePurchaseOrderService) CancelPurchaseOrderCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.cancelPurchaseOrderMutex.Lock()
	defer fake.cancelPurchaseOrderMutex.Unlock()
	fake.CancelPurchaseOrderStub = stub
}

func (fake *FakePurchaseOrderService) CancelPurchaseOrderArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.cancelPurchaseOrderMutex.RLock()
	defer fake.cancelPurchaseOrderMutex.RUnlock()
	argsForCall := fake.cancelPurchaseOrderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePurchaseOrderService) CancelPurchaseOrderReturns(result1 error) {
	fake.cancelPurchaseOrderMutex.Lock()
	defer fake.cancelPurchaseOrderMutex.Unlock()
	fake.CancelPurchaseOrderStub = nil
	fake.cancelPurchaseOrderReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderService) CancelPurchaseOrderReturnsOnCall(i int, result1 error) {
	fake.cancelPurchaseOrderMutex.Lock()
	defer fake.cancelPurchaseOrderMutex.Unlock()
	fake.CancelPurchaseOrderStub = nil
	if fake.cancelPurchaseOrderReturnsOnCall == nil {
		fake.cancelPurchaseOrderReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.cancelPurchaseOrderReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderService) CreatePurchaseOrder(arg1 context.Context, arg2 uuid.UUID, arg3 *services.CreatePurchaseOrderRequest) (*models.PurchaseOrder, error) {
	fake.createPurchaseOrderMutex.Lock()
	ret, specificReturn := fake.createPurchaseOrderReturnsOnCall[len(fake.createPurchaseOrderArgsForCall)]
	fake.createPurchaseOrderArgsForCall = append(fake.createPurchaseOrderArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 *services.CreatePurchaseOrderRequest
	}{arg1, arg2, arg3})
	stub := fake.CreatePurchaseOrderStub
	fakeReturns := fake.createPurchaseOrderReturns
	fake.recordInvocation("CreatePurchaseOrder", []interface{}{arg1, arg2, arg3})
	fake.createPurchaseOrderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePurchaseOrderService) CreatePurchaseOrderCallCount() int {
	fake.createPurchaseOrderMutex.RLock()
	defer fake.createPurchaseOrderMutex.RUnlock()
	return len(fake.createPurchaseOrderArgsForCall)
}

func (fake *FakePurchaseOrderService) CreatePurchaseOrderCalls(stub func(context.Context, uuid.UUID, *services.CreatePurchaseOrderRequest) (*models.PurchaseOrder, error)) {
	fake.createPurchaseOrderMutex.Lock()
	defer fake.createPurchaseOrderMutex.Unlock()
	fake.CreatePurchaseOrderStub = stub
}

func (fake *FakePurchaseOrderService) CreatePurchaseOrderArgsForCall(i int) (context.Context, uuid.UUID, *services.CreatePurchaseOrderRequest) {
	fake.createPurchaseOrderMutex.RLock()
	defer fake.createPurchaseOrderMutex.RUnlock()
	argsForCall := fake.createPurchaseOrderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePurchaseOrderService) CreatePurchaseOrderReturns(result1 *models.PurchaseOrder, result2 error) {
	fake.createPurchaseOrderMutex.Lock()
	defer fake.createPurchaseOrderMutex.Unlock()
	fake.CreatePurchaseOrderStub = nil
	fake.createPurchaseOrderReturns = struct {
		result1 *models.PurchaseOrder
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderService) CreatePurchaseOrderReturnsOnCall(i int, result1 *models.PurchaseOrder, result2 error) {
	fake.createPurchaseOrderMutex.Lock()
	defer fake.createPurchaseOrderMutex.Unlock()
	fake.CreatePurchaseOrderStub = nil
	if fake.createPurchaseOrderReturnsOnCall == nil {
		fake.createPurchaseOrderReturnsOnCall = make(map[int]struct {
			result1 *models.PurchaseOrder
			result2 error
		})
	}
	fake.createPurchaseOrderReturnsOnCall[i] = struct {
		result1 *models.PurchaseOrder
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderService) DeletePurchaseOrder(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.deletePurchaseOrderMutex.Lock()
	ret, specificReturn := fake.deletePurchaseOrderReturnsOnCall[len(fake.deletePurchaseOrderArgsForCall)]
	fake.deletePurchaseOrderArgsForCall = append(fake.deletePurchaseOrderArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.DeletePurchaseOrderStub
	fakeReturns := fake.deletePurchaseOrderReturns
	fake.recordInvocation("DeletePurchaseOrder", []interface{}{arg1, arg2, arg3})
	fake.deletePurchaseOrderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePurchaseOrderService) DeletePurchaseOrderCallCount() int {
	fake.deletePurchaseOrderMutex.RLock()
	defer fake.deletePurchaseOrderMutex.RUnlock()
	return len(fake.deletePurchaseOrderArgsForCall)
}

func (fake *FakePurchaseOrderService) DeletePurchaseOrderCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.deletePurchaseOrderMutex.Lock()
	defer fake.deletePurchaseOrderMutex.Unlock()
	fake.DeletePurchaseOrderStub = stub
}

func (fake *FakePurchaseOrderService) DeletePurchaseOrderArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.deletePurchaseOrderMutex.RLock()
	defer fake.deletePurchaseOrderMutex.RUnlock()
	argsForCall := fake.deletePurchaseOrderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePurchaseOrderService) DeletePurchaseOrderReturns(result1 error) {
	fake.deletePurchaseOrderMutex.Lock()
	defer fake.deletePurchaseOrderMutex.Unlock()
	fake.DeletePurchaseOrderStub = nil
	fake.deletePurchaseOrderReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderService) DeletePurchaseOrderReturnsOnCall(i int, result1 error) {
	fake.deletePurchaseOrderMutex.Lock()
	defer fake.deletePurchaseOrderMutex.Unlock()
	fake.DeletePurchaseOrderStub = nil
	if fake.deletePurchaseOrderReturnsOnCall == nil {
		fake.deletePurchaseOrderReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deletePurchaseOrderReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderService) GetPurchaseOrder(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (*models.PurchaseOrder, error) {
	fake.getPurchaseOrderMutex.Lock()
	ret, specificReturn := fake.getPurchaseOrderReturnsOnCall[len(fake.getPurchaseOrderArgsForCall)]
	fake.getPurchaseOrderArgsForCall = append(fake.getPurchaseOrderArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.GetPurchaseOrderStub
	fakeReturns := fake.getPurchaseOrderReturns
	fake.recordInvocation("GetPurchaseOrder", []interface{}{arg1, arg2, arg3})
	fake.getPurchaseOrderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePurchaseOrderService) GetPurchaseOrderCallCount() int {
	fake.getPurchaseOrderMutex.RLock()
	defer fake.getPurchaseOrderMutex.RUnlock()
	return len(fake.getPurchaseOrderArgsForCall)
}

func (fake *FakePurchaseOrderService) GetPurchaseOrderCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (*models.PurchaseOrder, error)) {
	fake.getPurchaseOrderMutex.Lock()
	defer fake.getPurchaseOrderMutex.Unlock()
	fake.GetPurchaseOrderStub = stub
}

func (fake *FakePurchaseOrderService) GetPurchaseOrderArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.getPurchaseOrderMutex.RLock()
	defer fake.getPurchaseOrderMutex.RUnlock()
	argsForCall := fake.getPurchaseOrderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePurchaseOrderService) GetPurchaseOrderReturns(result1 *models.PurchaseOrder, result2 error) {
	fake.getPurchaseOrderMutex.Lock()
	defer fake.getPurchaseOrderMutex.Unlock()
	fake.GetPurchaseOrderStub = nil
	fake.getPurchaseOrderReturns = struct {
		result1 *models.PurchaseOrder
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderService) GetPurchaseOrderReturnsOnCall(i int, result1 *models.PurchaseOrder, result2 error) {
	fake.getPurchaseOrderMutex.Lock()
	defer fake.getPurchaseOrderMutex.Unlock()
	fake.GetPurchaseOrderStub = nil
	if fake.getPurchaseOrderReturnsOnCall == nil {
		fake.getPurchaseOrderReturnsOnCall = make(map[int]struct {
			result1 *models.PurchaseOrder
			result2 error
		})
	}
	fake.getPurchaseOrderReturnsOnCall[i] = struct {
		result1 *models.PurchaseOrder
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderService) ListItems(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) ([]*models.PurchaseOrderItem, error) {
	fake.listItemsMutex.Lock()
	ret, specificReturn := fake.listItemsReturnsOnCall[len(fake.listItemsArgsForCall)]
	fake.listItemsArgsForCall = append(fake.listItemsArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.ListItemsStub
	fakeReturns := fake.listItemsReturns
	fake.recordInvocation("ListItems", []interface{}{arg1, arg2, arg3})
	fake.listItemsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePurchaseOrderService) ListItemsCallCount() int {
	fake.listItemsMutex.RLock()
	defer fake.listItemsMutex.RUnlock()
	return len(fake.listItemsArgsForCall)
}

func (fake *FakePurchaseOrderService) ListItemsCalls(stub func(context.Context, uuid.UUID, uuid.UUID) ([]*models.PurchaseOrderItem, error)) {
	fake.listItemsMutex.Lock()
	defer fake.listItemsMutex.Unlock()
	fake.ListItemsStub = stub
}

func (fake *FakePurchaseOrderService) ListItemsArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.listItemsMutex.RLock()
	defer fake.listItemsMutex.RUnlock()
	argsForCall := fake.listItemsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePurchaseOrderService) ListItemsReturns(result1 []*models.PurchaseOrderItem, result2 error) {
	fake.listItemsMutex.Lock()
	defer fake.listItemsMutex.Unlock()
	fake.ListItemsStub = nil
	fake.listItemsReturns = struct {
		result1 []*models.PurchaseOrderItem
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderService) ListItemsReturnsOnCall(i int, result1 []*models.PurchaseOrderItem, result2 error) {
	fake.listItemsMutex.Lock()
	defer fake.listItemsMutex.Unlock()
	fake.ListItemsStub = nil
	if fake.listItemsReturnsOnCall == nil {
		fake.listItemsReturnsOnCall = make(map[int]struct {
			result1 []*models.PurchaseOrderItem
			result2 error
		})
	}
	fake.listItemsReturnsOnCall[i] = struct {
		result1 []*models.PurchaseOrderItem
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderService) ListPurchaseOrders(arg1 context.Context, arg2 uuid.UUID, arg3 *services.PurchaseOrderFilters, arg4 int, arg5 int) ([]*models.PurchaseOrder, int, error) {
	fake.listPurchaseOrdersMutex.Lock()
	ret, specificReturn := fake.listPurchaseOrdersReturnsOnCall[len(fake.listPurchaseOrdersArgsForCall)]
	fake.listPurchaseOrdersArgsForCall = append(fake.listPurchaseOrdersArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 *services.PurchaseOrderFilters
		arg4 int
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ListPurchaseOrdersStub
	fakeReturns := fake.listPurchaseOrdersReturns
	fake.recordInvocation("ListPurchaseOrders", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.listPurchaseOrdersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakePurchaseOrderService) ListPurchaseOrdersCallCount() int {
	fake.listPurchaseOrdersMutex.RLock()
	defer fake.listPurchaseOrdersMutex.RUnlock()
	return len(fake.listPurchaseOrdersArgsForCall)
}

func (fake *FakePurchaseOrderService) ListPurchaseOrdersCalls(stub func(context.Context, uuid.UUID, *services.PurchaseOrderFilters, int, int) ([]*models.PurchaseOrder, int, error)) {
	fake.listPurchaseOrdersMutex.Lock()
	defer fake.listPurchaseOrdersMutex.Unlock()
	fake.ListPurchaseOrdersStub = stub
}

func (fake *FakePurchaseOrderService) ListPurchaseOrdersArgsForCall(i int) (context.Context, uuid.UUID, *services.PurchaseOrderFilters, int, int) {
	fake.listPurchaseOrdersMutex.RLock()
	defer fake.listPurchaseOrdersMutex.RUnlock()
	argsForCall := fake.listPurchaseOrdersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakePurchaseOrderService) ListPurchaseOrdersReturns(result1 []*models.PurchaseOrder, result2 int, result3 error) {
	fake.listPurchaseOrdersMutex.Lock()
	defer fake.listPurchaseOrdersMutex.Unlock()
	fake.ListPurchaseOrdersStub = nil
	fake.listPurchaseOrdersReturns = struct {
		result1 []*models.PurchaseOrder
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakePurchaseOrderService) ListPurchaseOrdersReturnsOnCall(i int, result1 []*models.PurchaseOrder, result2 int, result3 error) {
	fake.listPurchaseOrdersMutex.Lock()
	defer fake.listPurchaseOrdersMutex.Unlock()
	fake.ListPurchaseOrdersStub = nil
	if fake.listPurchaseOrdersReturnsOnCall == nil {
		fake.listPurchaseOrdersReturnsOnCall = make(map[int]struct {
			result1 []*models.PurchaseOrder
			result2 int
			result3 error
		})
	}
	fake.listPurchaseOrdersReturnsOnCall[i] = struct {
		result1 []*models.PurchaseOrder
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakePurchaseOrderService) ReceiveItems(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 []services.ReceiveItemRequest) error {
	var arg4Copy []services.ReceiveItemRequest
	if arg4 != nil {
		arg4Copy = make([]services.ReceiveItemRequest, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.receiveItemsMutex.Lock()
	ret, specificReturn := fake.receiveItemsReturnsOnCall[len(fake.receiveItemsArgsForCall)]
	fake.receiveItemsArgsForCall = append(fake.receiveItemsArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 []services.ReceiveItemRequest
	}{arg1, arg2, arg3, arg4Copy})
	stub := fake.ReceiveItemsStub
	fakeReturns := fake.receiveItemsReturns
	fake.recordInvocation("ReceiveItems", []interface{}{arg1, arg2, arg3, arg4Copy})
	fake.receiveItemsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePurchaseOrderService) ReceiveItemsCallCount() int {
	fake.receiveItemsMutex.RLock()
	defer fake.receiveItemsMutex.RUnlock()
	return len(fake.receiveItemsArgsForCall)
}

func (fake *FakePurchaseOrderService) ReceiveItemsCalls(stub func(context.Context, uuid.UUID, uuid.UUID, []services.ReceiveItemRequest) error) {
	fake.receiveItemsMutex.Lock()
	defer fake.receiveItemsMutex.Unlock()
	fake.ReceiveItemsStub = stub
}

func (fake *FakePurchaseOrderService) ReceiveItemsArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, []services.ReceiveItemRequest) {
	fake.receiveItemsMutex.RLock()
	defer fake.receiveItemsMutex.RUnlock()
	argsForCall := fake.receiveItemsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakePurchaseOrderService) ReceiveItemsReturns(result1 error) {
	fake.receiveItemsMutex.Lock()
	defer fake.receiveItemsMutex.Unlock()
	fake.ReceiveItemsStub = nil
	fake.receiveItemsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderService) ReceiveItemsReturnsOnCall(i int, result1 error) {
	fake.receiveItemsMutex.Lock()
	defer fake.receiveItemsMutex.Unlock()
	fake.ReceiveItemsStub = nil
	if fake.receiveItemsReturnsOnCall == nil {
		fake.receiveItemsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.receiveItemsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderService) RemoveItem(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 uuid.UUID) error {
	fake.removeItemMutex.Lock()
	ret, specificReturn := fake.removeItemReturnsOnCall[len(fake.removeItemArgsForCall)]
	fake.removeItemArgsForCall = append(fake.removeItemArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 uuid.UUID
	}{arg1, arg2, arg3, arg4})
	stub := fake.RemoveItemStub
	fakeReturns := fake.removeItemReturns
	fake.recordInvocation("RemoveItem", []interface{}{arg1, arg2, arg3, arg4})
	fake.removeItemMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePurchaseOrderService) RemoveItemCallCount() int {
	fake.removeItemMutex.RLock()
	defer fake.removeItemMutex.RUnlock()
	return len(fake.removeItemArgsForCall)
}

func (fake *FakePurchaseOrderService) RemoveItemCalls(stub func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) {
	fake.removeItemMutex.Lock()
	defer fake.removeItemMutex.Unlock()
	fake.RemoveItemStub = stub
}

func (fake *FakePurchaseOrderService) RemoveItemArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, uuid.UUID) {
	fake.removeItemMutex.RLock()
	defer fake.removeItemMutex.RUnlock()
	argsForCall := fake.removeItemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakePurchaseOrderService) RemoveItemReturns(result1 error) {
	fake.removeItemMutex.Lock()
	defer fake.removeItemMutex.Unlock()
	fake.RemoveItemStub = nil
	fake.removeItemReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderService) RemoveItemReturnsOnCall(i int, result1 error) {
	fake.removeItemMutex.Lock()
	defer fake.removeItemMutex.Unlock()
	fake.RemoveItemStub = nil
	if fake.removeItemReturnsOnCall == nil {
		fake.removeItemReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeItemReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderService) SubmitPurchaseOrder(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.submitPurchaseOrderMutex.Lock()
	ret, specificReturn := fake.submitPurchaseOrderReturnsOnCall[len(fake.submitPurchaseOrderArgsForCall)]
	fake.submitPurchaseOrderArgsForCall = append(fake.submitPurchaseOrderArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.SubmitPurchaseOrderStub
	fakeReturns := fake.submitPurchaseOrderReturns
	fake.recordInvocation("SubmitPurchaseOrder", []interface{}{arg1, arg2, arg3})
	fake.submitPurchaseOrderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePurchaseOrderService) SubmitPurchaseOrderCallCount() int {
	fake.submitPurchaseOrderMutex.RLock()
	defer fake.submitPurchaseOrderMutex.RUnlock()
	return len(fake.submitPurchaseOrderArgsForCall)
}

func (fake *FakePurchaseOrderService) SubmitPurchaseOrderCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.submitPurchaseOrderMutex.Lock()
	defer fake.submitPurchaseOrderMutex.Unlock()
	fake.SubmitPurchaseOrderStub = stub
}

func (fake *FakePurchaseOrderService) SubmitPurchaseOrderArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.submitPurchaseOrderMutex.RLock()
	defer fake.submitPurchaseOrderMutex.RUnlock()
	argsForCall := fake.submitPurchaseOrderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePurchaseOrderService) SubmitPurchaseOrderReturns(result1 error) {
	fake.submitPurchaseOrderMutex.Lock()
	defer fake.submitPurchaseOrderMutex.Unlock()
	fake.SubmitPurchaseOrderStub = nil
	fake.submitPurchaseOrderReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderService) SubmitPurchaseOrderReturnsOnCall(i int, result1 error) {
	fake.submitPurchaseOrderMutex.Lock()
	defer fake.submitPurchaseOrderMutex.Unlock()
	fake.SubmitPurchaseOrderStub = nil
	if fake.submitPurchaseOrderReturnsOnCall == nil {
		fake.submitPurchaseOrderReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.submitPurchaseOrderReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderService) UpdatePurchaseOrder(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 *services.UpdatePurchaseOrderRequest) error {
	fake.updatePurchaseOrderMutex.Lock()
	ret, specificReturn := fake.updatePurchaseOrderReturnsOnCall[len(fake.updatePurchaseOrderArgsForCall)]
	fake.updatePurchaseOrderArgsForCall = append(fake.updatePurchaseOrderArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 *services.UpdatePurchaseOrderRequest
	}{arg1, arg2, arg3, arg4})
	stub := fake.UpdatePurchaseOrderStub
	fakeReturns := fake.updatePurchaseOrderReturns
	fake.recordInvocation("UpdatePurchaseOrder", []interface{}{arg1, arg2, arg3, arg4})
	fake.updatePurchaseOrderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePurchaseOrderService) UpdatePurchaseOrderCallCount() int {
	fake.updatePurchaseOrderMutex.RLock()
	defer fake.updatePurchaseOrderMutex.RUnlock()
	return len(fake.updatePurchaseOrderArgsForCall)
}

func (fake *FakePurchaseOrderService) UpdatePurchaseOrderCalls(stub func(context.Context, uuid.UUID, uuid.UUID, *services.UpdatePurchaseOrderRequest) error) {
	fake.updatePurchaseOrderMutex.Lock()
	defer fake.updatePurchaseOrderMutex.Unlock()
	fake.UpdatePurchaseOrderStub = stub
}

func (fake *FakePurchaseOrderService) UpdatePurchaseOrderArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, *services.UpdatePurchaseOrderRequest) {
	fake.updatePurchaseOrderMutex.RLock()
	defer fake.updatePurchaseOrderMutex.RUnlock()
	argsForCall := fake.updatePurchaseOrderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakePurchaseOrderService) UpdatePurchaseOrderReturns(result1 error) {
	fake.updatePurchaseOrderMutex.Lock()
	defer fake.updatePurchaseOrderMutex.Unlock()
	fake.UpdatePurchaseOrderStub = nil
	fake.updatePurchaseOrderReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderService) UpdatePurchaseOrderReturnsOnCall(i int, result1 error) {
	fake.updatePurchaseOrderMutex.Lock()
	defer fake.updatePurchaseOrderMutex.Unlock()
	fake.UpdatePurchaseOrderStub = nil
	if fake.updatePurchaseOrderReturnsOnCall == nil {
		fake.updatePurchaseOrderReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updatePurchaseOrderReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePurchaseOrderService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ services.PurchaseOrderService = new(FakePurchaseOrderService)
