// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/yourorg/shoppilot/internal/models"
	"github.com/yourorg/shoppilot/internal/services"
)

type FakeSalesOrderService struct {
	AddItemStub        func(context.Context, uuid.UUID, uuid.UUID, *services.AddSalesOrderItemRequest) (*models.SalesOrderItem, error)
	addItemMutex       sync.RWMutex
	addItemArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 *services.AddSalesOrderItemRequest
	}
	addItemReturns struct {
		result1 *models.SalesOrderItem
		result2 error
	}
	addItemReturnsOnCall map[int]struct {
		result1 *models.SalesOrderItem
		result2 error
	}
	CancelSalesOrderStub        func(context.Context, uuid.UUID, uuid.UUID) error
	cancelSalesOrderMutex       sync.RWMutex
	cancelSalesOrderArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	cancelSalesOrderReturns struct {
		result1 error
	}
	cancelSalesOrderReturnsOnCall map[int]struct {
		result1 error
	}
	ConfirmSalesOrderStub        func(context.Context, uuid.UUID, uuid.UUID) error
	confirmSalesOrderMutex       sync.RWMutex
	confirmSalesOrderArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	confirmSalesOrderReturns struct {
		result1 error
	}
	confirmSalesOrderReturnsOnCall map[int]struct {
		result1 error
	}
	CreateSalesOrderStub        func(context.Context, uuid.UUID, *services.CreateSalesOrderRequest) (*models.SalesOrder, error)
	createSalesOrderMutex       sync.RWMutex
	createSalesOrderArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 *services.CreateSalesOrderRequest
	}
	createSalesOrderReturns struct {
		result1 *models.SalesOrder
		result2 error
	}
	createSalesOrderReturnsOnCall map[int]struct {
		result1 *models.SalesOrder
		result2 error
	}
	DeleteSalesOrderStub        func(context.Context, uuid.UUID, uuid.UUID) error
	deleteSalesOrderMutex       sync.RWMutex
	deleteSalesOrderArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	deleteSalesOrderReturns struct {
		result1 error
	}
	deleteSalesOrderReturnsOnCall map[int]struct {
		result1 error
	}
	FulfillItemsStub        func(context.Context, uuid.UUID, uuid.UUID, []services.FulfillItemRequest) error
	fulfillItemsMutex       sync.RWMutex
	fulfillItemsArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 []services.FulfillItemRequest
	}
	fulfillItemsReturns struct {
		result1 error
	}
	fulfillItemsReturnsOnCall map[int]struct {
		result1 error
	}
	GetSalesOrderStub        func(context.Context, uuid.UUID, uuid.UUID) (*models.SalesOrder, error)
	getSalesOrderMutex       sync.RWMutex
	getSalesOrderArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	getSalesOrderReturns struct {
		result1 *models.SalesOrder
		result2 error
	}
	getSalesOrderReturnsOnCall map[int]struct {
		result1 *models.SalesOrder
		result2 error
	}
	ListItemsStub        func(context.Context, uuid.UUID, uuid.UUID) ([]*models.SalesOrderItem, error)
	listItemsMutex       sync.RWMutex
	listItemsArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	listItemsReturns struct {
		result1 []*models.SalesOrderItem
		result2 error
	}
	listItemsReturnsOnCall map[int]struct {
		result1 []*models.SalesOrderItem
		result2 error
	}
	ListSalesOrdersStub        func(context.Context, uuid.UUID, *services.SalesOrderFilters, int, int) ([]*models.SalesOrder, int, error)
	listSalesOrdersMutex       sync.RWMutex
	listSalesOrdersArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 *services.SalesOrderFilters
		arg4 int
		arg5 int
	}
	listSalesOrdersReturns struct {
		result1 []*models.SalesOrder
		result2 int
		result3 error
	}
	listSalesOrdersReturnsOnCall map[int]struct {
		result1 []*models.SalesOrder
		result2 int
		result3 error
	}
	RemoveItemStub        func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error
	removeItemMutex       sync.RWMutex
	removeItemArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 uuid.UUID
	}
	removeItemReturns struct {
		result1 error
	}
	removeItemReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateSalesOrderStub        func(context.Context, uuid.UUID, uuid.UUID, *services.UpdateSalesOrderRequest) error
	updateSalesOrderMutex       sync.RWMutex
	updateSalesOrderArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 *services.UpdateSalesOrderRequest
	}
	updateSalesOrderReturns struct {
		result1 error
	}
	updateSalesOrderReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSalesOrderService) AddItem(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 *services.AddSalesOrderItemRequest) (*models.SalesOrderItem, error) {
	fake.addItemMutex.Lock()
	ret, specificReturn := fake.addItemReturnsOnCall[len(fake.addItemArgsForCall)]
	fake.addItemArgsForCall = append(fake.addItemArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 *services.AddSalesOrderItemRequest
	}{arg1, arg2, arg3, arg4})
	stub := fake.AddItemStub
	fakeReturns := fake.addItemReturns
	fake.recordInvocation("AddItem", []interface{}{arg1, arg2, arg3, arg4})
	fake.addItemMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSalesOrderService) AddItemCallCount() int {
	fake.addItemMutex.RLock()
	defer fake.addItemMutex.RUnlock()
	return len(fake.addItemArgsForCall)
}

func (fake *FakeSalesOrderService) AddItemCalls(stub func(context.Context, uuid.UUID, uuid.UUID, *services.AddSalesOrderItemRequest) (*models.SalesOrderItem, error)) {
	fake.addItemMutex.Lock()
	defer fake.addItemMutex.Unlock()
	fake.AddItemStub = stub
}

func (fake *FakeSalesOrderService) AddItemArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, *services.AddSalesOrderItemRequest) {
	fake.addItemMutex.RLock()
	defer fake.addItemMutex.RUnlock()
	argsForCall := fake.addItemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeSalesOrderService) AddItemReturns(result1 *models.SalesOrderItem, result2 error) {
	fake.addItemMutex.Lock()
	defer fake.addItemMutex.Unlock()
	fake.AddItemStub = nil
	fake.addItemReturns = struct {
		result1 *models.SalesOrderItem
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderService) AddItemReturnsOnCall(i int, result1 *models.SalesOrderItem, result2 error) {
	fake.addItemMutex.Lock()
	defer fake.addItemMutex.Unlock()
	fake.AddItemStub = nil
	if fake.addItemReturnsOnCall == nil {
		fake.addItemReturnsOnCall = make(map[int]struct {
			result1 *models.SalesOrderItem
			result2 error
		})
	}
	fake.addItemReturnsOnCall[i] = struct {
		result1 *models.SalesOrderItem
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderService) CancelSalesOrder(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.cancelSalesOrderMutex.Lock()
	ret, specificReturn := fake.cancelSalesOrderReturnsOnCall[len(fake.cancelSalesOrderArgsForCall)]
	fake.cancelSalesOrderArgsForCall = append(fake.cancelSalesOrderArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.CancelSalesOrderStub
	fakeReturns := fake.cancelSalesOrderReturns
	fake.recordInvocation("CancelSalesOrder", []interface{}{arg1, arg2, arg3})
	fake.cancelSalesOrderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSalesOrderService) CancelSalesOrderCallCount() int {
	fake.cancelSalesOrderMutex.RLock()
	defer fake.cancelSalesOrderMutex.RUnlock()
	return len(fake.cancelSalesOrderArgsForCall)
}

func (fake *FakeSalesOrderService) CancelSalesOrderCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.cancelSalesOrderMutex.Lock()
	defer fake.cancelSalesOrderMutex.Unlock()
	fake.CancelSalesOrderStub = stub
}

func (fake *FakeSalesOrderService) CancelSalesOrderArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.cancelSalesOrderMutex.RLock()
	defer fake.cancelSalesOrderMutex.RUnlock()
	argsForCall := fake.cancelSalesOrderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSalesOrderService) CancelSalesOrderReturns(result1 error) {
	fake.cancelSalesOrderMutex.Lock()
	defer fake.cancelSalesOrderMutex.Unlock()
	fake.CancelSalesOrderStub = nil
	fake.cancelSalesOrderReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderService) CancelSalesOrderReturnsOnCall(i int, result1 error) {
	fake.cancelSalesOrderMutex.Lock()
	defer fake.cancelSalesOrderMutex.Unlock()
	fake.CancelSalesOrderStub = nil
	if fake.cancelSalesOrderReturnsOnCall == nil {
		fake.cancelSalesOrderReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.cancelSalesOrderReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderService) ConfirmSalesOrder(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.confirmSalesOrderMutex.Lock()
	ret, specificReturn := fake.confirmSalesOrderReturnsOnCall[len(fake.confirmSalesOrderArgsForCall)]
	fake.confirmSalesOrderArgsForCall = append(fake.confirmSalesOrderArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.ConfirmSalesOrderStub
	fakeReturns := fake.confirmSalesOrderReturns
	fake.recordInvocation("ConfirmSalesOrder", []interface{}{arg1, arg2, arg3})
	fake.confirmSalesOrderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSalesOrderService) ConfirmSalesOrderCallCount() int {
	fake.confirmSalesOrderMutex.RLock()
	defer fake.confirmSalesOrderMutex.RUnlock()
	return len(fake.confirmSalesOrderArgsForCall)
}

func (fake *FakeSalesOrderService) ConfirmSalesOrderCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.confirmSalesOrderMutex.Lock()
	defer fake.confirmSalesOrderMutex.Unlock()
	fake.ConfirmSalesOrderStub = stub
}

func (fake *FakeSalesOrderService) ConfirmSalesOrderArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.confirmSalesOrderMutex.RLock()
	defer fake.confirmSalesOrderMutex.RUnlock()
	argsForCall := fake.confirmSalesOrderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSalesOrderService) ConfirmSalesOrderReturns(result1 error) {
	fake.confirmSalesOrderMutex.Lock()
	defer fake.confirmSalesOrderMutex.Unlock()
	fake.ConfirmSalesOrderStub = nil
	fake.confirmSalesOrderReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderService) ConfirmSalesOrderReturnsOnCall(i int, result1 error) {
	fake.confirmSalesOrderMutex.Lock()
	defer fake.confirmSalesOrderMutex.Unlock()
	fake.ConfirmSalesOrderStub = nil
	if fake.confirmSalesOrderReturnsOnCall == nil {
		fake.confirmSalesOrderReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.confirmSalesOrderReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderService) CreateSalesOrder(arg1 context.Context, arg2 uuid.UUID, arg3 *services.CreateSalesOrderRequest) (*models.SalesOrder, error) {
	fake.createSalesOrderMutex.Lock()
	ret, specificReturn := fake.createSalesOrderReturnsOnCall[len(fake.createSalesOrderArgsForCall)]
	fake.createSalesOrderArgsForCall = append(fake.createSalesOrderArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 *services.CreateSalesOrderRequest
	}{arg1, arg2, arg3})
	stub := fake.CreateSalesOrderStub
	fakeReturns := fake.createSalesOrderReturns
	fake.recordInvocation("CreateSalesOrder", []interface{}{arg1, arg2, arg3})
	fake.createSalesOrderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSalesOrderService) CreateSalesOrderCallCount() int {
	fake.createSalesOrderMutex.RLock()
	defer fake.createSalesOrderMutex.RUnlock()
	return len(fake.createSalesOrderArgsForCall)
}

func (fake *FakeSalesOrderService) CreateSalesOrderCalls(stub func(context.Context, uuid.UUID, *services.CreateSalesOrderRequest) (*models.SalesOrder, error)) {
	fake.createSalesOrderMutex.Lock()
	defer fake.createSalesOrderMutex.Unlock()
	fake.CreateSalesOrderStub = stub
}

func (fake *FakeSalesOrderService) CreateSalesOrderArgsForCall(i int) (context.Context, uuid.UUID, *services.CreateSalesOrderRequest) {
	fake.createSalesOrderMutex.RLock()
	defer fake.createSalesOrderMutex.RUnlock()
	argsForCall := fake.createSalesOrderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSalesOrderService) CreateSalesOrderReturns(result1 *models.SalesOrder, result2 error) {
	fake.createSalesOrderMutex.Lock()
	defer fake.createSalesOrderMutex.Unlock()
	fake.CreateSalesOrderStub = nil
	fake.createSalesOrderReturns = struct {
		result1 *models.SalesOrder
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderService) CreateSalesOrderReturnsOnCall(i int, result1 *models.SalesOrder, result2 error) {
	fake.createSalesOrderMutex.Lock()
	defer fake.createSalesOrderMutex.Unlock()
	fake.CreateSalesOrderStub = nil
	if fake.createSalesOrderReturnsOnCall == nil {
		fake.createSalesOrderReturnsOnCall = make(map[int]struct {
			result1 *models.SalesOrder
			result2 error
		})
	}
	fake.createSalesOrderReturnsOnCall[i] = struct {
		result1 *models.SalesOrder
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderService) DeleteSalesOrder(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.deleteSalesOrderMutex.Lock()
	ret, specificReturn := fake.deleteSalesOrderReturnsOnCall[len(fake.deleteSalesOrderArgsForCall)]
	fake.deleteSalesOrderArgsForCall = append(fake.deleteSalesOrderArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.DeleteSalesOrderStub
	fakeReturns := fake.deleteSalesOrderReturns
	fake.recordInvocation("DeleteSalesOrder", []interface{}{arg1, arg2, arg3})
	fake.deleteSalesOrderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSalesOrderService) DeleteSalesOrderCallCount() int {
	fake.deleteSalesOrderMutex.RLock()
	defer fake.deleteSalesOrderMutex.RUnlock()
	return len(fake.deleteSalesOrderArgsForCall)
}

func (fake *FakeSalesOrderService) DeleteSalesOrderCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.deleteSalesOrderMutex.Lock()
	defer fake.deleteSalesOrderMutex.Unlock()
	fake.DeleteSalesOrderStub = stub
}

func (fake *FakeSalesOrderService) DeleteSalesOrderArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.deleteSalesOrderMutex.RLock()
	defer fake.deleteSalesOrderMutex.RUnlock()
	argsForCall := fake.deleteSalesOrderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSalesOrderService) DeleteSalesOrderReturns(result1 error) {
	fake.deleteSalesOrderMutex.Lock()
	defer fake.deleteSalesOrderMutex.Unlock()
	fake.DeleteSalesOrderStub = nil
	fake.deleteSalesOrderReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderService) DeleteSalesOrderReturnsOnCall(i int, result1 error) {
	fake.deleteSalesOrderMutex.Lock()
	defer fake.deleteSalesOrderMutex.Unlock()
	fake.DeleteSalesOrderStub = nil
	if fake.deleteSalesOrderReturnsOnCall == nil {
		fake.deleteSalesOrderReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteSalesOrderReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderService) FulfillItems(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 []services.FulfillItemRequest) error {
	var arg4Copy []services.FulfillItemRequest
	if arg4 != nil {
		arg4Copy = make([]services.FulfillItemRequest, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.fulfillItemsMutex.Lock()
	ret, specificReturn := fake.fulfillItemsReturnsOnCall[len(fake.fulfillItemsArgsForCall)]
	fake.fulfillItemsArgsForCall = append(fake.fulfillItemsArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 []services.FulfillItemRequest
	}{arg1, arg2, arg3, arg4Copy})
	stub := fake.FulfillItemsStub
	fakeReturns := fake.fulfillItemsReturns
	fake.recordInvocation("FulfillItems", []interface{}{arg1, arg2, arg3, arg4Copy})
	fake.fulfillItemsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSalesOrderService) FulfillItemsCallCount() int {
	fake.fulfillItemsMutex.RLock()
	defer fake.fulfillItemsMutex.RUnlock()
	return len(fake.fulfillItemsArgsForCall)
}

func (fake *FakeSalesOrderService) FulfillItemsCalls(stub func(context.Context, uuid.UUID, uuid.UUID, []services.FulfillItemRequest) error) {
	fake.fulfillItemsMutex.Lock()
	defer fake.fulfillItemsMutex.Unlock()
	fake.FulfillItemsStub = stub
}

func (fake *FakeSalesOrderService) FulfillItemsArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, []services.FulfillItemRequest) {
	fake.fulfillItemsMutex.RLock()
	defer fake.fulfillItemsMutex.RUnlock()
	argsForCall := fake.fulfillItemsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeSalesOrderService) FulfillItemsReturns(result1 error) {
	fake.fulfillItemsMutex.Lock()
	defer fake.fulfillItemsMutex.Unlock()
	fake.FulfillItemsStub = nil
	fake.fulfillItemsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderService) FulfillItemsReturnsOnCall(i int, result1 error) {
	fake.fulfillItemsMutex.Lock()
	defer fake.fulfillItemsMutex.Unlock()
	fake.FulfillItemsStub = nil
	if fake.fulfillItemsReturnsOnCall == nil {
		fake.fulfillItemsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.fulfillItemsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderService) GetSalesOrder(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (*models.SalesOrder, error) {
	fake.getSalesOrderMutex.Lock()
	ret, specificReturn := fake.getSalesOrderReturnsOnCall[len(fake.getSalesOrderArgsForCall)]
	fake.getSalesOrderArgsForCall = append(fake.getSalesOrderArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.GetSalesOrderStub
	fakeReturns := fake.getSalesOrderReturns
	fake.recordInvocation("GetSalesOrder", []interface{}{arg1, arg2, arg3})
	fake.getSalesOrderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSalesOrderService) GetSalesOrderCallCount() int {
	fake.getSalesOrderMutex.RLock()
	defer fake.getSalesOrderMutex.RUnlock()
	return len(fake.getSalesOrderArgsForCall)
}

func (fake *FakeSalesOrderService) GetSalesOrderCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (*models.SalesOrder, error)) {
	fake.getSalesOrderMutex.Lock()
	defer fake.getSalesOrderMutex.Unlock()
	fake.GetSalesOrderStub = stub
}

func (fake *FakeSalesOrderService) GetSalesOrderArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.getSalesOrderMutex.RLock()
	defer fake.getSalesOrderMutex.RUnlock()
	argsForCall := fake.getSalesOrderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSalesOrderService) GetSalesOrderReturns(result1 *models.SalesOrder, result2 error) {
	fake.getSalesOrderMutex.Lock()
	defer fake.getSalesOrderMutex.Unlock()
	fake.GetSalesOrderStub = nil
	fake.getSalesOrderReturns = struct {
		result1 *models.SalesOrder
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderService) GetSalesOrderReturnsOnCall(i int, result1 *models.SalesOrder, result2 error) {
	fake.getSalesOrderMutex.Lock()
	defer fake.getSalesOrderMutex.Unlock()
	fake.GetSalesOrderStub = nil
	if fake.getSalesOrderReturnsOnCall == nil {
		fake.getSalesOrderReturnsOnCall = make(map[int]struct {
			result1 *models.SalesOrder
			result2 error
		})
	}
	fake.getSalesOrderReturnsOnCall[i] = struct {
		result1 *models.SalesOrder
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderService) ListItems(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) ([]*models.SalesOrderItem, error) {
	fake.listItemsMutex.Lock()
	ret, specificReturn := fake.listItemsReturnsOnCall[len(fake.listItemsArgsForCall)]
	fake.listItemsArgsForCall = append(fake.listItemsArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.ListItemsStub
	fakeReturns := fake.listItemsReturns
	fake.recordInvocation("ListItems", []interface{}{arg1, arg2, arg3})
	fake.listItemsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSalesOrderService) ListItemsCallCount() int {
	fake.listItemsMutex.RLock()
	defer fake.listItemsMutex.RUnlock()
	return len(fake.listItemsArgsForCall)
}

func (fake *FakeSalesOrderService) ListItemsCalls(stub func(context.Context, uuid.UUID, uuid.UUID) ([]*models.SalesOrderItem, error)) {
	fake.listItemsMutex.Lock()
	defer fake.listItemsMutex.Unlock()
	fake.ListItemsStub = stub
}

func (fake *FakeSalesOrderService) ListItemsArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.listItemsMutex.RLock()
	defer fake.listItemsMutex.RUnlock()
	argsForCall := fake.listItemsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSalesOrderService) ListItemsReturns(result1 []*models.SalesOrderItem, result2 error) {
	fake.listItemsMutex.Lock()
	defer fake.listItemsMutex.Unlock()
	fake.ListItemsStub = nil
	fake.listItemsReturns = struct {
		result1 []*models.SalesOrderItem
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderService) ListItemsReturnsOnCall(i int, result1 []*models.SalesOrderItem, result2 error) {
	fake.listItemsMutex.Lock()
	defer fake.listItemsMutex.Unlock()
	fake.ListItemsStub = nil
	if fake.listItemsReturnsOnCall == nil {
		fake.listItemsReturnsOnCall = make(map[int]struct {
			result1 []*models.SalesOrderItem
			result2 error
		})
	}
	fake.listItemsReturnsOnCall[i] = struct {
		result1 []*models.SalesOrderItem
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderService) ListSalesOrders(arg1 context.Context, arg2 uuid.UUID, arg3 *services.SalesOrderFilters, arg4 int, arg5 int) ([]*models.SalesOrder, int, error) {
	fake.listSalesOrdersMutex.Lock()
	ret, specificReturn := fake.listSalesOrdersReturnsOnCall[len(fake.listSalesOrdersArgsForCall)]
	fake.listSalesOrdersArgsForCall = append(fake.listSalesOrdersArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 *services.SalesOrderFilters
		arg4 int
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ListSalesOrdersStub
	fakeReturns := fake.listSalesOrdersReturns
	fake.recordInvocation("ListSalesOrders", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.listSalesOrdersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeSalesOrderService) ListSalesOrdersCallCount() int {
	fake.listSalesOrdersMutex.RLock()
	defer fake.listSalesOrdersMutex.RUnlock()
	return len(fake.listSalesOrdersArgsForCall)
}

func (fake *FakeSalesOrderService) ListSalesOrdersCalls(stub func(context.Context, uuid.UUID, *services.SalesOrderFilters, int, int) ([]*models.SalesOrder, int, error)) {
	fake.listSalesOrdersMutex.Lock()
	defer fake.listSalesOrdersMutex.Unlock()
	fake.ListSalesOrdersStub = stub
}

func (fake *FakeSalesOrderService) ListSalesOrdersArgsForCall(i int) (context.Context, uuid.UUID, *services.SalesOrderFilters, int, int) {
	fake.listSalesOrdersMutex.RLock()
	defer fake.listSalesOrdersMutex.RUnlock()
	argsForCall := fake.listSalesOrdersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeSalesOrderService) ListSalesOrdersReturns(result1 []*models.SalesOrder, result2 int, result3 error) {
	fake.listSalesOrdersMutex.Lock()
	defer fake.listSalesOrdersMutex.Unlock()
	fake.ListSalesOrdersStub = nil
	fake.listSalesOrdersReturns = struct {
		result1 []*models.SalesOrder
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeSalesOrderService) ListSalesOrdersReturnsOnCall(i int, result1 []*models.SalesOrder, result2 int, result3 error) {
	fake.listSalesOrdersMutex.Lock()
	defer fake.listSalesOrdersMutex.Unlock()
	fake.ListSalesOrdersStub = nil
	if fake.listSalesOrdersReturnsOnCall == nil {
		fake.listSalesOrdersReturnsOnCall = make(map[int]struct {
			result1 []*models.SalesOrder
			result2 int
			result3 error
		})
	}
	fake.listSalesOrdersReturnsOnCall[i] = struct {
		result1 []*models.SalesOrder
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeSalesOrderService) RemoveItem(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 uuid.UUID) error {
	fake.removeItemMutex.Lock()
	ret, specificReturn := fake.removeItemReturnsOnCall[len(fake.removeItemArgsForCall)]
	fake.removeItemArgsForCall = append(fake.removeItemArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 uuid.UUID
	}{arg1, arg2, arg3, arg4})
	stub := fake.RemoveItemStub
	fakeReturns := fake.removeItemReturns
	fake.recordInvocation("RemoveItem", []interface{}{arg1, arg2, arg3, arg4})
	fake.removeItemMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSalesOrderService) RemoveItemCallCount() int {
	fake.removeItemMutex.RLock()
	defer fake.removeItemMutex.RUnlock()
	return len(fake.removeItemArgsForCall)
}

func (fake *FakeSalesOrderService) RemoveItemCalls(stub func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) {
	fake.removeItemMutex.Lock()
	defer fake.removeItemMutex.Unlock()
	fake.RemoveItemStub = stub
}

func (fake *FakeSalesOrderService) RemoveItemArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, uuid.UUID) {
	fake.removeItemMutex.RLock()
	defer fake.removeItemMutex.RUnlock()
	argsForCall := fake.removeItemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeSalesOrderService) RemoveItemReturns(result1 error) {
	fake.removeItemMutex.Lock()
	defer fake.removeItemMutex.Unlock()
	fake.RemoveItemStub = nil
	fake.removeItemReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderService) RemoveItemReturnsOnCall(i int, result1 error) {
	fake.removeItemMutex.Lock()
	defer fake.removeItemMutex.Unlock()
	fake.RemoveItemStub = nil
	if fake.removeItemReturnsOnCall == nil {
		fake.removeItemReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeItemReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderService) UpdateSalesOrder(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 *services.UpdateSalesOrderRequest) error {
	fake.updateSalesOrderMutex.Lock()
	ret, specificReturn := fake.updateSalesOrderReturnsOnCall[len(fake.updateSalesOrderArgsForCall)]
	fake.updateSalesOrderArgsForCall = append(fake.updateSalesOrderArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 *services.UpdateSalesOrderRequest
	}{arg1, arg2, arg3, arg4})
	stub := fake.UpdateSalesOrderStub
	fakeReturns := fake.updateSalesOrderReturns
	fake.recordInvocation("UpdateSalesOrder", []interface{}{arg1, arg2, arg3, arg4})
	fake.updateSalesOrderMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSalesOrderService) UpdateSalesOrderCallCount() int {
	fake.updateSalesOrderMutex.RLock()
	defer fake.updateSalesOrderMutex.RUnlock()
	return len(fake.updateSalesOrderArgsForCall)
}

func (fake *FakeSalesOrderService) UpdateSalesOrderCalls(stub func(context.Context, uuid.UUID, uuid.UUID, *services.UpdateSalesOrderRequest) error) {
	fake.updateSalesOrderMutex.Lock()
	defer fake.updateSalesOrderMutex.Unlock()
	fake.UpdateSalesOrderStub = stub
}

func (fake *FakeSalesOrderService) UpdateSalesOrderArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, *services.UpdateSalesOrderRequest) {
	fake.updateSalesOrderMutex.RLock()
	defer fake.updateSalesOrderMutex.RUnlock()
	argsForCall := fake.updateSalesOrderArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeSalesOrderService) UpdateSalesOrderReturns(result1 error) {
	fake.updateSalesOrderMutex.Lock()
	defer fake.updateSalesOrderMutex.Unlock()
	fake.UpdateSalesOrderStub = nil
	fake.updateSalesOrderReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderService) UpdateSalesOrderReturnsOnCall(i int, result1 error) {
	fake.updateSalesOrderMutex.Lock()
	defer fake.updateSalesOrderMutex.Unlock()
	fake.UpdateSalesOrderStub = nil
	if fake.updateSalesOrderReturnsOnCall == nil {
		fake.updateSalesOrderReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateSalesOrderReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSalesOrderService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ services.SalesOrderService = new(FakeSalesOrderService)
