// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/yourorg/shoppilot/app/repositories"
	"github.com/yourorg/shoppilot/internal/models"
)

type FakePurchaseOrderRepository struct {
	CreateStub        func(context.Context, *models.PurchaseOrder) error
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 context.Context
		arg2 *models.PurchaseOrder
	}
	createReturns struct {
		result1 error
	}
	createReturnsOnCall map[int]struct {
		result1 error
	}
	CreateItemStub        func(context.Context, *models.PurchaseOrderItem) error
	createItemMutex       sync.RWMutex
	createItemArgsForCall []struct {
		arg1 context.Context
		arg2 *models.PurchaseOrderItem
	}
	createItemReturns struct {
		result1 error
	}
	createItemReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteStub        func(context.Context, uuid.UUID, uuid.UUID) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteItemStub        func(context.Context, uuid.UUID, uuid.UUID) error
	deleteItemMutex       sync.RWMutex
	deleteItemArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	deleteItemReturns struct {
		result1 error
	}
	deleteItemReturnsOnCall map[int]struct {
		result1 error
	}
	GetByIDStub        func(context.Context, uuid.UUID, uuid.UUID) (*models.PurchaseOrder, error)
	getByIDMutex       sync.RWMutex
	getByIDArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	getByIDReturns struct {
		result1 *models.PurchaseOrder
		result2 error
	}
	getByIDReturnsOnCall map[int]struct {
		result1 *models.PurchaseOrder
		result2 error
	}
	GetByPONumberStub        func(context.Context, uuid.UUID, string) (*models.PurchaseOrder, error)
	getByPONumberMutex       sync.RWMutex
	getByPONumberArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}
	getByPONumberReturns struct {
		result1 *models.PurchaseOrder
		result2 error
	}
	getByPONumberReturnsOnCall map[int]struct {
		result1 *models.PurchaseOrder
		result2 error
	}
	GetItemStub        func(context.Context, uuid.UUID, uuid.UUID) (*models.PurchaseOrderItem, error)
	getItemMutex       sync.RWMutex
	getItemArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	getItemReturns struct {
		result1 *models.PurchaseOrderItem
		result2 error
	}
	getItemReturnsOnCall map[int]struct {
		result1 *models.PurchaseOrderItem
		result2 error
	}
	ListByClientStub        func(context.Context, uuid.UUID, int, int) ([]*models.PurchaseOrder, error)
	listByClientMutex       sync.RWMutex
	listByClientArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}
	listByClientReturns struct {
		result1 []*models.PurchaseOrder
		result2 error
	}
	listByClientReturnsOnCall map[int]struct {
		result1 []*models.PurchaseOrder
		result2 error
	}
	ListByStatusStub        func(context.Context, uuid.UUID, models.PurchaseOrderStatus, int, int) ([]*models.PurchaseOrder, error)
	listByStatusMutex       sync.RWMutex
	listByStatusArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 models.PurchaseOrderStatus
		arg4 int
		arg5 int
	}
	listByStatusReturns struct {
		result1 []*models.PurchaseOrder
		result2 error
	}
	listByStatusReturnsOnCall map[int]struct {
		result1 []*models.PurchaseOrder
		result2 error
	}
	ListBySupplierStub        func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]*models.PurchaseOrder, error)
	listBySupplierMutex       sync.RWMutex
	listBySupplierArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
		arg5 int
	}
	listBySupplierReturns struct {
		result1 []*models.PurchaseOrder
		result2 error
	}
	listBySupplierReturnsOnCall map[int]struct {
		result1 []*models.PurchaseOrder
		result2 error
	}
	ListItemsByPOStub        func(context.Context, uuid.UUID, uuid.UUID) ([]*models.PurchaseOrderItem, error)
	listItemsByPOMutex       sync.RWMutex
	listItemsByPOArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	listItemsByPOReturns struct {
		result1 []*models.PurchaseOrderItem
		result2 error
	}
	listItemsByPOReturnsOnCall map[int]struct {
		result1 []*models.PurchaseOrderItem
		result2 error
	}
	ReceiveItemStub        func(context.Context, uuid.UUID, uuid.UUID, int) error
	receiveItemMutex       sync.RWMutex
	receiveItemArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
	}
	receiveItemReturns struct {
		result1 error
	}
	receiveItemReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateStub        func(context.Context, *models.PurchaseOrder) error
	updateMutex       sync.RWMutex
	updateArgsForCall []struct {
		arg1 context.Context
		arg2 *models.PurchaseOrder
	}
	updateReturns struct {
		result1 error
	}
	updateReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateItemStub        func(context.Context, *models.PurchaseOrderItem) error
	updateItemMutex       sync.RWMutex
	updateItemArgsForCall []struct {
		arg1 context.Context
		arg2 *models.PurchaseOrderItem
	}
	updateItemReturns struct {
		result1 error
	}
	updateItemReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePurchaseOrderRepository) Create(arg1 context.Context, arg2 *models.PurchaseOrder) error {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 context.Context
		arg2 *models.PurchaseOrder
	}{arg1, arg2})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePurchaseOrderRepository) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakePurchaseOrderRepository) CreateCalls(stub func(context.Context, *models.PurchaseOrder) error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakePurchaseOrderRepository) CreateArgsForCall(i int) (context.Context, *models.PurchaseOrder) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePurchaseOrderRepository) CreateReturns(result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderRepository) CreateReturnsOnCall(i int, result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderRepository) CreateItem(arg1 context.Context, arg2 *models.PurchaseOrderItem) error {
	fake.createItemMutex.Lock()
	ret, specificReturn := fake.createItemReturnsOnCall[len(fake.createItemArgsForCall)]
	fake.createItemArgsForCall = append(fake.createItemArgsForCall, struct {
		arg1 context.Context
		arg2 *models.PurchaseOrderItem
	}{arg1, arg2})
	stub := fake.CreateItemStub
	fakeReturns := fake.createItemReturns
	fake.recordInvocation("CreateItem", []interface{}{arg1, arg2})
	fake.createItemMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePurchaseOrderRepository) CreateItemCallCount() int {
	fake.createItemMutex.RLock()
	defer fake.createItemMutex.RUnlock()
	return len(fake.createItemArgsForCall)
}

func (fake *FakePurchaseOrderRepository) CreateItemCalls(stub func(context.Context, *models.PurchaseOrderItem) error) {
	fake.createItemMutex.Lock()
	defer fake.createItemMutex.Unlock()
	fake.CreateItemStub = stub
}

func (fake *FakePurchaseOrderRepository) CreateItemArgsForCall(i int) (context.Context, *models.PurchaseOrderItem) {
	fake.createItemMutex.RLock()
	defer fake.createItemMutex.RUnlock()
	argsForCall := fake.createItemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePurchaseOrderRepository) CreateItemReturns(result1 error) {
	fake.createItemMutex.Lock()
	defer fake.createItemMutex.Unlock()
	fake.CreateItemStub = nil
	fake.createItemReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderRepository) CreateItemReturnsOnCall(i int, result1 error) {
	fake.createItemMutex.Lock()
	defer fake.createItemMutex.Unlock()
	fake.CreateItemStub = nil
	if fake.createItemReturnsOnCall == nil {
		fake.createItemReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createItemReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderRepository) Delete(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.DeleteStub
	fakeReturns := fake.deleteReturns
	fake.recordInvocation("Delete", []interface{}{arg1, arg2, arg3})
	fake.deleteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePurchaseOrderRepository) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakePurchaseOrderRepository) DeleteCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakePurchaseOrderRepository) DeleteArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePurchaseOrderRepository) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderRepository) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderRepository) DeleteItem(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.deleteItemMutex.Lock()
	ret, specificReturn := fake.deleteItemReturnsOnCall[len(fake.deleteItemArgsForCall)]
	fake.deleteItemArgsForCall = append(fake.deleteItemArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.DeleteItemStub
	fakeReturns := fake.deleteItemReturns
	fake.recordInvocation("DeleteItem", []interface{}{arg1, arg2, arg3})
	fake.deleteItemMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePurchaseOrderRepository) DeleteItemCallCount() int {
	fake.deleteItemMutex.RLock()
	defer fake.deleteItemMutex.RUnlock()
	return len(fake.deleteItemArgsForCall)
}

func (fake *FakePurchaseOrderRepository) DeleteItemCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.deleteItemMutex.Lock()
	defer fake.deleteItemMutex.Unlock()
	fake.DeleteItemStub = stub
}

func (fake *FakePurchaseOrderRepository) DeleteItemArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.deleteItemMutex.RLock()
	defer fake.deleteItemMutex.RUnlock()
	argsForCall := fake.deleteItemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePurchaseOrderRepository) DeleteItemReturns(result1 error) {
	fake.deleteItemMutex.Lock()
	defer fake.deleteItemMutex.Unlock()
	fake.DeleteItemStub = nil
	fake.deleteItemReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderRepository) DeleteItemReturnsOnCall(i int, result1 error) {
	fake.deleteItemMutex.Lock()
	defer fake.deleteItemMutex.Unlock()
	fake.DeleteItemStub = nil
	if fake.deleteItemReturnsOnCall == nil {
		fake.deleteItemReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteItemReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderRepository) GetByID(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (*models.PurchaseOrder, error) {
	fake.getByIDMutex.Lock()
	ret, specificReturn := fake.getByIDReturnsOnCall[len(fake.getByIDArgsForCall)]
	fake.getByIDArgsForCall = append(fake.getByIDArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.GetByIDStub
	fakeReturns := fake.getByIDReturns
	fake.recordInvocation("GetByID", []interface{}{arg1, arg2, arg3})
	fake.getByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePurchaseOrderRepository) GetByIDCallCount() int {
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	return len(fake.getByIDArgsForCall)
}

func (fake *FakePurchaseOrderRepository) GetByIDCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (*models.PurchaseOrder, error)) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = stub
}

func (fake *FakePurchaseOrderRepository) GetByIDArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	argsForCall := fake.getByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePurchaseOrderRepository) GetByIDReturns(result1 *models.PurchaseOrder, result2 error) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = nil
	fake.getByIDReturns = struct {
		result1 *models.PurchaseOrder
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderRepository) GetByIDReturnsOnCall(i int, result1 *models.PurchaseOrder, result2 error) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = nil
	if fake.getByIDReturnsOnCall == nil {
		fake.getByIDReturnsOnCall = make(map[int]struct {
			result1 *models.PurchaseOrder
			result2 error
		})
	}
	fake.getByIDReturnsOnCall[i] = struct {
		result1 *models.PurchaseOrder
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderRepository) GetByPONumber(arg1 context.Context, arg2 uuid.UUID, arg3 string) (*models.PurchaseOrder, error) {
	fake.getByPONumberMutex.Lock()
	ret, specificReturn := fake.getByPONumberReturnsOnCall[len(fake.getByPONumberArgsForCall)]
	fake.getByPONumberArgsForCall = append(fake.getByPONumberArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.GetByPONumberStub
	fakeReturns := fake.getByPONumberReturns
	fake.recordInvocation("GetByPONumber", []interface{}{arg1, arg2, arg3})
	fake.getByPONumberMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePurchaseOrderRepository) GetByPONumberCallCount() int {
	fake.getByPONumberMutex.RLock()
	defer fake.getByPONumberMutex.RUnlock()
	return len(fake.getByPONumberArgsForCall)
}

func (fake *FakePurchaseOrderRepository) GetByPONumberCalls(stub func(context.Context, uuid.UUID, string) (*models.PurchaseOrder, error)) {
	fake.getByPONumberMutex.Lock()
	defer fake.getByPONumberMutex.Unlock()
	fake.GetByPONumberStub = stub
}

func (fake *FakePurchaseOrderRepository) GetByPONumberArgsForCall(i int) (context.Context, uuid.UUID, string) {
	fake.getByPONumberMutex.RLock()
	defer fake.getByPONumberMutex.RUnlock()
	argsForCall := fake.getByPONumberArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePurchaseOrderRepository) GetByPONumberReturns(result1 *models.PurchaseOrder, result2 error) {
	fake.getByPONumberMutex.Lock()
	defer fake.getByPONumberMutex.Unlock()
	fake.GetByPONumberStub = nil
	fake.getByPONumberReturns = struct {
		result1 *models.PurchaseOrder
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderRepository) GetByPONumberReturnsOnCall(i int, result1 *models.PurchaseOrder, result2 error) {
	fake.getByPONumberMutex.Lock()
	defer fake.getByPONumberMutex.Unlock()
	fake.GetByPONumberStub = nil
	if fake.getByPONumberReturnsOnCall == nil {
		fake.getByPONumberReturnsOnCall = make(map[int]struct {
			result1 *models.PurchaseOrder
			result2 error
		})
	}
	fake.getByPONumberReturnsOnCall[i] = struct {
		result1 *models.PurchaseOrder
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderRepository) GetItem(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (*models.PurchaseOrderItem, error) {
	fake.getItemMutex.Lock()
	ret, specificReturn := fake.getItemReturnsOnCall[len(fake.getItemArgsForCall)]
	fake.getItemArgsForCall = append(fake.getItemArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.GetItemStub
	fakeReturns := fake.getItemReturns
	fake.recordInvocation("GetItem", []interface{}{arg1, arg2, arg3})
	fake.getItemMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePurchaseOrderRepository) GetItemCallCount() int {
	fake.getItemMutex.RLock()
	defer fake.getItemMutex.RUnlock()
	return len(fake.getItemArgsForCall)
}

func (fake *FakePurchaseOrderRepository) GetItemCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (*models.PurchaseOrderItem, error)) {
	fake.getItemMutex.Lock()
	defer fake.getItemMutex.Unlock()
	fake.GetItemStub = stub
}

func (fake *FakePurchaseOrderRepository) GetItemArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.getItemMutex.RLock()
	defer fake.getItemMutex.RUnlock()
	argsForCall := fake.getItemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePurchaseOrderRepository) GetItemReturns(result1 *models.PurchaseOrderItem, result2 error) {
	fake.getItemMutex.Lock()
	defer fake.getItemMutex.Unlock()
	fake.GetItemStub = nil
	fake.getItemReturns = struct {
		result1 *models.PurchaseOrderItem
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderRepository) GetItemReturnsOnCall(i int, result1 *models.PurchaseOrderItem, result2 error) {
	fake.getItemMutex.Lock()
	defer fake.getItemMutex.Unlock()
	fake.GetItemStub = nil
	if fake.getItemReturnsOnCall == nil {
		fake.getItemReturnsOnCall = make(map[int]struct {
			result1 *models.PurchaseOrderItem
			result2 error
		})
	}
	fake.getItemReturnsOnCall[i] = struct {
		result1 *models.PurchaseOrderItem
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderRepository) ListByClient(arg1 context.Context, arg2 uuid.UUID, arg3 int, arg4 int) ([]*models.PurchaseOrder, error) {
	fake.listByClientMutex.Lock()
	ret, specificReturn := fake.listByClientReturnsOnCall[len(fake.listByClientArgsForCall)]
	fake.listByClientArgsForCall = append(fake.listByClientArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListByClientStub
	fakeReturns := fake.listByClientReturns
	fake.recordInvocation("ListByClient", []interface{}{arg1, arg2, arg3, arg4})
	fake.listByClientMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePurchaseOrderRepository) ListByClientCallCount() int {
	fake.listByClientMutex.RLock()
	defer fake.listByClientMutex.RUnlock()
	return len(fake.listByClientArgsForCall)
}

func (fake *FakePurchaseOrderRepository) ListByClientCalls(stub func(context.Context, uuid.UUID, int, int) ([]*models.PurchaseOrder, error)) {
	fake.listByClientMutex.Lock()
	defer fake.listByClientMutex.Unlock()
	fake.ListByClientStub = stub
}

func (fake *FakePurchaseOrderRepository) ListByClientArgsForCall(i int) (context.Context, uuid.UUID, int, int) {
	fake.listByClientMutex.RLock()
	defer fake.listByClientMutex.RUnlock()
	argsForCall := fake.listByClientArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakePurchaseOrderRepository) ListByClientReturns(result1 []*models.PurchaseOrder, result2 error) {
	fake.listByClientMutex.Lock()
	defer fake.listByClientMutex.Unlock()
	fake.ListByClientStub = nil
	fake.listByClientReturns = struct {
		result1 []*models.PurchaseOrder
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderRepository) ListByClientReturnsOnCall(i int, result1 []*models.PurchaseOrder, result2 error) {
	fake.listByClientMutex.Lock()
	defer fake.listByClientMutex.Unlock()
	fake.ListByClientStub = nil
	if fake.listByClientReturnsOnCall == nil {
		fake.listByClientReturnsOnCall = make(map[int]struct {
			result1 []*models.PurchaseOrder
			result2 error
		})
	}
	fake.listByClientReturnsOnCall[i] = struct {
		result1 []*models.PurchaseOrder
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderRepository) ListByStatus(arg1 context.Context, arg2 uuid.UUID, arg3 models.PurchaseOrderStatus, arg4 int, arg5 int) ([]*models.PurchaseOrder, error) {
	fake.listByStatusMutex.Lock()
	ret, specificReturn := fake.listByStatusReturnsOnCall[len(fake.listByStatusArgsForCall)]
	fake.listByStatusArgsForCall = append(fake.listByStatusArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 models.PurchaseOrderStatus
		arg4 int
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ListByStatusStub
	fakeReturns := fake.listByStatusReturns
	fake.recordInvocation("ListByStatus", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.listByStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePurchaseOrderRepository) ListByStatusCallCount() int {
	fake.listByStatusMutex.RLock()
	defer fake.listByStatusMutex.RUnlock()
	return len(fake.listByStatusArgsForCall)
}

func (fake *FakePurchaseOrderRepository) ListByStatusCalls(stub func(context.Context, uuid.UUID, models.PurchaseOrderStatus, int, int) ([]*models.PurchaseOrder, error)) {
	fake.listByStatusMutex.Lock()
	defer fake.listByStatusMutex.Unlock()
	fake.ListByStatusStub = stub
}

func (fake *FakePurchaseOrderRepository) ListByStatusArgsForCall(i int) (context.Context, uuid.UUID, models.PurchaseOrderStatus, int, int) {
	fake.listByStatusMutex.RLock()
	defer fake.listByStatusMutex.RUnlock()
	argsForCall := fake.listByStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakePurchaseOrderRepository) ListByStatusReturns(result1 []*models.PurchaseOrder, result2 error) {
	fake.listByStatusMutex.Lock()
	defer fake.listByStatusMutex.Unlock()
	fake.ListByStatusStub = nil
	fake.listByStatusReturns = struct {
		result1 []*models.PurchaseOrder
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderRepository) ListByStatusReturnsOnCall(i int, result1 []*models.PurchaseOrder, result2 error) {
	fake.listByStatusMutex.Lock()
	defer fake.listByStatusMutex.Unlock()
	fake.ListByStatusStub = nil
	if fake.listByStatusReturnsOnCall == nil {
		fake.listByStatusReturnsOnCall = make(map[int]struct {
			result1 []*models.PurchaseOrder
			result2 error
		})
	}
	fake.listByStatusReturnsOnCall[i] = struct {
		result1 []*models.PurchaseOrder
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderRepository) ListBySupplier(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 int, arg5 int) ([]*models.PurchaseOrder, error) {
	fake.listBySupplierMutex.Lock()
	ret, specificReturn := fake.listBySupplierReturnsOnCall[len(fake.listBySupplierArgsForCall)]
	fake.listBySupplierArgsForCall = append(fake.listBySupplierArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ListBySupplierStub
	fakeReturns := fake.listBySupplierReturns
	fake.recordInvocation("ListBySupplier", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.listBySupplierMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePurchaseOrderRepository) ListBySupplierCallCount() int {
	fake.listBySupplierMutex.RLock()
	defer fake.listBySupplierMutex.RUnlock()
	return len(fake.listBySupplierArgsForCall)
}

func (fake *FakePurchaseOrderRepository) ListBySupplierCalls(stub func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]*models.PurchaseOrder, error)) {
	fake.listBySupplierMutex.Lock()
	defer fake.listBySupplierMutex.Unlock()
	fake.ListBySupplierStub = stub
}

func (fake *FakePurchaseOrderRepository) ListBySupplierArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, int, int) {
	fake.listBySupplierMutex.RLock()
	defer fake.listBySupplierMutex.RUnlock()
	argsForCall := fake.listBySupplierArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakePurchaseOrderRepository) ListBySupplierReturns(result1 []*models.PurchaseOrder, result2 error) {
	fake.listBySupplierMutex.Lock()
	defer fake.listBySupplierMutex.Unlock()
	fake.ListBySupplierStub = nil
	fake.listBySupplierReturns = struct {
		result1 []*models.PurchaseOrder
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderRepository) ListBySupplierReturnsOnCall(i int, result1 []*models.PurchaseOrder, result2 error) {
	fake.listBySupplierMutex.Lock()
	defer fake.listBySupplierMutex.Unlock()
	fake.ListBySupplierStub = nil
	if fake.listBySupplierReturnsOnCall == nil {
		fake.listBySupplierReturnsOnCall = make(map[int]struct {
			result1 []*models.PurchaseOrder
			result2 error
		})
	}
	fake.listBySupplierReturnsOnCall[i] = struct {
		result1 []*models.PurchaseOrder
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderRepository) ListItemsByPO(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) ([]*models.PurchaseOrderItem, error) {
	fake.listItemsByPOMutex.Lock()
	ret, specificReturn := fake.listItemsByPOReturnsOnCall[len(fake.listItemsByPOArgsForCall)]
	fake.listItemsByPOArgsForCall = append(fake.listItemsByPOArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.ListItemsByPOStub
	fakeReturns := fake.listItemsByPOReturns
	fake.recordInvocation("ListItemsByPO", []interface{}{arg1, arg2, arg3})
	fake.listItemsByPOMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePurchaseOrderRepository) ListItemsByPOCallCount() int {
	fake.listItemsByPOMutex.RLock()
	defer fake.listItemsByPOMutex.RUnlock()
	return len(fake.listItemsByPOArgsForCall)
}

func (fake *FakePurchaseOrderRepository) ListItemsByPOCalls(stub func(context.Context, uuid.UUID, uuid.UUID) ([]*models.PurchaseOrderItem, error)) {
	fake.listItemsByPOMutex.Lock()
	defer fake.listItemsByPOMutex.Unlock()
	fake.ListItemsByPOStub = stub
}

func (fake *FakePurchaseOrderRepository) ListItemsByPOArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.listItemsByPOMutex.RLock()
	defer fake.listItemsByPOMutex.RUnlock()
	argsForCall := fake.listItemsByPOArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakePurchaseOrderRepository) ListItemsByPOReturns(result1 []*models.PurchaseOrderItem, result2 error) {
	fake.listItemsByPOMutex.Lock()
	defer fake.listItemsByPOMutex.Unlock()
	fake.ListItemsByPOStub = nil
	fake.listItemsByPOReturns = struct {
		result1 []*models.PurchaseOrderItem
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderRepository) ListItemsByPOReturnsOnCall(i int, result1 []*models.PurchaseOrderItem, result2 error) {
	fake.listItemsByPOMutex.Lock()
	defer fake.listItemsByPOMutex.Unlock()
	fake.ListItemsByPOStub = nil
	if fake.listItemsByPOReturnsOnCall == nil {
		fake.listItemsByPOReturnsOnCall = make(map[int]struct {
			result1 []*models.PurchaseOrderItem
			result2 error
		})
	}
	fake.listItemsByPOReturnsOnCall[i] = struct {
		result1 []*models.PurchaseOrderItem
		result2 error
	}{result1, result2}
}

func (fake *FakePurchaseOrderRepository) ReceiveItem(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 int) error {
	fake.receiveItemMutex.Lock()
	ret, specificReturn := fake.receiveItemReturnsOnCall[len(fake.receiveItemArgsForCall)]
	fake.receiveItemArgsForCall = append(fake.receiveItemArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.ReceiveItemStub
	fakeReturns := fake.receiveItemReturns
	fake.recordInvocation("ReceiveItem", []interface{}{arg1, arg2, arg3, arg4})
	fake.receiveItemMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePurchaseOrderRepository) ReceiveItemCallCount() int {
	fake.receiveItemMutex.RLock()
	defer fake.receiveItemMutex.RUnlock()
	return len(fake.receiveItemArgsForCall)
}

func (fake *FakePurchaseOrderRepository) ReceiveItemCalls(stub func(context.Context, uuid.UUID, uuid.UUID, int) error) {
	fake.receiveItemMutex.Lock()
	defer fake.receiveItemMutex.Unlock()
	fake.ReceiveItemStub = stub
}

func (fake *FakePurchaseOrderRepository) ReceiveItemArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, int) {
	fake.receiveItemMutex.RLock()
	defer fake.receiveItemMutex.RUnlock()
	argsForCall := fake.receiveItemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakePurchaseOrderRepository) ReceiveItemReturns(result1 error) {
	fake.receiveItemMutex.Lock()
	defer fake.receiveItemMutex.Unlock()
	fake.ReceiveItemStub = nil
	fake.receiveItemReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderRepository) ReceiveItemReturnsOnCall(i int, result1 error) {
	fake.receiveItemMutex.Lock()
	defer fake.receiveItemMutex.Unlock()
	fake.ReceiveItemStub = nil
	if fake.receiveItemReturnsOnCall == nil {
		fake.receiveItemReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.receiveItemReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderRepository) Update(arg1 context.Context, arg2 *models.PurchaseOrder) error {
	fake.updateMutex.Lock()
	ret, specificReturn := fake.updateReturnsOnCall[len(fake.updateArgsForCall)]
	fake.updateArgsForCall = append(fake.updateArgsForCall, struct {
		arg1 context.Context
		arg2 *models.PurchaseOrder
	}{arg1, arg2})
	stub := fake.UpdateStub
	fakeReturns := fake.updateReturns
	fake.recordInvocation("Update", []interface{}{arg1, arg2})
	fake.updateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePurchaseOrderRepository) UpdateCallCount() int {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return len(fake.updateArgsForCall)
}

func (fake *FakePurchaseOrderRepository) UpdateCalls(stub func(context.Context, *models.PurchaseOrder) error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = stub
}

func (fake *FakePurchaseOrderRepository) UpdateArgsForCall(i int) (context.Context, *models.PurchaseOrder) {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	argsForCall := fake.updateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePurchaseOrderRepository) UpdateReturns(result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	fake.updateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderRepository) UpdateReturnsOnCall(i int, result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	if fake.updateReturnsOnCall == nil {
		fake.updateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderRepository) UpdateItem(arg1 context.Context, arg2 *models.PurchaseOrderItem) error {
	fake.updateItemMutex.Lock()
	ret, specificReturn := fake.updateItemReturnsOnCall[len(fake.updateItemArgsForCall)]
	fake.updateItemArgsForCall = append(fake.updateItemArgsForCall, struct {
		arg1 context.Context
		arg2 *models.PurchaseOrderItem
	}{arg1, arg2})
	stub := fake.UpdateItemStub
	fakeReturns := fake.updateItemReturns
	fake.recordInvocation("UpdateItem", []interface{}{arg1, arg2})
	fake.updateItemMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakePurchaseOrderRepository) UpdateItemCallCount() int {
	fake.updateItemMutex.RLock()
	defer fake.updateItemMutex.RUnlock()
	return len(fake.updateItemArgsForCall)
}

func (fake *FakePurchaseOrderRepository) UpdateItemCalls(stub func(context.Context, *models.PurchaseOrderItem) error) {
	fake.updateItemMutex.Lock()
	defer fake.updateItemMutex.Unlock()
	fake.UpdateItemStub = stub
}

func (fake *FakePurchaseOrderRepository) UpdateItemArgsForCall(i int) (context.Context, *models.PurchaseOrderItem) {
	fake.updateItemMutex.RLock()
	defer fake.updateItemMutex.RUnlock()
	argsForCall := fake.updateItemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakePurchaseOrderRepository) UpdateItemReturns(result1 error) {
	fake.updateItemMutex.Lock()
	defer fake.updateItemMutex.Unlock()
	fake.UpdateItemStub = nil
	fake.updateItemReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderRepository) UpdateItemReturnsOnCall(i int, result1 error) {
	fake.updateItemMutex.Lock()
	defer fake.updateItemMutex.Unlock()
	fake.UpdateItemStub = nil
	if fake.updateItemReturnsOnCall == nil {
		fake.updateItemReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateItemReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakePurchaseOrderRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePurchaseOrderRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repositories.PurchaseOrderRepository = new(FakePurchaseOrderRepository)
