// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/yourorg/shoppilot/app/repositories"
	"github.com/yourorg/shoppilot/internal/models"
)

type FakeProductRepository struct {
	CreateStub        func(context.Context, *models.Product) error
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 context.Context
		arg2 *models.Product
	}
	createReturns struct {
		result1 error
	}
	createReturnsOnCall map[int]struct {
		result1 error
	}
	CreateVariantStub        func(context.Context, *models.ProductVariant) error
	createVariantMutex       sync.RWMutex
	createVariantArgsForCall []struct {
		arg1 context.Context
		arg2 *models.ProductVariant
	}
	createVariantReturns struct {
		result1 error
	}
	createVariantReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteStub        func(context.Context, uuid.UUID, uuid.UUID) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteVariantStub        func(context.Context, uuid.UUID, uuid.UUID) error
	deleteVariantMutex       sync.RWMutex
	deleteVariantArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	deleteVariantReturns struct {
		result1 error
	}
	deleteVariantReturnsOnCall map[int]struct {
		result1 error
	}
	GetByCodeStub        func(context.Context, uuid.UUID, string) (*models.Product, error)
	getByCodeMutex       sync.RWMutex
	getByCodeArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}
	getByCodeReturns struct {
		result1 *models.Product
		result2 error
	}
	getByCodeReturnsOnCall map[int]struct {
		result1 *models.Product
		result2 error
	}
	GetByIDStub        func(context.Context, uuid.UUID, uuid.UUID) (*models.Product, error)
	getByIDMutex       sync.RWMutex
	getByIDArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	getByIDReturns struct {
		result1 *models.Product
		result2 error
	}
	getByIDReturnsOnCall map[int]struct {
		result1 *models.Product
		result2 error
	}
	GetDefaultVariantStub        func(context.Context, uuid.UUID, uuid.UUID) (*models.ProductVariant, error)
	getDefaultVariantMutex       sync.RWMutex
	getDefaultVariantArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	getDefaultVariantReturns struct {
		result1 *models.ProductVariant
		result2 error
	}
	getDefaultVariantReturnsOnCall map[int]struct {
		result1 *models.ProductVariant
		result2 error
	}
	GetVariantByIDStub        func(context.Context, uuid.UUID, uuid.UUID) (*models.ProductVariant, error)
	getVariantByIDMutex       sync.RWMutex
	getVariantByIDArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	getVariantByIDReturns struct {
		result1 *models.ProductVariant
		result2 error
	}
	getVariantByIDReturnsOnCall map[int]struct {
		result1 *models.ProductVariant
		result2 error
	}
	GetVariantBySKUStub        func(context.Context, uuid.UUID, string) (*models.ProductVariant, error)
	getVariantBySKUMutex       sync.RWMutex
	getVariantBySKUArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}
	getVariantBySKUReturns struct {
		result1 *models.ProductVariant
		result2 error
	}
	getVariantBySKUReturnsOnCall map[int]struct {
		result1 *models.ProductVariant
		result2 error
	}
	ListByClientStub        func(context.Context, uuid.UUID, int, int) ([]*models.Product, error)
	listByClientMutex       sync.RWMutex
	listByClientArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}
	listByClientReturns struct {
		result1 []*models.Product
		result2 error
	}
	listByClientReturnsOnCall map[int]struct {
		result1 []*models.Product
		result2 error
	}
	ListByShopStub        func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]*models.Product, error)
	listByShopMutex       sync.RWMutex
	listByShopArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
		arg5 int
	}
	listByShopReturns struct {
		result1 []*models.Product
		result2 error
	}
	listByShopReturnsOnCall map[int]struct {
		result1 []*models.Product
		result2 error
	}
	ListVariantsByProductStub        func(context.Context, uuid.UUID, uuid.UUID) ([]*models.ProductVariant, error)
	listVariantsByProductMutex       sync.RWMutex
	listVariantsByProductArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	listVariantsByProductReturns struct {
		result1 []*models.ProductVariant
		result2 error
	}
	listVariantsByProductReturnsOnCall map[int]struct {
		result1 []*models.ProductVariant
		result2 error
	}
	SearchStub        func(context.Context, uuid.UUID, string, int, int) ([]*models.Product, error)
	searchMutex       sync.RWMutex
	searchArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
		arg4 int
		arg5 int
	}
	searchReturns struct {
		result1 []*models.Product
		result2 error
	}
	searchReturnsOnCall map[int]struct {
		result1 []*models.Product
		result2 error
	}
	UpdateStub        func(context.Context, *models.Product) error
	updateMutex       sync.RWMutex
	updateArgsForCall []struct {
		arg1 context.Context
		arg2 *models.Product
	}
	updateReturns struct {
		result1 error
	}
	updateReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateInventoryStub        func(context.Context, uuid.UUID, uuid.UUID, int) error
	updateInventoryMutex       sync.RWMutex
	updateInventoryArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
	}
	updateInventoryReturns struct {
		result1 error
	}
	updateInventoryReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateVariantStub        func(context.Context, *models.ProductVariant) error
	updateVariantMutex       sync.RWMutex
	updateVariantArgsForCall []struct {
		arg1 context.Context
		arg2 *models.ProductVariant
	}
	updateVariantReturns struct {
		result1 error
	}
	updateVariantReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProductRepository) Create(arg1 context.Context, arg2 *models.Product) error {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 context.Context
		arg2 *models.Product
	}{arg1, arg2})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProductRepository) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeProductRepository) CreateCalls(stub func(context.Context, *models.Product) error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeProductRepository) CreateArgsForCall(i int) (context.Context, *models.Product) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeProductRepository) CreateReturns(result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductRepository) CreateReturnsOnCall(i int, result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductRepository) CreateVariant(arg1 context.Context, arg2 *models.ProductVariant) error {
	fake.createVariantMutex.Lock()
	ret, specificReturn := fake.createVariantReturnsOnCall[len(fake.createVariantArgsForCall)]
	fake.createVariantArgsForCall = append(fake.createVariantArgsForCall, struct {
		arg1 context.Context
		arg2 *models.ProductVariant
	}{arg1, arg2})
	stub := fake.CreateVariantStub
	fakeReturns := fake.createVariantReturns
	fake.recordInvocation("CreateVariant", []interface{}{arg1, arg2})
	fake.createVariantMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProductRepository) CreateVariantCallCount() int {
	fake.createVariantMutex.RLock()
	defer fake.createVariantMutex.RUnlock()
	return len(fake.createVariantArgsForCall)
}

func (fake *FakeProductRepository) CreateVariantCalls(stub func(context.Context, *models.ProductVariant) error) {
	fake.createVariantMutex.Lock()
	defer fake.createVariantMutex.Unlock()
	fake.CreateVariantStub = stub
}

func (fake *FakeProductRepository) CreateVariantArgsForCall(i int) (context.Context, *models.ProductVariant) {
	fake.createVariantMutex.RLock()
	defer fake.createVariantMutex.RUnlock()
	argsForCall := fake.createVariantArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeProductRepository) CreateVariantReturns(result1 error) {
	fake.createVariantMutex.Lock()
	defer fake.createVariantMutex.Unlock()
	fake.CreateVariantStub = nil
	fake.createVariantReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductRepository) CreateVariantReturnsOnCall(i int, result1 error) {
	fake.createVariantMutex.Lock()
	defer fake.createVariantMutex.Unlock()
	fake.CreateVariantStub = nil
	if fake.createVariantReturnsOnCall == nil {
		fake.createVariantReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createVariantReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductRepository) Delete(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.DeleteStub
	fakeReturns := fake.deleteReturns
	fake.recordInvocation("Delete", []interface{}{arg1, arg2, arg3})
	fake.deleteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProductRepository) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeProductRepository) DeleteCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakeProductRepository) DeleteArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProductRepository) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductRepository) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductRepository) DeleteVariant(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.deleteVariantMutex.Lock()
	ret, specificReturn := fake.deleteVariantReturnsOnCall[len(fake.deleteVariantArgsForCall)]
	fake.deleteVariantArgsForCall = append(fake.deleteVariantArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.DeleteVariantStub
	fakeReturns := fake.deleteVariantReturns
	fake.recordInvocation("DeleteVariant", []interface{}{arg1, arg2, arg3})
	fake.deleteVariantMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProductRepository) DeleteVariantCallCount() int {
	fake.deleteVariantMutex.RLock()
	defer fake.deleteVariantMutex.RUnlock()
	return len(fake.deleteVariantArgsForCall)
}

func (fake *FakeProductRepository) DeleteVariantCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.deleteVariantMutex.Lock()
	defer fake.deleteVariantMutex.Unlock()
	fake.DeleteVariantStub = stub
}

func (fake *FakeProductRepository) DeleteVariantArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.deleteVariantMutex.RLock()
	defer fake.deleteVariantMutex.RUnlock()
	argsForCall := fake.deleteVariantArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProductRepository) DeleteVariantReturns(result1 error) {
	fake.deleteVariantMutex.Lock()
	defer fake.deleteVariantMutex.Unlock()
	fake.DeleteVariantStub = nil
	fake.deleteVariantReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductRepository) DeleteVariantReturnsOnCall(i int, result1 error) {
	fake.deleteVariantMutex.Lock()
	defer fake.deleteVariantMutex.Unlock()
	fake.DeleteVariantStub = nil
	if fake.deleteVariantReturnsOnCall == nil {
		fake.deleteVariantReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteVariantReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductRepository) GetByCode(arg1 context.Context, arg2 uuid.UUID, arg3 string) (*models.Product, error) {
	fake.getByCodeMutex.Lock()
	ret, specificReturn := fake.getByCodeReturnsOnCall[len(fake.getByCodeArgsForCall)]
	fake.getByCodeArgsForCall = append(fake.getByCodeArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.GetByCodeStub
	fakeReturns := fake.getByCodeReturns
	fake.recordInvocation("GetByCode", []interface{}{arg1, arg2, arg3})
	fake.getByCodeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProductRepository) GetByCodeCallCount() int {
	fake.getByCodeMutex.RLock()
	defer fake.getByCodeMutex.RUnlock()
	return len(fake.getByCodeArgsForCall)
}

func (fake *FakeProductRepository) GetByCodeCalls(stub func(context.Context, uuid.UUID, string) (*models.Product, error)) {
	fake.getByCodeMutex.Lock()
	defer fake.getByCodeMutex.Unlock()
	fake.GetByCodeStub = stub
}

func (fake *FakeProductRepository) GetByCodeArgsForCall(i int) (context.Context, uuid.UUID, string) {
	fake.getByCodeMutex.RLock()
	defer fake.getByCodeMutex.RUnlock()
	argsForCall := fake.getByCodeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProductRepository) GetByCodeReturns(result1 *models.Product, result2 error) {
	fake.getByCodeMutex.Lock()
	defer fake.getByCodeMutex.Unlock()
	fake.GetByCodeStub = nil
	fake.getByCodeReturns = struct {
		result1 *models.Product
		result2 error
	}{result1, result2}
}

func (fake *FakeProductRepository) GetByCodeReturnsOnCall(i int, result1 *models.Product, result2 error) {
	fake.getByCodeMutex.Lock()
	defer fake.getByCodeMutex.Unlock()
	fake.GetByCodeStub = nil
	if fake.getByCodeReturnsOnCall == nil {
		fake.getByCodeReturnsOnCall = make(map[int]struct {
			result1 *models.Product
			result2 error
		})
	}
	fake.getByCodeReturnsOnCall[i] = struct {
		result1 *models.Product
		result2 error
	}{result1, result2}
}

func (fake *FakeProductRepository) GetByID(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (*models.Product, error) {
	fake.getByIDMutex.Lock()
	ret, specificReturn := fake.getByIDReturnsOnCall[len(fake.getByIDArgsForCall)]
	fake.getByIDArgsForCall = append(fake.getByIDArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.GetByIDStub
	fakeReturns := fake.getByIDReturns
	fake.recordInvocation("GetByID", []interface{}{arg1, arg2, arg3})
	fake.getByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProductRepository) GetByIDCallCount() int {
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	return len(fake.getByIDArgsForCall)
}

func (fake *FakeProductRepository) GetByIDCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (*models.Product, error)) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = stub
}

func (fake *FakeProductRepository) GetByIDArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	argsForCall := fake.getByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProductRepository) GetByIDReturns(result1 *models.Product, result2 error) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = nil
	fake.getByIDReturns = struct {
		result1 *models.Product
		result2 error
	}{result1, result2}
}

func (fake *FakeProductRepository) GetByIDReturnsOnCall(i int, result1 *models.Product, result2 error) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = nil
	if fake.getByIDReturnsOnCall == nil {
		fake.getByIDReturnsOnCall = make(map[int]struct {
			result1 *models.Product
			result2 error
		})
	}
	fake.getByIDReturnsOnCall[i] = struct {
		result1 *models.Product
		result2 error
	}{result1, result2}
}

func (fake *FakeProductRepository) GetDefaultVariant(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (*models.ProductVariant, error) {
	fake.getDefaultVariantMutex.Lock()
	ret, specificReturn := fake.getDefaultVariantReturnsOnCall[len(fake.getDefaultVariantArgsForCall)]
	fake.getDefaultVariantArgsForCall = append(fake.getDefaultVariantArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.GetDefaultVariantStub
	fakeReturns := fake.getDefaultVariantReturns
	fake.recordInvocation("GetDefaultVariant", []interface{}{arg1, arg2, arg3})
	fake.getDefaultVariantMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProductRepository) GetDefaultVariantCallCount() int {
	fake.getDefaultVariantMutex.RLock()
	defer fake.getDefaultVariantMutex.RUnlock()
	return len(fake.getDefaultVariantArgsForCall)
}

func (fake *FakeProductRepository) GetDefaultVariantCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (*models.ProductVariant, error)) {
	fake.getDefaultVariantMutex.Lock()
	defer fake.getDefaultVariantMutex.Unlock()
	fake.GetDefaultVariantStub = stub
}

func (fake *FakeProductRepository) GetDefaultVariantArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.getDefaultVariantMutex.RLock()
	defer fake.getDefaultVariantMutex.RUnlock()
	argsForCall := fake.getDefaultVariantArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProductRepository) GetDefaultVariantReturns(result1 *models.ProductVariant, result2 error) {
	fake.getDefaultVariantMutex.Lock()
	defer fake.getDefaultVariantMutex.Unlock()
	fake.GetDefaultVariantStub = nil
	fake.getDefaultVariantReturns = struct {
		result1 *models.ProductVariant
		result2 error
	}{result1, result2}
}

func (fake *FakeProductRepository) GetDefaultVariantReturnsOnCall(i int, result1 *models.ProductVariant, result2 error) {
	fake.getDefaultVariantMutex.Lock()
	defer fake.getDefaultVariantMutex.Unlock()
	fake.GetDefaultVariantStub = nil
	if fake.getDefaultVariantReturnsOnCall == nil {
		fake.getDefaultVariantReturnsOnCall = make(map[int]struct {
			result1 *models.ProductVariant
			result2 error
		})
	}
	fake.getDefaultVariantReturnsOnCall[i] = struct {
		result1 *models.ProductVariant
		result2 error
	}{result1, result2}
}

func (fake *FakeProductRepository) GetVariantByID(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (*models.ProductVariant, error) {
	fake.getVariantByIDMutex.Lock()
	ret, specificReturn := fake.getVariantByIDReturnsOnCall[len(fake.getVariantByIDArgsForCall)]
	fake.getVariantByIDArgsForCall = append(fake.getVariantByIDArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.GetVariantByIDStub
	fakeReturns := fake.getVariantByIDReturns
	fake.recordInvocation("GetVariantByID", []interface{}{arg1, arg2, arg3})
	fake.getVariantByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProductRepository) GetVariantByIDCallCount() int {
	fake.getVariantByIDMutex.RLock()
	defer fake.getVariantByIDMutex.RUnlock()
	return len(fake.getVariantByIDArgsForCall)
}

func (fake *FakeProductRepository) GetVariantByIDCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (*models.ProductVariant, error)) {
	fake.getVariantByIDMutex.Lock()
	defer fake.getVariantByIDMutex.Unlock()
	fake.GetVariantByIDStub = stub
}

func (fake *FakeProductRepository) GetVariantByIDArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.getVariantByIDMutex.RLock()
	defer fake.getVariantByIDMutex.RUnlock()
	argsForCall := fake.getVariantByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProductRepository) GetVariantByIDReturns(result1 *models.ProductVariant, result2 error) {
	fake.getVariantByIDMutex.Lock()
	defer fake.getVariantByIDMutex.Unlock()
	fake.GetVariantByIDStub = nil
	fake.getVariantByIDReturns = struct {
		result1 *models.ProductVariant
		result2 error
	}{result1, result2}
}

func (fake *FakeProductRepository) GetVariantByIDReturnsOnCall(i int, result1 *models.ProductVariant, result2 error) {
	fake.getVariantByIDMutex.Lock()
	defer fake.getVariantByIDMutex.Unlock()
	fake.GetVariantByIDStub = nil
	if fake.getVariantByIDReturnsOnCall == nil {
		fake.getVariantByIDReturnsOnCall = make(map[int]struct {
			result1 *models.ProductVariant
			result2 error
		})
	}
	fake.getVariantByIDReturnsOnCall[i] = struct {
		result1 *models.ProductVariant
		result2 error
	}{result1, result2}
}

func (fake *FakeProductRepository) GetVariantBySKU(arg1 context.Context, arg2 uuid.UUID, arg3 string) (*models.ProductVariant, error) {
	fake.getVariantBySKUMutex.Lock()
	ret, specificReturn := fake.getVariantBySKUReturnsOnCall[len(fake.getVariantBySKUArgsForCall)]
	fake.getVariantBySKUArgsForCall = append(fake.getVariantBySKUArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.GetVariantBySKUStub
	fakeReturns := fake.getVariantBySKUReturns
	fake.recordInvocation("GetVariantBySKU", []interface{}{arg1, arg2, arg3})
	fake.getVariantBySKUMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProductRepository) GetVariantBySKUCallCount() int {
	fake.getVariantBySKUMutex.RLock()
	defer fake.getVariantBySKUMutex.RUnlock()
	return len(fake.getVariantBySKUArgsForCall)
}

func (fake *FakeProductRepository) GetVariantBySKUCalls(stub func(context.Context, uuid.UUID, string) (*models.ProductVariant, error)) {
	fake.getVariantBySKUMutex.Lock()
	defer fake.getVariantBySKUMutex.Unlock()
	fake.GetVariantBySKUStub = stub
}

func (fake *FakeProductRepository) GetVariantBySKUArgsForCall(i int) (context.Context, uuid.UUID, string) {
	fake.getVariantBySKUMutex.RLock()
	defer fake.getVariantBySKUMutex.RUnlock()
	argsForCall := fake.getVariantBySKUArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProductRepository) GetVariantBySKUReturns(result1 *models.ProductVariant, result2 error) {
	fake.getVariantBySKUMutex.Lock()
	defer fake.getVariantBySKUMutex.Unlock()
	fake.GetVariantBySKUStub = nil
	fake.getVariantBySKUReturns = struct {
		result1 *models.ProductVariant
		result2 error
	}{result1, result2}
}

func (fake *FakeProductRepository) GetVariantBySKUReturnsOnCall(i int, result1 *models.ProductVariant, result2 error) {
	fake.getVariantBySKUMutex.Lock()
	defer fake.getVariantBySKUMutex.Unlock()
	fake.GetVariantBySKUStub = nil
	if fake.getVariantBySKUReturnsOnCall == nil {
		fake.getVariantBySKUReturnsOnCall = make(map[int]struct {
			result1 *models.ProductVariant
			result2 error
		})
	}
	fake.getVariantBySKUReturnsOnCall[i] = struct {
		result1 *models.ProductVariant
		result2 error
	}{result1, result2}
}

func (fake *FakeProductRepository) ListByClient(arg1 context.Context, arg2 uuid.UUID, arg3 int, arg4 int) ([]*models.Product, error) {
	fake.listByClientMutex.Lock()
	ret, specificReturn := fake.listByClientReturnsOnCall[len(fake.listByClientArgsForCall)]
	fake.listByClientArgsForCall = append(fake.listByClientArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListByClientStub
	fakeReturns := fake.listByClientReturns
	fake.recordInvocation("ListByClient", []interface{}{arg1, arg2, arg3, arg4})
	fake.listByClientMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProductRepository) ListByClientCallCount() int {
	fake.listByClientMutex.RLock()
	defer fake.listByClientMutex.RUnlock()
	return len(fake.listByClientArgsForCall)
}

func (fake *FakeProductRepository) ListByClientCalls(stub func(context.Context, uuid.UUID, int, int) ([]*models.Product, error)) {
	fake.listByClientMutex.Lock()
	defer fake.listByClientMutex.Unlock()
	fake.ListByClientStub = stub
}

func (fake *FakeProductRepository) ListByClientArgsForCall(i int) (context.Context, uuid.UUID, int, int) {
	fake.listByClientMutex.RLock()
	defer fake.listByClientMutex.RUnlock()
	argsForCall := fake.listByClientArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeProductRepository) ListByClientReturns(result1 []*models.Product, result2 error) {
	fake.listByClientMutex.Lock()
	defer fake.listByClientMutex.Unlock()
	fake.ListByClientStub = nil
	fake.listByClientReturns = struct {
		result1 []*models.Product
		result2 error
	}{result1, result2}
}

func (fake *FakeProductRepository) ListByClientReturnsOnCall(i int, result1 []*models.Product, result2 error) {
	fake.listByClientMutex.Lock()
	defer fake.listByClientMutex.Unlock()
	fake.ListByClientStub = nil
	if fake.listByClientReturnsOnCall == nil {
		fake.listByClientReturnsOnCall = make(map[int]struct {
			result1 []*models.Product
			result2 error
		})
	}
	fake.listByClientReturnsOnCall[i] = struct {
		result1 []*models.Product
		result2 error
	}{result1, result2}
}

func (fake *FakeProductRepository) ListByShop(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 int, arg5 int) ([]*models.Product, error) {
	fake.listByShopMutex.Lock()
	ret, specificReturn := fake.listByShopReturnsOnCall[len(fake.listByShopArgsForCall)]
	fake.listByShopArgsForCall = append(fake.listByShopArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ListByShopStub
	fakeReturns := fake.listByShopReturns
	fake.recordInvocation("ListByShop", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.listByShopMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProductRepository) ListByShopCallCount() int {
	fake.listByShopMutex.RLock()
	defer fake.listByShopMutex.RUnlock()
	return len(fake.listByShopArgsForCall)
}

func (fake *FakeProductRepository) ListByShopCalls(stub func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]*models.Product, error)) {
	fake.listByShopMutex.Lock()
	defer fake.listByShopMutex.Unlock()
	fake.ListByShopStub = stub
}

func (fake *FakeProductRepository) ListByShopArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, int, int) {
	fake.listByShopMutex.RLock()
	defer fake.listByShopMutex.RUnlock()
	argsForCall := fake.listByShopArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeProductRepository) ListByShopReturns(result1 []*models.Product, result2 error) {
	fake.listByShopMutex.Lock()
	defer fake.listByShopMutex.Unlock()
	fake.ListByShopStub = nil
	fake.listByShopReturns = struct {
		result1 []*models.Product
		result2 error
	}{result1, result2}
}

func (fake *FakeProductRepository) ListByShopReturnsOnCall(i int, result1 []*models.Product, result2 error) {
	fake.listByShopMutex.Lock()
	defer fake.listByShopMutex.Unlock()
	fake.ListByShopStub = nil
	if fake.listByShopReturnsOnCall == nil {
		fake.listByShopReturnsOnCall = make(map[int]struct {
			result1 []*models.Product
			result2 error
		})
	}
	fake.listByShopReturnsOnCall[i] = struct {
		result1 []*models.Product
		result2 error
	}{result1, result2}
}

func (fake *FakeProductRepository) ListVariantsByProduct(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) ([]*models.ProductVariant, error) {
	fake.listVariantsByProductMutex.Lock()
	ret, specificReturn := fake.listVariantsByProductReturnsOnCall[len(fake.listVariantsByProductArgsForCall)]
	fake.listVariantsByProductArgsForCall = append(fake.listVariantsByProductArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.ListVariantsByProductStub
	fakeReturns := fake.listVariantsByProductReturns
	fake.recordInvocation("ListVariantsByProduct", []interface{}{arg1, arg2, arg3})
	fake.listVariantsByProductMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProductRepository) ListVariantsByProductCallCount() int {
	fake.listVariantsByProductMutex.RLock()
	defer fake.listVariantsByProductMutex.RUnlock()
	return len(fake.listVariantsByProductArgsForCall)
}

func (fake *FakeProductRepository) ListVariantsByProductCalls(stub func(context.Context, uuid.UUID, uuid.UUID) ([]*models.ProductVariant, error)) {
	fake.listVariantsByProductMutex.Lock()
	defer fake.listVariantsByProductMutex.Unlock()
	fake.ListVariantsByProductStub = stub
}

func (fake *FakeProductRepository) ListVariantsByProductArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.listVariantsByProductMutex.RLock()
	defer fake.listVariantsByProductMutex.RUnlock()
	argsForCall := fake.listVariantsByProductArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProductRepository) ListVariantsByProductReturns(result1 []*models.ProductVariant, result2 error) {
	fake.listVariantsByProductMutex.Lock()
	defer fake.listVariantsByProductMutex.Unlock()
	fake.ListVariantsByProductStub = nil
	fake.listVariantsByProductReturns = struct {
		result1 []*models.ProductVariant
		result2 error
	}{result1, result2}
}

func (fake *FakeProductRepository) ListVariantsByProductReturnsOnCall(i int, result1 []*models.ProductVariant, result2 error) {
	fake.listVariantsByProductMutex.Lock()
	defer fake.listVariantsByProductMutex.Unlock()
	fake.ListVariantsByProductStub = nil
	if fake.listVariantsByProductReturnsOnCall == nil {
		fake.listVariantsByProductReturnsOnCall = make(map[int]struct {
			result1 []*models.ProductVariant
			result2 error
		})
	}
	fake.listVariantsByProductReturnsOnCall[i] = struct {
		result1 []*models.ProductVariant
		result2 error
	}{result1, result2}
}

func (fake *FakeProductRepository) Search(arg1 context.Context, arg2 uuid.UUID, arg3 string, arg4 int, arg5 int) ([]*models.Product, error) {
	fake.searchMutex.Lock()
	ret, specificReturn := fake.searchReturnsOnCall[len(fake.searchArgsForCall)]
	fake.searchArgsForCall = append(fake.searchArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
		arg4 int
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.SearchStub
	fakeReturns := fake.searchReturns
	fake.recordInvocation("Search", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.searchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProductRepository) SearchCallCount() int {
	fake.searchMutex.RLock()
	defer fake.searchMutex.RUnlock()
	return len(fake.searchArgsForCall)
}

func (fake *FakeProductRepository) SearchCalls(stub func(context.Context, uuid.UUID, string, int, int) ([]*models.Product, error)) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = stub
}

func (fake *FakeProductRepository) SearchArgsForCall(i int) (context.Context, uuid.UUID, string, int, int) {
	fake.searchMutex.RLock()
	defer fake.searchMutex.RUnlock()
	argsForCall := fake.searchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeProductRepository) SearchReturns(result1 []*models.Product, result2 error) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = nil
	fake.searchReturns = struct {
		result1 []*models.Product
		result2 error
	}{result1, result2}
}

func (fake *FakeProductRepository) SearchReturnsOnCall(i int, result1 []*models.Product, result2 error) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = nil
	if fake.searchReturnsOnCall == nil {
		fake.searchReturnsOnCall = make(map[int]struct {
			result1 []*models.Product
			result2 error
		})
	}
	fake.searchReturnsOnCall[i] = struct {
		result1 []*models.Product
		result2 error
	}{result1, result2}
}

func (fake *FakeProductRepository) Update(arg1 context.Context, arg2 *models.Product) error {
	fake.updateMutex.Lock()
	ret, specificReturn := fake.updateReturnsOnCall[len(fake.updateArgsForCall)]
	fake.updateArgsForCall = append(fake.updateArgsForCall, struct {
		arg1 context.Context
		arg2 *models.Product
	}{arg1, arg2})
	stub := fake.UpdateStub
	fakeReturns := fake.updateReturns
	fake.recordInvocation("Update", []interface{}{arg1, arg2})
	fake.updateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProductRepository) UpdateCallCount() int {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return len(fake.updateArgsForCall)
}

func (fake *FakeProductRepository) UpdateCalls(stub func(context.Context, *models.Product) error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = stub
}

func (fake *FakeProductRepository) UpdateArgsForCall(i int) (context.Context, *models.Product) {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	argsForCall := fake.updateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeProductRepository) UpdateReturns(result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	fake.updateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductRepository) UpdateReturnsOnCall(i int, result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	if fake.updateReturnsOnCall == nil {
		fake.updateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductRepository) UpdateInventory(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 int) error {
	fake.updateInventoryMutex.Lock()
	ret, specificReturn := fake.updateInventoryReturnsOnCall[len(fake.updateInventoryArgsForCall)]
	fake.updateInventoryArgsForCall = append(fake.updateInventoryArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.UpdateInventoryStub
	fakeReturns := fake.updateInventoryReturns
	fake.recordInvocation("UpdateInventory", []interface{}{arg1, arg2, arg3, arg4})
	fake.updateInventoryMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProductRepository) UpdateInventoryCallCount() int {
	fake.updateInventoryMutex.RLock()
	defer fake.updateInventoryMutex.RUnlock()
	return len(fake.updateInventoryArgsForCall)
}

func (fake *FakeProductRepository) UpdateInventoryCalls(stub func(context.Context, uuid.UUID, uuid.UUID, int) error) {
	fake.updateInventoryMutex.Lock()
	defer fake.updateInventoryMutex.Unlock()
	fake.UpdateInventoryStub = stub
}

func (fake *FakeProductRepository) UpdateInventoryArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, int) {
	fake.updateInventoryMutex.RLock()
	defer fake.updateInventoryMutex.RUnlock()
	argsForCall := fake.updateInventoryArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeProductRepository) UpdateInventoryReturns(result1 error) {
	fake.updateInventoryMutex.Lock()
	defer fake.updateInventoryMutex.Unlock()
	fake.UpdateInventoryStub = nil
	fake.updateInventoryReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductRepository) UpdateInventoryReturnsOnCall(i int, result1 error) {
	fake.updateInventoryMutex.Lock()
	defer fake.updateInventoryMutex.Unlock()
	fake.UpdateInventoryStub = nil
	if fake.updateInventoryReturnsOnCall == nil {
		fake.updateInventoryReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateInventoryReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductRepository) UpdateVariant(arg1 context.Context, arg2 *models.ProductVariant) error {
	fake.updateVariantMutex.Lock()
	ret, specificReturn := fake.updateVariantReturnsOnCall[len(fake.updateVariantArgsForCall)]
	fake.updateVariantArgsForCall = append(fake.updateVariantArgsForCall, struct {
		arg1 context.Context
		arg2 *models.ProductVariant
	}{arg1, arg2})
	stub := fake.UpdateVariantStub
	fakeReturns := fake.updateVariantReturns
	fake.recordInvocation("UpdateVariant", []interface{}{arg1, arg2})
	fake.updateVariantMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeProductRepository) UpdateVariantCallCount() int {
	fake.updateVariantMutex.RLock()
	defer fake.updateVariantMutex.RUnlock()
	return len(fake.updateVariantArgsForCall)
}

func (fake *FakeProductRepository) UpdateVariantCalls(stub func(context.Context, *models.ProductVariant) error) {
	fake.updateVariantMutex.Lock()
	defer fake.updateVariantMutex.Unlock()
	fake.UpdateVariantStub = stub
}

func (fake *FakeProductRepository) UpdateVariantArgsForCall(i int) (context.Context, *models.ProductVariant) {
	fake.updateVariantMutex.RLock()
	defer fake.updateVariantMutex.RUnlock()
	argsForCall := fake.updateVariantArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeProductRepository) UpdateVariantReturns(result1 error) {
	fake.updateVariantMutex.Lock()
	defer fake.updateVariantMutex.Unlock()
	fake.UpdateVariantStub = nil
	fake.updateVariantReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductRepository) UpdateVariantReturnsOnCall(i int, result1 error) {
	fake.updateVariantMutex.Lock()
	defer fake.updateVariantMutex.Unlock()
	fake.UpdateVariantStub = nil
	if fake.updateVariantReturnsOnCall == nil {
		fake.updateVariantReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateVariantReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProductRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProductRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repositories.ProductRepository = new(FakeProductRepository)
