// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/yourorg/shoppilot/app/repositories"
	"github.com/yourorg/shoppilot/internal/models"
)

type FakeCustomerRepository struct {
	CreateStub        func(context.Context, *models.Customer) error
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 context.Context
		arg2 *models.Customer
	}
	createReturns struct {
		result1 error
	}
	createReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteStub        func(context.Context, uuid.UUID, uuid.UUID) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	GetByCodeStub        func(context.Context, uuid.UUID, string) (*models.Customer, error)
	getByCodeMutex       sync.RWMutex
	getByCodeArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}
	getByCodeReturns struct {
		result1 *models.Customer
		result2 error
	}
	getByCodeReturnsOnCall map[int]struct {
		result1 *models.Customer
		result2 error
	}
	GetByEmailStub        func(context.Context, uuid.UUID, string) (*models.Customer, error)
	getByEmailMutex       sync.RWMutex
	getByEmailArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}
	getByEmailReturns struct {
		result1 *models.Customer
		result2 error
	}
	getByEmailReturnsOnCall map[int]struct {
		result1 *models.Customer
		result2 error
	}
	GetByIDStub        func(context.Context, uuid.UUID, uuid.UUID) (*models.Customer, error)
	getByIDMutex       sync.RWMutex
	getByIDArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	getByIDReturns struct {
		result1 *models.Customer
		result2 error
	}
	getByIDReturnsOnCall map[int]struct {
		result1 *models.Customer
		result2 error
	}
	ListByClientStub        func(context.Context, uuid.UUID, int, int) ([]*models.Customer, error)
	listByClientMutex       sync.RWMutex
	listByClientArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}
	listByClientReturns struct {
		result1 []*models.Customer
		result2 error
	}
	listByClientReturnsOnCall map[int]struct {
		result1 []*models.Customer
		result2 error
	}
	SearchStub        func(context.Context, uuid.UUID, string, int, int) ([]*models.Customer, error)
	searchMutex       sync.RWMutex
	searchArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
		arg4 int
		arg5 int
	}
	searchReturns struct {
		result1 []*models.Customer
		result2 error
	}
	searchReturnsOnCall map[int]struct {
		result1 []*models.Customer
		result2 error
	}
	UpdateStub        func(context.Context, *models.Customer) error
	updateMutex       sync.RWMutex
	updateArgsForCall []struct {
		arg1 context.Context
		arg2 *models.Customer
	}
	updateReturns struct {
		result1 error
	}
	updateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCustomerRepository) Create(arg1 context.Context, arg2 *models.Customer) error {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 context.Context
		arg2 *models.Customer
	}{arg1, arg2})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCustomerRepository) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeCustomerRepository) CreateCalls(stub func(context.Context, *models.Customer) error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeCustomerRepository) CreateArgsForCall(i int) (context.Context, *models.Customer) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCustomerRepository) CreateReturns(result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCustomerRepository) CreateReturnsOnCall(i int, result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCustomerRepository) Delete(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.DeleteStub
	fakeReturns := fake.deleteReturns
	fake.recordInvocation("Delete", []interface{}{arg1, arg2, arg3})
	fake.deleteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCustomerRepository) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeCustomerRepository) DeleteCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakeCustomerRepository) DeleteArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeCustomerRepository) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCustomerRepository) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCustomerRepository) GetByCode(arg1 context.Context, arg2 uuid.UUID, arg3 string) (*models.Customer, error) {
	fake.getByCodeMutex.Lock()
	ret, specificReturn := fake.getByCodeReturnsOnCall[len(fake.getByCodeArgsForCall)]
	fake.getByCodeArgsForCall = append(fake.getByCodeArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.GetByCodeStub
	fakeReturns := fake.getByCodeReturns
	fake.recordInvocation("GetByCode", []interface{}{arg1, arg2, arg3})
	fake.getByCodeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCustomerRepository) GetByCodeCallCount() int {
	fake.getByCodeMutex.RLock()
	defer fake.getByCodeMutex.RUnlock()
	return len(fake.getByCodeArgsForCall)
}

func (fake *FakeCustomerRepository) GetByCodeCalls(stub func(context.Context, uuid.UUID, string) (*models.Customer, error)) {
	fake.getByCodeMutex.Lock()
	defer fake.getByCodeMutex.Unlock()
	fake.GetByCodeStub = stub
}

func (fake *FakeCustomerRepository) GetByCodeArgsForCall(i int) (context.Context, uuid.UUID, string) {
	fake.getByCodeMutex.RLock()
	defer fake.getByCodeMutex.RUnlock()
	argsForCall := fake.getByCodeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeCustomerRepository) GetByCodeReturns(result1 *models.Customer, result2 error) {
	fake.getByCodeMutex.Lock()
	defer fake.getByCodeMutex.Unlock()
	fake.GetByCodeStub = nil
	fake.getByCodeReturns = struct {
		result1 *models.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerRepository) GetByCodeReturnsOnCall(i int, result1 *models.Customer, result2 error) {
	fake.getByCodeMutex.Lock()
	defer fake.getByCodeMutex.Unlock()
	fake.GetByCodeStub = nil
	if fake.getByCodeReturnsOnCall == nil {
		fake.getByCodeReturnsOnCall = make(map[int]struct {
			result1 *models.Customer
			result2 error
		})
	}
	fake.getByCodeReturnsOnCall[i] = struct {
		result1 *models.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerRepository) GetByEmail(arg1 context.Context, arg2 uuid.UUID, arg3 string) (*models.Customer, error) {
	fake.getByEmailMutex.Lock()
	ret, specificReturn := fake.getByEmailReturnsOnCall[len(fake.getByEmailArgsForCall)]
	fake.getByEmailArgsForCall = append(fake.getByEmailArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.GetByEmailStub
	fakeReturns := fake.getByEmailReturns
	fake.recordInvocation("GetByEmail", []interface{}{arg1, arg2, arg3})
	fake.getByEmailMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCustomerRepository) GetByEmailCallCount() int {
	fake.getByEmailMutex.RLock()
	defer fake.getByEmailMutex.RUnlock()
	return len(fake.getByEmailArgsForCall)
}

func (fake *FakeCustomerRepository) GetByEmailCalls(stub func(context.Context, uuid.UUID, string) (*models.Customer, error)) {
	fake.getByEmailMutex.Lock()
	defer fake.getByEmailMutex.Unlock()
	fake.GetByEmailStub = stub
}

func (fake *FakeCustomerRepository) GetByEmailArgsForCall(i int) (context.Context, uuid.UUID, string) {
	fake.getByEmailMutex.RLock()
	defer fake.getByEmailMutex.RUnlock()
	argsForCall := fake.getByEmailArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeCustomerRepository) GetByEmailReturns(result1 *models.Customer, result2 error) {
	fake.getByEmailMutex.Lock()
	defer fake.getByEmailMutex.Unlock()
	fake.GetByEmailStub = nil
	fake.getByEmailReturns = struct {
		result1 *models.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerRepository) GetByEmailReturnsOnCall(i int, result1 *models.Customer, result2 error) {
	fake.getByEmailMutex.Lock()
	defer fake.getByEmailMutex.Unlock()
	fake.GetByEmailStub = nil
	if fake.getByEmailReturnsOnCall == nil {
		fake.getByEmailReturnsOnCall = make(map[int]struct {
			result1 *models.Customer
			result2 error
		})
	}
	fake.getByEmailReturnsOnCall[i] = struct {
		result1 *models.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerRepository) GetByID(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (*models.Customer, error) {
	fake.getByIDMutex.Lock()
	ret, specificReturn := fake.getByIDReturnsOnCall[len(fake.getByIDArgsForCall)]
	fake.getByIDArgsForCall = append(fake.getByIDArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.GetByIDStub
	fakeReturns := fake.getByIDReturns
	fake.recordInvocation("GetByID", []interface{}{arg1, arg2, arg3})
	fake.getByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCustomerRepository) GetByIDCallCount() int {
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	return len(fake.getByIDArgsForCall)
}

func (fake *FakeCustomerRepository) GetByIDCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (*models.Customer, error)) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = stub
}

func (fake *FakeCustomerRepository) GetByIDArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	argsForCall := fake.getByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeCustomerRepository) GetByIDReturns(result1 *models.Customer, result2 error) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = nil
	fake.getByIDReturns = struct {
		result1 *models.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerRepository) GetByIDReturnsOnCall(i int, result1 *models.Customer, result2 error) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = nil
	if fake.getByIDReturnsOnCall == nil {
		fake.getByIDReturnsOnCall = make(map[int]struct {
			result1 *models.Customer
			result2 error
		})
	}
	fake.getByIDReturnsOnCall[i] = struct {
		result1 *models.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerRepository) ListByClient(arg1 context.Context, arg2 uuid.UUID, arg3 int, arg4 int) ([]*models.Customer, error) {
	fake.listByClientMutex.Lock()
	ret, specificReturn := fake.listByClientReturnsOnCall[len(fake.listByClientArgsForCall)]
	fake.listByClientArgsForCall = append(fake.listByClientArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListByClientStub
	fakeReturns := fake.listByClientReturns
	fake.recordInvocation("ListByClient", []interface{}{arg1, arg2, arg3, arg4})
	fake.listByClientMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCustomerRepository) ListByClientCallCount() int {
	fake.listByClientMutex.RLock()
	defer fake.listByClientMutex.RUnlock()
	return len(fake.listByClientArgsForCall)
}

func (fake *FakeCustomerRepository) ListByClientCalls(stub func(context.Context, uuid.UUID, int, int) ([]*models.Customer, error)) {
	fake.listByClientMutex.Lock()
	defer fake.listByClientMutex.Unlock()
	fake.ListByClientStub = stub
}

func (fake *FakeCustomerRepository) ListByClientArgsForCall(i int) (context.Context, uuid.UUID, int, int) {
	fake.listByClientMutex.RLock()
	defer fake.listByClientMutex.RUnlock()
	argsForCall := fake.listByClientArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeCustomerRepository) ListByClientReturns(result1 []*models.Customer, result2 error) {
	fake.listByClientMutex.Lock()
	defer fake.listByClientMutex.Unlock()
	fake.ListByClientStub = nil
	fake.listByClientReturns = struct {
		result1 []*models.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerRepository) ListByClientReturnsOnCall(i int, result1 []*models.Customer, result2 error) {
	fake.listByClientMutex.Lock()
	defer fake.listByClientMutex.Unlock()
	fake.ListByClientStub = nil
	if fake.listByClientReturnsOnCall == nil {
		fake.listByClientReturnsOnCall = make(map[int]struct {
			result1 []*models.Customer
			result2 error
		})
	}
	fake.listByClientReturnsOnCall[i] = struct {
		result1 []*models.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerRepository) Search(arg1 context.Context, arg2 uuid.UUID, arg3 string, arg4 int, arg5 int) ([]*models.Customer, error) {
	fake.searchMutex.Lock()
	ret, specificReturn := fake.searchReturnsOnCall[len(fake.searchArgsForCall)]
	fake.searchArgsForCall = append(fake.searchArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
		arg4 int
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.SearchStub
	fakeReturns := fake.searchReturns
	fake.recordInvocation("Search", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.searchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCustomerRepository) SearchCallCount() int {
	fake.searchMutex.RLock()
	defer fake.searchMutex.RUnlock()
	return len(fake.searchArgsForCall)
}

func (fake *FakeCustomerRepository) SearchCalls(stub func(context.Context, uuid.UUID, string, int, int) ([]*models.Customer, error)) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = stub
}

func (fake *FakeCustomerRepository) SearchArgsForCall(i int) (context.Context, uuid.UUID, string, int, int) {
	fake.searchMutex.RLock()
	defer fake.searchMutex.RUnlock()
	argsForCall := fake.searchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeCustomerRepository) SearchReturns(result1 []*models.Customer, result2 error) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = nil
	fake.searchReturns = struct {
		result1 []*models.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerRepository) SearchReturnsOnCall(i int, result1 []*models.Customer, result2 error) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = nil
	if fake.searchReturnsOnCall == nil {
		fake.searchReturnsOnCall = make(map[int]struct {
			result1 []*models.Customer
			result2 error
		})
	}
	fake.searchReturnsOnCall[i] = struct {
		result1 []*models.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerRepository) Update(arg1 context.Context, arg2 *models.Customer) error {
	fake.updateMutex.Lock()
	ret, specificReturn := fake.updateReturnsOnCall[len(fake.updateArgsForCall)]
	fake.updateArgsForCall = append(fake.updateArgsForCall, struct {
		arg1 context.Context
		arg2 *models.Customer
	}{arg1, arg2})
	stub := fake.UpdateStub
	fakeReturns := fake.updateReturns
	fake.recordInvocation("Update", []interface{}{arg1, arg2})
	fake.updateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCustomerRepository) UpdateCallCount() int {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return len(fake.updateArgsForCall)
}

func (fake *FakeCustomerRepository) UpdateCalls(stub func(context.Context, *models.Customer) error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = stub
}

func (fake *FakeCustomerRepository) UpdateArgsForCall(i int) (context.Context, *models.Customer) {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	argsForCall := fake.updateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCustomerRepository) UpdateReturns(result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	fake.updateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCustomerRepository) UpdateReturnsOnCall(i int, result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	if fake.updateReturnsOnCall == nil {
		fake.updateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCustomerRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCustomerRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repositories.CustomerRepository = new(FakeCustomerRepository)
