// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/yourorg/shoppilot/app/repositories"
	"github.com/yourorg/shoppilot/internal/models"
)

type FakeInventoryAlertRepository struct {
	CreateStub        func(context.Context, *models.InventoryAlert) error
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 context.Context
		arg2 *models.InventoryAlert
	}
	createReturns struct {
		result1 error
	}
	createReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteStub        func(context.Context, uuid.UUID, uuid.UUID) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	GetByIDStub        func(context.Context, uuid.UUID, uuid.UUID) (*models.InventoryAlert, error)
	getByIDMutex       sync.RWMutex
	getByIDArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	getByIDReturns struct {
		result1 *models.InventoryAlert
		result2 error
	}
	getByIDReturnsOnCall map[int]struct {
		result1 *models.InventoryAlert
		result2 error
	}
	GetByVariantStub        func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (*models.InventoryAlert, error)
	getByVariantMutex       sync.RWMutex
	getByVariantArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 uuid.UUID
	}
	getByVariantReturns struct {
		result1 *models.InventoryAlert
		result2 error
	}
	getByVariantReturnsOnCall map[int]struct {
		result1 *models.InventoryAlert
		result2 error
	}
	ListByShopStub        func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]*models.InventoryAlert, error)
	listByShopMutex       sync.RWMutex
	listByShopArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
		arg5 int
	}
	listByShopReturns struct {
		result1 []*models.InventoryAlert
		result2 error
	}
	listByShopReturnsOnCall map[int]struct {
		result1 []*models.InventoryAlert
		result2 error
	}
	ListTriggeredStub        func(context.Context, uuid.UUID) ([]*models.InventoryAlert, error)
	listTriggeredMutex       sync.RWMutex
	listTriggeredArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
	}
	listTriggeredReturns struct {
		result1 []*models.InventoryAlert
		result2 error
	}
	listTriggeredReturnsOnCall map[int]struct {
		result1 []*models.InventoryAlert
		result2 error
	}
	UpdateStub        func(context.Context, *models.InventoryAlert) error
	updateMutex       sync.RWMutex
	updateArgsForCall []struct {
		arg1 context.Context
		arg2 *models.InventoryAlert
	}
	updateReturns struct {
		result1 error
	}
	updateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeInventoryAlertRepository) Create(arg1 context.Context, arg2 *models.InventoryAlert) error {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 context.Context
		arg2 *models.InventoryAlert
	}{arg1, arg2})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeInventoryAlertRepository) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeInventoryAlertRepository) CreateCalls(stub func(context.Context, *models.InventoryAlert) error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeInventoryAlertRepository) CreateArgsForCall(i int) (context.Context, *models.InventoryAlert) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeInventoryAlertRepository) CreateReturns(result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeInventoryAlertRepository) CreateReturnsOnCall(i int, result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeInventoryAlertRepository) Delete(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.DeleteStub
	fakeReturns := fake.deleteReturns
	fake.recordInvocation("Delete", []interface{}{arg1, arg2, arg3})
	fake.deleteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeInventoryAlertRepository) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeInventoryAlertRepository) DeleteCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakeInventoryAlertRepository) DeleteArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeInventoryAlertRepository) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeInventoryAlertRepository) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeInventoryAlertRepository) GetByID(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (*models.InventoryAlert, error) {
	fake.getByIDMutex.Lock()
	ret, specificReturn := fake.getByIDReturnsOnCall[len(fake.getByIDArgsForCall)]
	fake.getByIDArgsForCall = append(fake.getByIDArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.GetByIDStub
	fakeReturns := fake.getByIDReturns
	fake.recordInvocation("GetByID", []interface{}{arg1, arg2, arg3})
	fake.getByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInventoryAlertRepository) GetByIDCallCount() int {
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	return len(fake.getByIDArgsForCall)
}

func (fake *FakeInventoryAlertRepository) GetByIDCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (*models.InventoryAlert, error)) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = stub
}

func (fake *FakeInventoryAlertRepository) GetByIDArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	argsForCall := fake.getByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeInventoryAlertRepository) GetByIDReturns(result1 *models.InventoryAlert, result2 error) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = nil
	fake.getByIDReturns = struct {
		result1 *models.InventoryAlert
		result2 error
	}{result1, result2}
}

func (fake *FakeInventoryAlertRepository) GetByIDReturnsOnCall(i int, result1 *models.InventoryAlert, result2 error) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = nil
	if fake.getByIDReturnsOnCall == nil {
		fake.getByIDReturnsOnCall = make(map[int]struct {
			result1 *models.InventoryAlert
			result2 error
		})
	}
	fake.getByIDReturnsOnCall[i] = struct {
		result1 *models.InventoryAlert
		result2 error
	}{result1, result2}
}

func (fake *FakeInventoryAlertRepository) GetByVariant(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 uuid.UUID) (*models.InventoryAlert, error) {
	fake.getByVariantMutex.Lock()
	ret, specificReturn := fake.getByVariantReturnsOnCall[len(fake.getByVariantArgsForCall)]
	fake.getByVariantArgsForCall = append(fake.getByVariantArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 uuid.UUID
	}{arg1, arg2, arg3, arg4})
	stub := fake.GetByVariantStub
	fakeReturns := fake.getByVariantReturns
	fake.recordInvocation("GetByVariant", []interface{}{arg1, arg2, arg3, arg4})
	fake.getByVariantMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInventoryAlertRepository) GetByVariantCallCount() int {
	fake.getByVariantMutex.RLock()
	defer fake.getByVariantMutex.RUnlock()
	return len(fake.getByVariantArgsForCall)
}

func (fake *FakeInventoryAlertRepository) GetByVariantCalls(stub func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (*models.InventoryAlert, error)) {
	fake.getByVariantMutex.Lock()
	defer fake.getByVariantMutex.Unlock()
	fake.GetByVariantStub = stub
}

func (fake *FakeInventoryAlertRepository) GetByVariantArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, uuid.UUID) {
	fake.getByVariantMutex.RLock()
	defer fake.getByVariantMutex.RUnlock()
	argsForCall := fake.getByVariantArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeInventoryAlertRepository) GetByVariantReturns(result1 *models.InventoryAlert, result2 error) {
	fake.getByVariantMutex.Lock()
	defer fake.getByVariantMutex.Unlock()
	fake.GetByVariantStub = nil
	fake.getByVariantReturns = struct {
		result1 *models.InventoryAlert
		result2 error
	}{result1, result2}
}

func (fake *FakeInventoryAlertRepository) GetByVariantReturnsOnCall(i int, result1 *models.InventoryAlert, result2 error) {
	fake.getByVariantMutex.Lock()
	defer fake.getByVariantMutex.Unlock()
	fake.GetByVariantStub = nil
	if fake.getByVariantReturnsOnCall == nil {
		fake.getByVariantReturnsOnCall = make(map[int]struct {
			result1 *models.InventoryAlert
			result2 error
		})
	}
	fake.getByVariantReturnsOnCall[i] = struct {
		result1 *models.InventoryAlert
		result2 error
	}{result1, result2}
}

func (fake *FakeInventoryAlertRepository) ListByShop(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 int, arg5 int) ([]*models.InventoryAlert, error) {
	fake.listByShopMutex.Lock()
	ret, specificReturn := fake.listByShopReturnsOnCall[len(fake.listByShopArgsForCall)]
	fake.listByShopArgsForCall = append(fake.listByShopArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ListByShopStub
	fakeReturns := fake.listByShopReturns
	fake.recordInvocation("ListByShop", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.listByShopMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInventoryAlertRepository) ListByShopCallCount() int {
	fake.listByShopMutex.RLock()
	defer fake.listByShopMutex.RUnlock()
	return len(fake.listByShopArgsForCall)
}

func (fake *FakeInventoryAlertRepository) ListByShopCalls(stub func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]*models.InventoryAlert, error)) {
	fake.listByShopMutex.Lock()
	defer fake.listByShopMutex.Unlock()
	fake.ListByShopStub = stub
}

func (fake *FakeInventoryAlertRepository) ListByShopArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, int, int) {
	fake.listByShopMutex.RLock()
	defer fake.listByShopMutex.RUnlock()
	argsForCall := fake.listByShopArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeInventoryAlertRepository) ListByShopReturns(result1 []*models.InventoryAlert, result2 error) {
	fake.listByShopMutex.Lock()
	defer fake.listByShopMutex.Unlock()
	fake.ListByShopStub = nil
	fake.listByShopReturns = struct {
		result1 []*models.InventoryAlert
		result2 error
	}{result1, result2}
}

func (fake *FakeInventoryAlertRepository) ListByShopReturnsOnCall(i int, result1 []*models.InventoryAlert, result2 error) {
	fake.listByShopMutex.Lock()
	defer fake.listByShopMutex.Unlock()
	fake.ListByShopStub = nil
	if fake.listByShopReturnsOnCall == nil {
		fake.listByShopReturnsOnCall = make(map[int]struct {
			result1 []*models.InventoryAlert
			result2 error
		})
	}
	fake.listByShopReturnsOnCall[i] = struct {
		result1 []*models.InventoryAlert
		result2 error
	}{result1, result2}
}

func (fake *FakeInventoryAlertRepository) ListTriggered(arg1 context.Context, arg2 uuid.UUID) ([]*models.InventoryAlert, error) {
	fake.listTriggeredMutex.Lock()
	ret, specificReturn := fake.listTriggeredReturnsOnCall[len(fake.listTriggeredArgsForCall)]
	fake.listTriggeredArgsForCall = append(fake.listTriggeredArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
	}{arg1, arg2})
	stub := fake.ListTriggeredStub
	fakeReturns := fake.listTriggeredReturns
	fake.recordInvocation("ListTriggered", []interface{}{arg1, arg2})
	fake.listTriggeredMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInventoryAlertRepository) ListTriggeredCallCount() int {
	fake.listTriggeredMutex.RLock()
	defer fake.listTriggeredMutex.RUnlock()
	return len(fake.listTriggeredArgsForCall)
}

func (fake *FakeInventoryAlertRepository) ListTriggeredCalls(stub func(context.Context, uuid.UUID) ([]*models.InventoryAlert, error)) {
	fake.listTriggeredMutex.Lock()
	defer fake.listTriggeredMutex.Unlock()
	fake.ListTriggeredStub = stub
}

func (fake *FakeInventoryAlertRepository) ListTriggeredArgsForCall(i int) (context.Context, uuid.UUID) {
	fake.listTriggeredMutex.RLock()
	defer fake.listTriggeredMutex.RUnlock()
	argsForCall := fake.listTriggeredArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeInventoryAlertRepository) ListTriggeredReturns(result1 []*models.InventoryAlert, result2 error) {
	fake.listTriggeredMutex.Lock()
	defer fake.listTriggeredMutex.Unlock()
	fake.ListTriggeredStub = nil
	fake.listTriggeredReturns = struct {
		result1 []*models.InventoryAlert
		result2 error
	}{result1, result2}
}

func (fake *FakeInventoryAlertRepository) ListTriggeredReturnsOnCall(i int, result1 []*models.InventoryAlert, result2 error) {
	fake.listTriggeredMutex.Lock()
	defer fake.listTriggeredMutex.Unlock()
	fake.ListTriggeredStub = nil
	if fake.listTriggeredReturnsOnCall == nil {
		fake.listTriggeredReturnsOnCall = make(map[int]struct {
			result1 []*models.InventoryAlert
			result2 error
		})
	}
	fake.listTriggeredReturnsOnCall[i] = struct {
		result1 []*models.InventoryAlert
		result2 error
	}{result1, result2}
}

func (fake *FakeInventoryAlertRepository) Update(arg1 context.Context, arg2 *models.InventoryAlert) error {
	fake.updateMutex.Lock()
	ret, specificReturn := fake.updateReturnsOnCall[len(fake.updateArgsForCall)]
	fake.updateArgsForCall = append(fake.updateArgsForCall, struct {
		arg1 context.Context
		arg2 *models.InventoryAlert
	}{arg1, arg2})
	stub := fake.UpdateStub
	fakeReturns := fake.updateReturns
	fake.recordInvocation("Update", []interface{}{arg1, arg2})
	fake.updateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeInventoryAlertRepository) UpdateCallCount() int {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return len(fake.updateArgsForCall)
}

func (fake *FakeInventoryAlertRepository) UpdateCalls(stub func(context.Context, *models.InventoryAlert) error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = stub
}

func (fake *FakeInventoryAlertRepository) UpdateArgsForCall(i int) (context.Context, *models.InventoryAlert) {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	argsForCall := fake.updateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeInventoryAlertRepository) UpdateReturns(result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	fake.updateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeInventoryAlertRepository) UpdateReturnsOnCall(i int, result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	if fake.updateReturnsOnCall == nil {
		fake.updateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeInventoryAlertRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeInventoryAlertRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repositories.InventoryAlertRepository = new(FakeInventoryAlertRepository)
