// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/yourorg/shoppilot/app/repositories"
	"github.com/yourorg/shoppilot/internal/models"
)

type FakeSalesOrderRepository struct {
	CreateStub        func(context.Context, *models.SalesOrder) error
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 context.Context
		arg2 *models.SalesOrder
	}
	createReturns struct {
		result1 error
	}
	createReturnsOnCall map[int]struct {
		result1 error
	}
	CreateItemStub        func(context.Context, *models.SalesOrderItem) error
	createItemMutex       sync.RWMutex
	createItemArgsForCall []struct {
		arg1 context.Context
		arg2 *models.SalesOrderItem
	}
	createItemReturns struct {
		result1 error
	}
	createItemReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteStub        func(context.Context, uuid.UUID, uuid.UUID) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteItemStub        func(context.Context, uuid.UUID, uuid.UUID) error
	deleteItemMutex       sync.RWMutex
	deleteItemArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	deleteItemReturns struct {
		result1 error
	}
	deleteItemReturnsOnCall map[int]struct {
		result1 error
	}
	FulfillItemStub        func(context.Context, uuid.UUID, uuid.UUID, int) error
	fulfillItemMutex       sync.RWMutex
	fulfillItemArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
	}
	fulfillItemReturns struct {
		result1 error
	}
	fulfillItemReturnsOnCall map[int]struct {
		result1 error
	}
	GetByIDStub        func(context.Context, uuid.UUID, uuid.UUID) (*models.SalesOrder, error)
	getByIDMutex       sync.RWMutex
	getByIDArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	getByIDReturns struct {
		result1 *models.SalesOrder
		result2 error
	}
	getByIDReturnsOnCall map[int]struct {
		result1 *models.SalesOrder
		result2 error
	}
	GetByOrderNumberStub        func(context.Context, uuid.UUID, string) (*models.SalesOrder, error)
	getByOrderNumberMutex       sync.RWMutex
	getByOrderNumberArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}
	getByOrderNumberReturns struct {
		result1 *models.SalesOrder
		result2 error
	}
	getByOrderNumberReturnsOnCall map[int]struct {
		result1 *models.SalesOrder
		result2 error
	}
	GetItemStub        func(context.Context, uuid.UUID, uuid.UUID) (*models.SalesOrderItem, error)
	getItemMutex       sync.RWMutex
	getItemArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	getItemReturns struct {
		result1 *models.SalesOrderItem
		result2 error
	}
	getItemReturnsOnCall map[int]struct {
		result1 *models.SalesOrderItem
		result2 error
	}
	ListByClientStub        func(context.Context, uuid.UUID, int, int) ([]*models.SalesOrder, error)
	listByClientMutex       sync.RWMutex
	listByClientArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}
	listByClientReturns struct {
		result1 []*models.SalesOrder
		result2 error
	}
	listByClientReturnsOnCall map[int]struct {
		result1 []*models.SalesOrder
		result2 error
	}
	ListByCustomerStub        func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]*models.SalesOrder, error)
	listByCustomerMutex       sync.RWMutex
	listByCustomerArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
		arg5 int
	}
	listByCustomerReturns struct {
		result1 []*models.SalesOrder
		result2 error
	}
	listByCustomerReturnsOnCall map[int]struct {
		result1 []*models.SalesOrder
		result2 error
	}
	ListByStatusStub        func(context.Context, uuid.UUID, models.SalesOrderStatus, int, int) ([]*models.SalesOrder, error)
	listByStatusMutex       sync.RWMutex
	listByStatusArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 models.SalesOrderStatus
		arg4 int
		arg5 int
	}
	listByStatusReturns struct {
		result1 []*models.SalesOrder
		result2 error
	}
	listByStatusReturnsOnCall map[int]struct {
		result1 []*models.SalesOrder
		result2 error
	}
	ListItemsBySOStub        func(context.Context, uuid.UUID, uuid.UUID) ([]*models.SalesOrderItem, error)
	listItemsBySOMutex       sync.RWMutex
	listItemsBySOArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	listItemsBySOReturns struct {
		result1 []*models.SalesOrderItem
		result2 error
	}
	listItemsBySOReturnsOnCall map[int]struct {
		result1 []*models.SalesOrderItem
		result2 error
	}
	UpdateStub        func(context.Context, *models.SalesOrder) error
	updateMutex       sync.RWMutex
	updateArgsForCall []struct {
		arg1 context.Context
		arg2 *models.SalesOrder
	}
	updateReturns struct {
		result1 error
	}
	updateReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateItemStub        func(context.Context, *models.SalesOrderItem) error
	updateItemMutex       sync.RWMutex
	updateItemArgsForCall []struct {
		arg1 context.Context
		arg2 *models.SalesOrderItem
	}
	updateItemReturns struct {
		result1 error
	}
	updateItemReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSalesOrderRepository) Create(arg1 context.Context, arg2 *models.SalesOrder) error {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 context.Context
		arg2 *models.SalesOrder
	}{arg1, arg2})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSalesOrderRepository) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeSalesOrderRepository) CreateCalls(stub func(context.Context, *models.SalesOrder) error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeSalesOrderRepository) CreateArgsForCall(i int) (context.Context, *models.SalesOrder) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSalesOrderRepository) CreateReturns(result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderRepository) CreateReturnsOnCall(i int, result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderRepository) CreateItem(arg1 context.Context, arg2 *models.SalesOrderItem) error {
	fake.createItemMutex.Lock()
	ret, specificReturn := fake.createItemReturnsOnCall[len(fake.createItemArgsForCall)]
	fake.createItemArgsForCall = append(fake.createItemArgsForCall, struct {
		arg1 context.Context
		arg2 *models.SalesOrderItem
	}{arg1, arg2})
	stub := fake.CreateItemStub
	fakeReturns := fake.createItemReturns
	fake.recordInvocation("CreateItem", []interface{}{arg1, arg2})
	fake.createItemMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSalesOrderRepository) CreateItemCallCount() int {
	fake.createItemMutex.RLock()
	defer fake.createItemMutex.RUnlock()
	return len(fake.createItemArgsForCall)
}

func (fake *FakeSalesOrderRepository) CreateItemCalls(stub func(context.Context, *models.SalesOrderItem) error) {
	fake.createItemMutex.Lock()
	defer fake.createItemMutex.Unlock()
	fake.CreateItemStub = stub
}

func (fake *FakeSalesOrderRepository) CreateItemArgsForCall(i int) (context.Context, *models.SalesOrderItem) {
	fake.createItemMutex.RLock()
	defer fake.createItemMutex.RUnlock()
	argsForCall := fake.createItemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSalesOrderRepository) CreateItemReturns(result1 error) {
	fake.createItemMutex.Lock()
	defer fake.createItemMutex.Unlock()
	fake.CreateItemStub = nil
	fake.createItemReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderRepository) CreateItemReturnsOnCall(i int, result1 error) {
	fake.createItemMutex.Lock()
	defer fake.createItemMutex.Unlock()
	fake.CreateItemStub = nil
	if fake.createItemReturnsOnCall == nil {
		fake.createItemReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createItemReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderRepository) Delete(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.DeleteStub
	fakeReturns := fake.deleteReturns
	fake.recordInvocation("Delete", []interface{}{arg1, arg2, arg3})
	fake.deleteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSalesOrderRepository) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeSalesOrderRepository) DeleteCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakeSalesOrderRepository) DeleteArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSalesOrderRepository) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderRepository) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderRepository) DeleteItem(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.deleteItemMutex.Lock()
	ret, specificReturn := fake.deleteItemReturnsOnCall[len(fake.deleteItemArgsForCall)]
	fake.deleteItemArgsForCall = append(fake.deleteItemArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.DeleteItemStub
	fakeReturns := fake.deleteItemReturns
	fake.recordInvocation("DeleteItem", []interface{}{arg1, arg2, arg3})
	fake.deleteItemMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSalesOrderRepository) DeleteItemCallCount() int {
	fake.deleteItemMutex.RLock()
	defer fake.deleteItemMutex.RUnlock()
	return len(fake.deleteItemArgsForCall)
}

func (fake *FakeSalesOrderRepository) DeleteItemCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.deleteItemMutex.Lock()
	defer fake.deleteItemMutex.Unlock()
	fake.DeleteItemStub = stub
}

func (fake *FakeSalesOrderRepository) DeleteItemArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.deleteItemMutex.RLock()
	defer fake.deleteItemMutex.RUnlock()
	argsForCall := fake.deleteItemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSalesOrderRepository) DeleteItemReturns(result1 error) {
	fake.deleteItemMutex.Lock()
	defer fake.deleteItemMutex.Unlock()
	fake.DeleteItemStub = nil
	fake.deleteItemReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderRepository) DeleteItemReturnsOnCall(i int, result1 error) {
	fake.deleteItemMutex.Lock()
	defer fake.deleteItemMutex.Unlock()
	fake.DeleteItemStub = nil
	if fake.deleteItemReturnsOnCall == nil {
		fake.deleteItemReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteItemReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderRepository) FulfillItem(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 int) error {
	fake.fulfillItemMutex.Lock()
	ret, specificReturn := fake.fulfillItemReturnsOnCall[len(fake.fulfillItemArgsForCall)]
	fake.fulfillItemArgsForCall = append(fake.fulfillItemArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.FulfillItemStub
	fakeReturns := fake.fulfillItemReturns
	fake.recordInvocation("FulfillItem", []interface{}{arg1, arg2, arg3, arg4})
	fake.fulfillItemMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSalesOrderRepository) FulfillItemCallCount() int {
	fake.fulfillItemMutex.RLock()
	defer fake.fulfillItemMutex.RUnlock()
	return len(fake.fulfillItemArgsForCall)
}

func (fake *FakeSalesOrderRepository) FulfillItemCalls(stub func(context.Context, uuid.UUID, uuid.UUID, int) error) {
	fake.fulfillItemMutex.Lock()
	defer fake.fulfillItemMutex.Unlock()
	fake.FulfillItemStub = stub
}

func (fake *FakeSalesOrderRepository) FulfillItemArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, int) {
	fake.fulfillItemMutex.RLock()
	defer fake.fulfillItemMutex.RUnlock()
	argsForCall := fake.fulfillItemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeSalesOrderRepository) FulfillItemReturns(result1 error) {
	fake.fulfillItemMutex.Lock()
	defer fake.fulfillItemMutex.Unlock()
	fake.FulfillItemStub = nil
	fake.fulfillItemReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderRepository) FulfillItemReturnsOnCall(i int, result1 error) {
	fake.fulfillItemMutex.Lock()
	defer fake.fulfillItemMutex.Unlock()
	fake.FulfillItemStub = nil
	if fake.fulfillItemReturnsOnCall == nil {
		fake.fulfillItemReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.fulfillItemReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderRepository) GetByID(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (*models.SalesOrder, error) {
	fake.getByIDMutex.Lock()
	ret, specificReturn := fake.getByIDReturnsOnCall[len(fake.getByIDArgsForCall)]
	fake.getByIDArgsForCall = append(fake.getByIDArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.GetByIDStub
	fakeReturns := fake.getByIDReturns
	fake.recordInvocation("GetByID", []interface{}{arg1, arg2, arg3})
	fake.getByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSalesOrderRepository) GetByIDCallCount() int {
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	return len(fake.getByIDArgsForCall)
}

func (fake *FakeSalesOrderRepository) GetByIDCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (*models.SalesOrder, error)) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = stub
}

func (fake *FakeSalesOrderRepository) GetByIDArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	argsForCall := fake.getByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSalesOrderRepository) GetByIDReturns(result1 *models.SalesOrder, result2 error) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = nil
	fake.getByIDReturns = struct {
		result1 *models.SalesOrder
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderRepository) GetByIDReturnsOnCall(i int, result1 *models.SalesOrder, result2 error) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = nil
	if fake.getByIDReturnsOnCall == nil {
		fake.getByIDReturnsOnCall = make(map[int]struct {
			result1 *models.SalesOrder
			result2 error
		})
	}
	fake.getByIDReturnsOnCall[i] = struct {
		result1 *models.SalesOrder
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderRepository) GetByOrderNumber(arg1 context.Context, arg2 uuid.UUID, arg3 string) (*models.SalesOrder, error) {
	fake.getByOrderNumberMutex.Lock()
	ret, specificReturn := fake.getByOrderNumberReturnsOnCall[len(fake.getByOrderNumberArgsForCall)]
	fake.getByOrderNumberArgsForCall = append(fake.getByOrderNumberArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.GetByOrderNumberStub
	fakeReturns := fake.getByOrderNumberReturns
	fake.recordInvocation("GetByOrderNumber", []interface{}{arg1, arg2, arg3})
	fake.getByOrderNumberMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSalesOrderRepository) GetByOrderNumberCallCount() int {
	fake.getByOrderNumberMutex.RLock()
	defer fake.getByOrderNumberMutex.RUnlock()
	return len(fake.getByOrderNumberArgsForCall)
}

func (fake *FakeSalesOrderRepository) GetByOrderNumberCalls(stub func(context.Context, uuid.UUID, string) (*models.SalesOrder, error)) {
	fake.getByOrderNumberMutex.Lock()
	defer fake.getByOrderNumberMutex.Unlock()
	fake.GetByOrderNumberStub = stub
}

func (fake *FakeSalesOrderRepository) GetByOrderNumberArgsForCall(i int) (context.Context, uuid.UUID, string) {
	fake.getByOrderNumberMutex.RLock()
	defer fake.getByOrderNumberMutex.RUnlock()
	argsForCall := fake.getByOrderNumberArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSalesOrderRepository) GetByOrderNumberReturns(result1 *models.SalesOrder, result2 error) {
	fake.getByOrderNumberMutex.Lock()
	defer fake.getByOrderNumberMutex.Unlock()
	fake.GetByOrderNumberStub = nil
	fake.getByOrderNumberReturns = struct {
		result1 *models.SalesOrder
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderRepository) GetByOrderNumberReturnsOnCall(i int, result1 *models.SalesOrder, result2 error) {
	fake.getByOrderNumberMutex.Lock()
	defer fake.getByOrderNumberMutex.Unlock()
	fake.GetByOrderNumberStub = nil
	if fake.getByOrderNumberReturnsOnCall == nil {
		fake.getByOrderNumberReturnsOnCall = make(map[int]struct {
			result1 *models.SalesOrder
			result2 error
		})
	}
	fake.getByOrderNumberReturnsOnCall[i] = struct {
		result1 *models.SalesOrder
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderRepository) GetItem(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (*models.SalesOrderItem, error) {
	fake.getItemMutex.Lock()
	ret, specificReturn := fake.getItemReturnsOnCall[len(fake.getItemArgsForCall)]
	fake.getItemArgsForCall = append(fake.getItemArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.GetItemStub
	fakeReturns := fake.getItemReturns
	fake.recordInvocation("GetItem", []interface{}{arg1, arg2, arg3})
	fake.getItemMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSalesOrderRepository) GetItemCallCount() int {
	fake.getItemMutex.RLock()
	defer fake.getItemMutex.RUnlock()
	return len(fake.getItemArgsForCall)
}

func (fake *FakeSalesOrderRepository) GetItemCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (*models.SalesOrderItem, error)) {
	fake.getItemMutex.Lock()
	defer fake.getItemMutex.Unlock()
	fake.GetItemStub = stub
}

func (fake *FakeSalesOrderRepository) GetItemArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.getItemMutex.RLock()
	defer fake.getItemMutex.RUnlock()
	argsForCall := fake.getItemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSalesOrderRepository) GetItemReturns(result1 *models.SalesOrderItem, result2 error) {
	fake.getItemMutex.Lock()
	defer fake.getItemMutex.Unlock()
	fake.GetItemStub = nil
	fake.getItemReturns = struct {
		result1 *models.SalesOrderItem
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderRepository) GetItemReturnsOnCall(i int, result1 *models.SalesOrderItem, result2 error) {
	fake.getItemMutex.Lock()
	defer fake.getItemMutex.Unlock()
	fake.GetItemStub = nil
	if fake.getItemReturnsOnCall == nil {
		fake.getItemReturnsOnCall = make(map[int]struct {
			result1 *models.SalesOrderItem
			result2 error
		})
	}
	fake.getItemReturnsOnCall[i] = struct {
		result1 *models.SalesOrderItem
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderRepository) ListByClient(arg1 context.Context, arg2 uuid.UUID, arg3 int, arg4 int) ([]*models.SalesOrder, error) {
	fake.listByClientMutex.Lock()
	ret, specificReturn := fake.listByClientReturnsOnCall[len(fake.listByClientArgsForCall)]
	fake.listByClientArgsForCall = append(fake.listByClientArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListByClientStub
	fakeReturns := fake.listByClientReturns
	fake.recordInvocation("ListByClient", []interface{}{arg1, arg2, arg3, arg4})
	fake.listByClientMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSalesOrderRepository) ListByClientCallCount() int {
	fake.listByClientMutex.RLock()
	defer fake.listByClientMutex.RUnlock()
	return len(fake.listByClientArgsForCall)
}

func (fake *FakeSalesOrderRepository) ListByClientCalls(stub func(context.Context, uuid.UUID, int, int) ([]*models.SalesOrder, error)) {
	fake.listByClientMutex.Lock()
	defer fake.listByClientMutex.Unlock()
	fake.ListByClientStub = stub
}

func (fake *FakeSalesOrderRepository) ListByClientArgsForCall(i int) (context.Context, uuid.UUID, int, int) {
	fake.listByClientMutex.RLock()
	defer fake.listByClientMutex.RUnlock()
	argsForCall := fake.listByClientArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeSalesOrderRepository) ListByClientReturns(result1 []*models.SalesOrder, result2 error) {
	fake.listByClientMutex.Lock()
	defer fake.listByClientMutex.Unlock()
	fake.ListByClientStub = nil
	fake.listByClientReturns = struct {
		result1 []*models.SalesOrder
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderRepository) ListByClientReturnsOnCall(i int, result1 []*models.SalesOrder, result2 error) {
	fake.listByClientMutex.Lock()
	defer fake.listByClientMutex.Unlock()
	fake.ListByClientStub = nil
	if fake.listByClientReturnsOnCall == nil {
		fake.listByClientReturnsOnCall = make(map[int]struct {
			result1 []*models.SalesOrder
			result2 error
		})
	}
	fake.listByClientReturnsOnCall[i] = struct {
		result1 []*models.SalesOrder
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderRepository) ListByCustomer(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 int, arg5 int) ([]*models.SalesOrder, error) {
	fake.listByCustomerMutex.Lock()
	ret, specificReturn := fake.listByCustomerReturnsOnCall[len(fake.listByCustomerArgsForCall)]
	fake.listByCustomerArgsForCall = append(fake.listByCustomerArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ListByCustomerStub
	fakeReturns := fake.listByCustomerReturns
	fake.recordInvocation("ListByCustomer", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.listByCustomerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSalesOrderRepository) ListByCustomerCallCount() int {
	fake.listByCustomerMutex.RLock()
	defer fake.listByCustomerMutex.RUnlock()
	return len(fake.listByCustomerArgsForCall)
}

func (fake *FakeSalesOrderRepository) ListByCustomerCalls(stub func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]*models.SalesOrder, error)) {
	fake.listByCustomerMutex.Lock()
	defer fake.listByCustomerMutex.Unlock()
	fake.ListByCustomerStub = stub
}

func (fake *FakeSalesOrderRepository) ListByCustomerArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, int, int) {
	fake.listByCustomerMutex.RLock()
	defer fake.listByCustomerMutex.RUnlock()
	argsForCall := fake.listByCustomerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeSalesOrderRepository) ListByCustomerReturns(result1 []*models.SalesOrder, result2 error) {
	fake.listByCustomerMutex.Lock()
	defer fake.listByCustomerMutex.Unlock()
	fake.ListByCustomerStub = nil
	fake.listByCustomerReturns = struct {
		result1 []*models.SalesOrder
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderRepository) ListByCustomerReturnsOnCall(i int, result1 []*models.SalesOrder, result2 error) {
	fake.listByCustomerMutex.Lock()
	defer fake.listByCustomerMutex.Unlock()
	fake.ListByCustomerStub = nil
	if fake.listByCustomerReturnsOnCall == nil {
		fake.listByCustomerReturnsOnCall = make(map[int]struct {
			result1 []*models.SalesOrder
			result2 error
		})
	}
	fake.listByCustomerReturnsOnCall[i] = struct {
		result1 []*models.SalesOrder
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderRepository) ListByStatus(arg1 context.Context, arg2 uuid.UUID, arg3 models.SalesOrderStatus, arg4 int, arg5 int) ([]*models.SalesOrder, error) {
	fake.listByStatusMutex.Lock()
	ret, specificReturn := fake.listByStatusReturnsOnCall[len(fake.listByStatusArgsForCall)]
	fake.listByStatusArgsForCall = append(fake.listByStatusArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 models.SalesOrderStatus
		arg4 int
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ListByStatusStub
	fakeReturns := fake.listByStatusReturns
	fake.recordInvocation("ListByStatus", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.listByStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSalesOrderRepository) ListByStatusCallCount() int {
	fake.listByStatusMutex.RLock()
	defer fake.listByStatusMutex.RUnlock()
	return len(fake.listByStatusArgsForCall)
}

func (fake *FakeSalesOrderRepository) ListByStatusCalls(stub func(context.Context, uuid.UUID, models.SalesOrderStatus, int, int) ([]*models.SalesOrder, error)) {
	fake.listByStatusMutex.Lock()
	defer fake.listByStatusMutex.Unlock()
	fake.ListByStatusStub = stub
}

func (fake *FakeSalesOrderRepository) ListByStatusArgsForCall(i int) (context.Context, uuid.UUID, models.SalesOrderStatus, int, int) {
	fake.listByStatusMutex.RLock()
	defer fake.listByStatusMutex.RUnlock()
	argsForCall := fake.listByStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeSalesOrderRepository) ListByStatusReturns(result1 []*models.SalesOrder, result2 error) {
	fake.listByStatusMutex.Lock()
	defer fake.listByStatusMutex.Unlock()
	fake.ListByStatusStub = nil
	fake.listByStatusReturns = struct {
		result1 []*models.SalesOrder
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderRepository) ListByStatusReturnsOnCall(i int, result1 []*models.SalesOrder, result2 error) {
	fake.listByStatusMutex.Lock()
	defer fake.listByStatusMutex.Unlock()
	fake.ListByStatusStub = nil
	if fake.listByStatusReturnsOnCall == nil {
		fake.listByStatusReturnsOnCall = make(map[int]struct {
			result1 []*models.SalesOrder
			result2 error
		})
	}
	fake.listByStatusReturnsOnCall[i] = struct {
		result1 []*models.SalesOrder
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderRepository) ListItemsBySO(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) ([]*models.SalesOrderItem, error) {
	fake.listItemsBySOMutex.Lock()
	ret, specificReturn := fake.listItemsBySOReturnsOnCall[len(fake.listItemsBySOArgsForCall)]
	fake.listItemsBySOArgsForCall = append(fake.listItemsBySOArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.ListItemsBySOStub
	fakeReturns := fake.listItemsBySOReturns
	fake.recordInvocation("ListItemsBySO", []interface{}{arg1, arg2, arg3})
	fake.listItemsBySOMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSalesOrderRepository) ListItemsBySOCallCount() int {
	fake.listItemsBySOMutex.RLock()
	defer fake.listItemsBySOMutex.RUnlock()
	return len(fake.listItemsBySOArgsForCall)
}

func (fake *FakeSalesOrderRepository) ListItemsBySOCalls(stub func(context.Context, uuid.UUID, uuid.UUID) ([]*models.SalesOrderItem, error)) {
	fake.listItemsBySOMutex.Lock()
	defer fake.listItemsBySOMutex.Unlock()
	fake.ListItemsBySOStub = stub
}

func (fake *FakeSalesOrderRepository) ListItemsBySOArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.listItemsBySOMutex.RLock()
	defer fake.listItemsBySOMutex.RUnlock()
	argsForCall := fake.listItemsBySOArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSalesOrderRepository) ListItemsBySOReturns(result1 []*models.SalesOrderItem, result2 error) {
	fake.listItemsBySOMutex.Lock()
	defer fake.listItemsBySOMutex.Unlock()
	fake.ListItemsBySOStub = nil
	fake.listItemsBySOReturns = struct {
		result1 []*models.SalesOrderItem
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderRepository) ListItemsBySOReturnsOnCall(i int, result1 []*models.SalesOrderItem, result2 error) {
	fake.listItemsBySOMutex.Lock()
	defer fake.listItemsBySOMutex.Unlock()
	fake.ListItemsBySOStub = nil
	if fake.listItemsBySOReturnsOnCall == nil {
		fake.listItemsBySOReturnsOnCall = make(map[int]struct {
			result1 []*models.SalesOrderItem
			result2 error
		})
	}
	fake.listItemsBySOReturnsOnCall[i] = struct {
		result1 []*models.SalesOrderItem
		result2 error
	}{result1, result2}
}

func (fake *FakeSalesOrderRepository) Update(arg1 context.Context, arg2 *models.SalesOrder) error {
	fake.updateMutex.Lock()
	ret, specificReturn := fake.updateReturnsOnCall[len(fake.updateArgsForCall)]
	fake.updateArgsForCall = append(fake.updateArgsForCall, struct {
		arg1 context.Context
		arg2 *models.SalesOrder
	}{arg1, arg2})
	stub := fake.UpdateStub
	fakeReturns := fake.updateReturns
	fake.recordInvocation("Update", []interface{}{arg1, arg2})
	fake.updateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSalesOrderRepository) UpdateCallCount() int {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return len(fake.updateArgsForCall)
}

func (fake *FakeSalesOrderRepository) UpdateCalls(stub func(context.Context, *models.SalesOrder) error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = stub
}

func (fake *FakeSalesOrderRepository) UpdateArgsForCall(i int) (context.Context, *models.SalesOrder) {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	argsForCall := fake.updateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSalesOrderRepository) UpdateReturns(result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	fake.updateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderRepository) UpdateReturnsOnCall(i int, result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	if fake.updateReturnsOnCall == nil {
		fake.updateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderRepository) UpdateItem(arg1 context.Context, arg2 *models.SalesOrderItem) error {
	fake.updateItemMutex.Lock()
	ret, specificReturn := fake.updateItemReturnsOnCall[len(fake.updateItemArgsForCall)]
	fake.updateItemArgsForCall = append(fake.updateItemArgsForCall, struct {
		arg1 context.Context
		arg2 *models.SalesOrderItem
	}{arg1, arg2})
	stub := fake.UpdateItemStub
	fakeReturns := fake.updateItemReturns
	fake.recordInvocation("UpdateItem", []interface{}{arg1, arg2})
	fake.updateItemMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSalesOrderRepository) UpdateItemCallCount() int {
	fake.updateItemMutex.RLock()
	defer fake.updateItemMutex.RUnlock()
	return len(fake.updateItemArgsForCall)
}

func (fake *FakeSalesOrderRepository) UpdateItemCalls(stub func(context.Context, *models.SalesOrderItem) error) {
	fake.updateItemMutex.Lock()
	defer fake.updateItemMutex.Unlock()
	fake.UpdateItemStub = stub
}

func (fake *FakeSalesOrderRepository) UpdateItemArgsForCall(i int) (context.Context, *models.SalesOrderItem) {
	fake.updateItemMutex.RLock()
	defer fake.updateItemMutex.RUnlock()
	argsForCall := fake.updateItemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSalesOrderRepository) UpdateItemReturns(result1 error) {
	fake.updateItemMutex.Lock()
	defer fake.updateItemMutex.Unlock()
	fake.UpdateItemStub = nil
	fake.updateItemReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderRepository) UpdateItemReturnsOnCall(i int, result1 error) {
	fake.updateItemMutex.Lock()
	defer fake.updateItemMutex.Unlock()
	fake.UpdateItemStub = nil
	if fake.updateItemReturnsOnCall == nil {
		fake.updateItemReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateItemReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSalesOrderRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSalesOrderRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repositories.SalesOrderRepository = new(FakeSalesOrderRepository)
