// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/yourorg/shoppilot/app/repositories"
	"github.com/yourorg/shoppilot/internal/models"
)

type FakeInventoryMovementRepository struct {
	CreateStub        func(context.Context, *models.InventoryMovement) error
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 context.Context
		arg2 *models.InventoryMovement
	}
	createReturns struct {
		result1 error
	}
	createReturnsOnCall map[int]struct {
		result1 error
	}
	GetByIDStub        func(context.Context, uuid.UUID, uuid.UUID) (*models.InventoryMovement, error)
	getByIDMutex       sync.RWMutex
	getByIDArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	getByIDReturns struct {
		result1 *models.InventoryMovement
		result2 error
	}
	getByIDReturnsOnCall map[int]struct {
		result1 *models.InventoryMovement
		result2 error
	}
	ListByReferenceStub        func(context.Context, uuid.UUID, string, uuid.UUID) ([]*models.InventoryMovement, error)
	listByReferenceMutex       sync.RWMutex
	listByReferenceArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
		arg4 uuid.UUID
	}
	listByReferenceReturns struct {
		result1 []*models.InventoryMovement
		result2 error
	}
	listByReferenceReturnsOnCall map[int]struct {
		result1 []*models.InventoryMovement
		result2 error
	}
	ListByShopStub        func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]*models.InventoryMovement, error)
	listByShopMutex       sync.RWMutex
	listByShopArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
		arg5 int
	}
	listByShopReturns struct {
		result1 []*models.InventoryMovement
		result2 error
	}
	listByShopReturnsOnCall map[int]struct {
		result1 []*models.InventoryMovement
		result2 error
	}
	ListByTypeStub        func(context.Context, uuid.UUID, models.InventoryMovementType, int, int) ([]*models.InventoryMovement, error)
	listByTypeMutex       sync.RWMutex
	listByTypeArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 models.InventoryMovementType
		arg4 int
		arg5 int
	}
	listByTypeReturns struct {
		result1 []*models.InventoryMovement
		result2 error
	}
	listByTypeReturnsOnCall map[int]struct {
		result1 []*models.InventoryMovement
		result2 error
	}
	ListByVariantStub        func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]*models.InventoryMovement, error)
	listByVariantMutex       sync.RWMutex
	listByVariantArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
		arg5 int
	}
	listByVariantReturns struct {
		result1 []*models.InventoryMovement
		result2 error
	}
	listByVariantReturnsOnCall map[int]struct {
		result1 []*models.InventoryMovement
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeInventoryMovementRepository) Create(arg1 context.Context, arg2 *models.InventoryMovement) error {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 context.Context
		arg2 *models.InventoryMovement
	}{arg1, arg2})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeInventoryMovementRepository) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeInventoryMovementRepository) CreateCalls(stub func(context.Context, *models.InventoryMovement) error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeInventoryMovementRepository) CreateArgsForCall(i int) (context.Context, *models.InventoryMovement) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeInventoryMovementRepository) CreateReturns(result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeInventoryMovementRepository) CreateReturnsOnCall(i int, result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeInventoryMovementRepository) GetByID(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (*models.InventoryMovement, error) {
	fake.getByIDMutex.Lock()
	ret, specificReturn := fake.getByIDReturnsOnCall[len(fake.getByIDArgsForCall)]
	fake.getByIDArgsForCall = append(fake.getByIDArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.GetByIDStub
	fakeReturns := fake.getByIDReturns
	fake.recordInvocation("GetByID", []interface{}{arg1, arg2, arg3})
	fake.getByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInventoryMovementRepository) GetByIDCallCount() int {
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	return len(fake.getByIDArgsForCall)
}

func (fake *FakeInventoryMovementRepository) GetByIDCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (*models.InventoryMovement, error)) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = stub
}

func (fake *FakeInventoryMovementRepository) GetByIDArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	argsForCall := fake.getByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeInventoryMovementRepository) GetByIDReturns(result1 *models.InventoryMovement, result2 error) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = nil
	fake.getByIDReturns = struct {
		result1 *models.InventoryMovement
		result2 error
	}{result1, result2}
}

func (fake *FakeInventoryMovementRepository) GetByIDReturnsOnCall(i int, result1 *models.InventoryMovement, result2 error) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = nil
	if fake.getByIDReturnsOnCall == nil {
		fake.getByIDReturnsOnCall = make(map[int]struct {
			result1 *models.InventoryMovement
			result2 error
		})
	}
	fake.getByIDReturnsOnCall[i] = struct {
		result1 *models.InventoryMovement
		result2 error
	}{result1, result2}
}

func (fake *FakeInventoryMovementRepository) ListByReference(arg1 context.Context, arg2 uuid.UUID, arg3 string, arg4 uuid.UUID) ([]*models.InventoryMovement, error) {
	fake.listByReferenceMutex.Lock()
	ret, specificReturn := fake.listByReferenceReturnsOnCall[len(fake.listByReferenceArgsForCall)]
	fake.listByReferenceArgsForCall = append(fake.listByReferenceArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
		arg4 uuid.UUID
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListByReferenceStub
	fakeReturns := fake.listByReferenceReturns
	fake.recordInvocation("ListByReference", []interface{}{arg1, arg2, arg3, arg4})
	fake.listByReferenceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInventoryMovementRepository) ListByReferenceCallCount() int {
	fake.listByReferenceMutex.RLock()
	defer fake.listByReferenceMutex.RUnlock()
	return len(fake.listByReferenceArgsForCall)
}

func (fake *FakeInventoryMovementRepository) ListByReferenceCalls(stub func(context.Context, uuid.UUID, string, uuid.UUID) ([]*models.InventoryMovement, error)) {
	fake.listByReferenceMutex.Lock()
	defer fake.listByReferenceMutex.Unlock()
	fake.ListByReferenceStub = stub
}

func (fake *FakeInventoryMovementRepository) ListByReferenceArgsForCall(i int) (context.Context, uuid.UUID, string, uuid.UUID) {
	fake.listByReferenceMutex.RLock()
	defer fake.listByReferenceMutex.RUnlock()
	argsForCall := fake.listByReferenceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeInventoryMovementRepository) ListByReferenceReturns(result1 []*models.InventoryMovement, result2 error) {
	fake.listByReferenceMutex.Lock()
	defer fake.listByReferenceMutex.Unlock()
	fake.ListByReferenceStub = nil
	fake.listByReferenceReturns = struct {
		result1 []*models.InventoryMovement
		result2 error
	}{result1, result2}
}

func (fake *FakeInventoryMovementRepository) ListByReferenceReturnsOnCall(i int, result1 []*models.InventoryMovement, result2 error) {
	fake.listByReferenceMutex.Lock()
	defer fake.listByReferenceMutex.Unlock()
	fake.ListByReferenceStub = nil
	if fake.listByReferenceReturnsOnCall == nil {
		fake.listByReferenceReturnsOnCall = make(map[int]struct {
			result1 []*models.InventoryMovement
			result2 error
		})
	}
	fake.listByReferenceReturnsOnCall[i] = struct {
		result1 []*models.InventoryMovement
		result2 error
	}{result1, result2}
}

func (fake *FakeInventoryMovementRepository) ListByShop(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 int, arg5 int) ([]*models.InventoryMovement, error) {
	fake.listByShopMutex.Lock()
	ret, specificReturn := fake.listByShopReturnsOnCall[len(fake.listByShopArgsForCall)]
	fake.listByShopArgsForCall = append(fake.listByShopArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ListByShopStub
	fakeReturns := fake.listByShopReturns
	fake.recordInvocation("ListByShop", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.listByShopMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInventoryMovementRepository) ListByShopCallCount() int {
	fake.listByShopMutex.RLock()
	defer fake.listByShopMutex.RUnlock()
	return len(fake.listByShopArgsForCall)
}

func (fake *FakeInventoryMovementRepository) ListByShopCalls(stub func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]*models.InventoryMovement, error)) {
	fake.listByShopMutex.Lock()
	defer fake.listByShopMutex.Unlock()
	fake.ListByShopStub = stub
}

func (fake *FakeInventoryMovementRepository) ListByShopArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, int, int) {
	fake.listByShopMutex.RLock()
	defer fake.listByShopMutex.RUnlock()
	argsForCall := fake.listByShopArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeInventoryMovementRepository) ListByShopReturns(result1 []*models.InventoryMovement, result2 error) {
	fake.listByShopMutex.Lock()
	defer fake.listByShopMutex.Unlock()
	fake.ListByShopStub = nil
	fake.listByShopReturns = struct {
		result1 []*models.InventoryMovement
		result2 error
	}{result1, result2}
}

func (fake *FakeInventoryMovementRepository) ListByShopReturnsOnCall(i int, result1 []*models.InventoryMovement, result2 error) {
	fake.listByShopMutex.Lock()
	defer fake.listByShopMutex.Unlock()
	fake.ListByShopStub = nil
	if fake.listByShopReturnsOnCall == nil {
		fake.listByShopReturnsOnCall = make(map[int]struct {
			result1 []*models.InventoryMovement
			result2 error
		})
	}
	fake.listByShopReturnsOnCall[i] = struct {
		result1 []*models.InventoryMovement
		result2 error
	}{result1, result2}
}

func (fake *FakeInventoryMovementRepository) ListByType(arg1 context.Context, arg2 uuid.UUID, arg3 models.InventoryMovementType, arg4 int, arg5 int) ([]*models.InventoryMovement, error) {
	fake.listByTypeMutex.Lock()
	ret, specificReturn := fake.listByTypeReturnsOnCall[len(fake.listByTypeArgsForCall)]
	fake.listByTypeArgsForCall = append(fake.listByTypeArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 models.InventoryMovementType
		arg4 int
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ListByTypeStub
	fakeReturns := fake.listByTypeReturns
	fake.recordInvocation("ListByType", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.listByTypeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInventoryMovementRepository) ListByTypeCallCount() int {
	fake.listByTypeMutex.RLock()
	defer fake.listByTypeMutex.RUnlock()
	return len(fake.listByTypeArgsForCall)
}

func (fake *FakeInventoryMovementRepository) ListByTypeCalls(stub func(context.Context, uuid.UUID, models.InventoryMovementType, int, int) ([]*models.InventoryMovement, error)) {
	fake.listByTypeMutex.Lock()
	defer fake.listByTypeMutex.Unlock()
	fake.ListByTypeStub = stub
}

func (fake *FakeInventoryMovementRepository) ListByTypeArgsForCall(i int) (context.Context, uuid.UUID, models.InventoryMovementType, int, int) {
	fake.listByTypeMutex.RLock()
	defer fake.listByTypeMutex.RUnlock()
	argsForCall := fake.listByTypeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeInventoryMovementRepository) ListByTypeReturns(result1 []*models.InventoryMovement, result2 error) {
	fake.listByTypeMutex.Lock()
	defer fake.listByTypeMutex.Unlock()
	fake.ListByTypeStub = nil
	fake.listByTypeReturns = struct {
		result1 []*models.InventoryMovement
		result2 error
	}{result1, result2}
}

func (fake *FakeInventoryMovementRepository) ListByTypeReturnsOnCall(i int, result1 []*models.InventoryMovement, result2 error) {
	fake.listByTypeMutex.Lock()
	defer fake.listByTypeMutex.Unlock()
	fake.ListByTypeStub = nil
	if fake.listByTypeReturnsOnCall == nil {
		fake.listByTypeReturnsOnCall = make(map[int]struct {
			result1 []*models.InventoryMovement
			result2 error
		})
	}
	fake.listByTypeReturnsOnCall[i] = struct {
		result1 []*models.InventoryMovement
		result2 error
	}{result1, result2}
}

func (fake *FakeInventoryMovementRepository) ListByVariant(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID, arg4 int, arg5 int) ([]*models.InventoryMovement, error) {
	fake.listByVariantMutex.Lock()
	ret, specificReturn := fake.listByVariantReturnsOnCall[len(fake.listByVariantArgsForCall)]
	fake.listByVariantArgsForCall = append(fake.listByVariantArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
		arg4 int
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ListByVariantStub
	fakeReturns := fake.listByVariantReturns
	fake.recordInvocation("ListByVariant", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.listByVariantMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInventoryMovementRepository) ListByVariantCallCount() int {
	fake.listByVariantMutex.RLock()
	defer fake.listByVariantMutex.RUnlock()
	return len(fake.listByVariantArgsForCall)
}

func (fake *FakeInventoryMovementRepository) ListByVariantCalls(stub func(context.Context, uuid.UUID, uuid.UUID, int, int) ([]*models.InventoryMovement, error)) {
	fake.listByVariantMutex.Lock()
	defer fake.listByVariantMutex.Unlock()
	fake.ListByVariantStub = stub
}

func (fake *FakeInventoryMovementRepository) ListByVariantArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID, int, int) {
	fake.listByVariantMutex.RLock()
	defer fake.listByVariantMutex.RUnlock()
	argsForCall := fake.listByVariantArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeInventoryMovementRepository) ListByVariantReturns(result1 []*models.InventoryMovement, result2 error) {
	fake.listByVariantMutex.Lock()
	defer fake.listByVariantMutex.Unlock()
	fake.ListByVariantStub = nil
	fake.listByVariantReturns = struct {
		result1 []*models.InventoryMovement
		result2 error
	}{result1, result2}
}

func (fake *FakeInventoryMovementRepository) ListByVariantReturnsOnCall(i int, result1 []*models.InventoryMovement, result2 error) {
	fake.listByVariantMutex.Lock()
	defer fake.listByVariantMutex.Unlock()
	fake.ListByVariantStub = nil
	if fake.listByVariantReturnsOnCall == nil {
		fake.listByVariantReturnsOnCall = make(map[int]struct {
			result1 []*models.InventoryMovement
			result2 error
		})
	}
	fake.listByVariantReturnsOnCall[i] = struct {
		result1 []*models.InventoryMovement
		result2 error
	}{result1, result2}
}

func (fake *FakeInventoryMovementRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeInventoryMovementRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repositories.InventoryMovementRepository = new(FakeInventoryMovementRepository)
