// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/google/uuid"
	"github.com/yourorg/shoppilot/app/repositories"
	"github.com/yourorg/shoppilot/internal/models"
)

type FakeSupplierRepository struct {
	CreateStub        func(context.Context, *models.Supplier) error
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 context.Context
		arg2 *models.Supplier
	}
	createReturns struct {
		result1 error
	}
	createReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteStub        func(context.Context, uuid.UUID, uuid.UUID) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	GetByCodeStub        func(context.Context, uuid.UUID, string) (*models.Supplier, error)
	getByCodeMutex       sync.RWMutex
	getByCodeArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}
	getByCodeReturns struct {
		result1 *models.Supplier
		result2 error
	}
	getByCodeReturnsOnCall map[int]struct {
		result1 *models.Supplier
		result2 error
	}
	GetByIDStub        func(context.Context, uuid.UUID, uuid.UUID) (*models.Supplier, error)
	getByIDMutex       sync.RWMutex
	getByIDArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}
	getByIDReturns struct {
		result1 *models.Supplier
		result2 error
	}
	getByIDReturnsOnCall map[int]struct {
		result1 *models.Supplier
		result2 error
	}
	ListActiveStub        func(context.Context, uuid.UUID, int, int) ([]*models.Supplier, error)
	listActiveMutex       sync.RWMutex
	listActiveArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}
	listActiveReturns struct {
		result1 []*models.Supplier
		result2 error
	}
	listActiveReturnsOnCall map[int]struct {
		result1 []*models.Supplier
		result2 error
	}
	ListByClientStub        func(context.Context, uuid.UUID, int, int) ([]*models.Supplier, error)
	listByClientMutex       sync.RWMutex
	listByClientArgsForCall []struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}
	listByClientReturns struct {
		result1 []*models.Supplier
		result2 error
	}
	listByClientReturnsOnCall map[int]struct {
		result1 []*models.Supplier
		result2 error
	}
	UpdateStub        func(context.Context, *models.Supplier) error
	updateMutex       sync.RWMutex
	updateArgsForCall []struct {
		arg1 context.Context
		arg2 *models.Supplier
	}
	updateReturns struct {
		result1 error
	}
	updateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSupplierRepository) Create(arg1 context.Context, arg2 *models.Supplier) error {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 context.Context
		arg2 *models.Supplier
	}{arg1, arg2})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSupplierRepository) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeSupplierRepository) CreateCalls(stub func(context.Context, *models.Supplier) error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeSupplierRepository) CreateArgsForCall(i int) (context.Context, *models.Supplier) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSupplierRepository) CreateReturns(result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSupplierRepository) CreateReturnsOnCall(i int, result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSupplierRepository) Delete(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.DeleteStub
	fakeReturns := fake.deleteReturns
	fake.recordInvocation("Delete", []interface{}{arg1, arg2, arg3})
	fake.deleteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSupplierRepository) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeSupplierRepository) DeleteCalls(stub func(context.Context, uuid.UUID, uuid.UUID) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakeSupplierRepository) DeleteArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSupplierRepository) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSupplierRepository) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSupplierRepository) GetByCode(arg1 context.Context, arg2 uuid.UUID, arg3 string) (*models.Supplier, error) {
	fake.getByCodeMutex.Lock()
	ret, specificReturn := fake.getByCodeReturnsOnCall[len(fake.getByCodeArgsForCall)]
	fake.getByCodeArgsForCall = append(fake.getByCodeArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.GetByCodeStub
	fakeReturns := fake.getByCodeReturns
	fake.recordInvocation("GetByCode", []interface{}{arg1, arg2, arg3})
	fake.getByCodeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSupplierRepository) GetByCodeCallCount() int {
	fake.getByCodeMutex.RLock()
	defer fake.getByCodeMutex.RUnlock()
	return len(fake.getByCodeArgsForCall)
}

func (fake *FakeSupplierRepository) GetByCodeCalls(stub func(context.Context, uuid.UUID, string) (*models.Supplier, error)) {
	fake.getByCodeMutex.Lock()
	defer fake.getByCodeMutex.Unlock()
	fake.GetByCodeStub = stub
}

func (fake *FakeSupplierRepository) GetByCodeArgsForCall(i int) (context.Context, uuid.UUID, string) {
	fake.getByCodeMutex.RLock()
	defer fake.getByCodeMutex.RUnlock()
	argsForCall := fake.getByCodeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSupplierRepository) GetByCodeReturns(result1 *models.Supplier, result2 error) {
	fake.getByCodeMutex.Lock()
	defer fake.getByCodeMutex.Unlock()
	fake.GetByCodeStub = nil
	fake.getByCodeReturns = struct {
		result1 *models.Supplier
		result2 error
	}{result1, result2}
}

func (fake *FakeSupplierRepository) GetByCodeReturnsOnCall(i int, result1 *models.Supplier, result2 error) {
	fake.getByCodeMutex.Lock()
	defer fake.getByCodeMutex.Unlock()
	fake.GetByCodeStub = nil
	if fake.getByCodeReturnsOnCall == nil {
		fake.getByCodeReturnsOnCall = make(map[int]struct {
			result1 *models.Supplier
			result2 error
		})
	}
	fake.getByCodeReturnsOnCall[i] = struct {
		result1 *models.Supplier
		result2 error
	}{result1, result2}
}

func (fake *FakeSupplierRepository) GetByID(arg1 context.Context, arg2 uuid.UUID, arg3 uuid.UUID) (*models.Supplier, error) {
	fake.getByIDMutex.Lock()
	ret, specificReturn := fake.getByIDReturnsOnCall[len(fake.getByIDArgsForCall)]
	fake.getByIDArgsForCall = append(fake.getByIDArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 uuid.UUID
	}{arg1, arg2, arg3})
	stub := fake.GetByIDStub
	fakeReturns := fake.getByIDReturns
	fake.recordInvocation("GetByID", []interface{}{arg1, arg2, arg3})
	fake.getByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSupplierRepository) GetByIDCallCount() int {
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	return len(fake.getByIDArgsForCall)
}

func (fake *FakeSupplierRepository) GetByIDCalls(stub func(context.Context, uuid.UUID, uuid.UUID) (*models.Supplier, error)) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = stub
}

func (fake *FakeSupplierRepository) GetByIDArgsForCall(i int) (context.Context, uuid.UUID, uuid.UUID) {
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	argsForCall := fake.getByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSupplierRepository) GetByIDReturns(result1 *models.Supplier, result2 error) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = nil
	fake.getByIDReturns = struct {
		result1 *models.Supplier
		result2 error
	}{result1, result2}
}

func (fake *FakeSupplierRepository) GetByIDReturnsOnCall(i int, result1 *models.Supplier, result2 error) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = nil
	if fake.getByIDReturnsOnCall == nil {
		fake.getByIDReturnsOnCall = make(map[int]struct {
			result1 *models.Supplier
			result2 error
		})
	}
	fake.getByIDReturnsOnCall[i] = struct {
		result1 *models.Supplier
		result2 error
	}{result1, result2}
}

func (fake *FakeSupplierRepository) ListActive(arg1 context.Context, arg2 uuid.UUID, arg3 int, arg4 int) ([]*models.Supplier, error) {
	fake.listActiveMutex.Lock()
	ret, specificReturn := fake.listActiveReturnsOnCall[len(fake.listActiveArgsForCall)]
	fake.listActiveArgsForCall = append(fake.listActiveArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListActiveStub
	fakeReturns := fake.listActiveReturns
	fake.recordInvocation("ListActive", []interface{}{arg1, arg2, arg3, arg4})
	fake.listActiveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSupplierRepository) ListActiveCallCount() int {
	fake.listActiveMutex.RLock()
	defer fake.listActiveMutex.RUnlock()
	return len(fake.listActiveArgsForCall)
}

func (fake *FakeSupplierRepository) ListActiveCalls(stub func(context.Context, uuid.UUID, int, int) ([]*models.Supplier, error)) {
	fake.listActiveMutex.Lock()
	defer fake.listActiveMutex.Unlock()
	fake.ListActiveStub = stub
}

func (fake *FakeSupplierRepository) ListActiveArgsForCall(i int) (context.Context, uuid.UUID, int, int) {
	fake.listActiveMutex.RLock()
	defer fake.listActiveMutex.RUnlock()
	argsForCall := fake.listActiveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeSupplierRepository) ListActiveReturns(result1 []*models.Supplier, result2 error) {
	fake.listActiveMutex.Lock()
	defer fake.listActiveMutex.Unlock()
	fake.ListActiveStub = nil
	fake.listActiveReturns = struct {
		result1 []*models.Supplier
		result2 error
	}{result1, result2}
}

func (fake *FakeSupplierRepository) ListActiveReturnsOnCall(i int, result1 []*models.Supplier, result2 error) {
	fake.listActiveMutex.Lock()
	defer fake.listActiveMutex.Unlock()
	fake.ListActiveStub = nil
	if fake.listActiveReturnsOnCall == nil {
		fake.listActiveReturnsOnCall = make(map[int]struct {
			result1 []*models.Supplier
			result2 error
		})
	}
	fake.listActiveReturnsOnCall[i] = struct {
		result1 []*models.Supplier
		result2 error
	}{result1, result2}
}

func (fake *FakeSupplierRepository) ListByClient(arg1 context.Context, arg2 uuid.UUID, arg3 int, arg4 int) ([]*models.Supplier, error) {
	fake.listByClientMutex.Lock()
	ret, specificReturn := fake.listByClientReturnsOnCall[len(fake.listByClientArgsForCall)]
	fake.listByClientArgsForCall = append(fake.listByClientArgsForCall, struct {
		arg1 context.Context
		arg2 uuid.UUID
		arg3 int
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.ListByClientStub
	fakeReturns := fake.listByClientReturns
	fake.recordInvocation("ListByClient", []interface{}{arg1, arg2, arg3, arg4})
	fake.listByClientMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSupplierRepository) ListByClientCallCount() int {
	fake.listByClientMutex.RLock()
	defer fake.listByClientMutex.RUnlock()
	return len(fake.listByClientArgsForCall)
}

func (fake *FakeSupplierRepository) ListByClientCalls(stub func(context.Context, uuid.UUID, int, int) ([]*models.Supplier, error)) {
	fake.listByClientMutex.Lock()
	defer fake.listByClientMutex.Unlock()
	fake.ListByClientStub = stub
}

func (fake *FakeSupplierRepository) ListByClientArgsForCall(i int) (context.Context, uuid.UUID, int, int) {
	fake.listByClientMutex.RLock()
	defer fake.listByClientMutex.RUnlock()
	argsForCall := fake.listByClientArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeSupplierRepository) ListByClientReturns(result1 []*models.Supplier, result2 error) {
	fake.listByClientMutex.Lock()
	defer fake.listByClientMutex.Unlock()
	fake.ListByClientStub = nil
	fake.listByClientReturns = struct {
		result1 []*models.Supplier
		result2 error
	}{result1, result2}
}

func (fake *FakeSupplierRepository) ListByClientReturnsOnCall(i int, result1 []*models.Supplier, result2 error) {
	fake.listByClientMutex.Lock()
	defer fake.listByClientMutex.Unlock()
	fake.ListByClientStub = nil
	if fake.listByClientReturnsOnCall == nil {
		fake.listByClientReturnsOnCall = make(map[int]struct {
			result1 []*models.Supplier
			result2 error
		})
	}
	fake.listByClientReturnsOnCall[i] = struct {
		result1 []*models.Supplier
		result2 error
	}{result1, result2}
}

func (fake *FakeSupplierRepository) Update(arg1 context.Context, arg2 *models.Supplier) error {
	fake.updateMutex.Lock()
	ret, specificReturn := fake.updateReturnsOnCall[len(fake.updateArgsForCall)]
	fake.updateArgsForCall = append(fake.updateArgsForCall, struct {
		arg1 context.Context
		arg2 *models.Supplier
	}{arg1, arg2})
	stub := fake.UpdateStub
	fakeReturns := fake.updateReturns
	fake.recordInvocation("Update", []interface{}{arg1, arg2})
	fake.updateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSupplierRepository) UpdateCallCount() int {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return len(fake.updateArgsForCall)
}

func (fake *FakeSupplierRepository) UpdateCalls(stub func(context.Context, *models.Supplier) error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = stub
}

func (fake *FakeSupplierRepository) UpdateArgsForCall(i int) (context.Context, *models.Supplier) {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	argsForCall := fake.updateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSupplierRepository) UpdateReturns(result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	fake.updateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSupplierRepository) UpdateReturnsOnCall(i int, result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	if fake.updateReturnsOnCall == nil {
		fake.updateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSupplierRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSupplierRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repositories.SupplierRepository = new(FakeSupplierRepository)
